---@meta game-Scripts-BountyLogic
local game = {}

function game.BountyBoardScreenDisplayCategory(a, b) end
---@alias game-Scripts-BountyLogic.BountyBoardScreenDisplayCategory ...

function game.BountyScreenScrollDown(a, b) end
---@alias game-Scripts-BountyLogic.BountyScreenScrollDown ...

function game.BountyScreenScrollUp(a, b) end
---@alias game-Scripts-BountyLogic.BountyScreenScrollUp ...

function game.BountyScreenUpdateIntensityEyes(a) end
---@alias game-Scripts-BountyLogic.BountyScreenUpdateIntensityEyes ...

function game.CheckPackagedBountyCompletion() end
---@alias game-Scripts-BountyLogic.CheckPackagedBountyCompletion ...

function game.CheckRandomBounties() end
---@alias game-Scripts-BountyLogic.CheckRandomBounties ...

function game.CheckShrineBounties() end
---@alias game-Scripts-BountyLogic.CheckShrineBounties ...

function game.CloseBountyBoardScreen(a, b) end
---@alias game-Scripts-BountyLogic.CloseBountyBoardScreen ...

function game.HasUnclearedBounty(a, b) end
---@alias game-Scripts-BountyLogic.HasUnclearedBounty ...

function game.HasUnviewedBounty(a, b) end
---@alias game-Scripts-BountyLogic.HasUnviewedBounty ...

function game.LoadActiveBountyPackages() end
---@alias game-Scripts-BountyLogic.LoadActiveBountyPackages ...

function game.MarkShrineBountyComplete(a, b) end
---@alias game-Scripts-BountyLogic.MarkShrineBountyComplete ...

function game.MouseOffBounty(a) end
---@alias game-Scripts-BountyLogic.MouseOffBounty ...

function game.MouseOverBounty(a) end
---@alias game-Scripts-BountyLogic.MouseOverBounty ...

function game.OpenBountyBoardScreen(a, b) end
---@alias game-Scripts-BountyLogic.OpenBountyBoardScreen ...

function game.RandomBountyProcessMetaUpgrades(a, b, c, d, e, f) end
---@alias game-Scripts-BountyLogic.RandomBountyProcessMetaUpgrades ...

function game.RestorePackagedBountyGameState() end
---@alias game-Scripts-BountyLogic.RestorePackagedBountyGameState ...

function game.StartPackagedBounty(a, b) end
---@alias game-Scripts-BountyLogic.StartPackagedBounty ...

function game.StoredGameStateInit(a) end
---@alias game-Scripts-BountyLogic.StoredGameStateInit ...

function game.UseBountyBoard(a, b) end
---@alias game-Scripts-BountyLogic.UseBountyBoard ...

return game