---@meta game-Scripts-CombatLogic
local game = {}

function game.ActivateFuse(a) end
---@alias game-Scripts-CombatLogic.ActivateFuse ...

function game.ActivateLuciferFuse(a) end
---@alias game-Scripts-CombatLogic.ActivateLuciferFuse ...

function game.ActivateManaReserveInvulnerability(a, b) end
---@alias game-Scripts-CombatLogic.ActivateManaReserveInvulnerability ...

function game.addCritMultiplier(a, b, c) end
---@alias game-Scripts-CombatLogic.addCritMultiplier ...

function game.addDamageMultiplier(a, b) end
---@alias game-Scripts-CombatLogic.addDamageMultiplier ...

function game.addDdMultiplier(a, b, c) end
---@alias game-Scripts-CombatLogic.addDdMultiplier ...

function game.AddEnemyHitShield(a) end
---@alias game-Scripts-CombatLogic.AddEnemyHitShield ...

function game.AddIncomingDamageModifier(a, b) end
---@alias game-Scripts-CombatLogic.AddIncomingDamageModifier ...

function game.AddLastStand(a) end
---@alias game-Scripts-CombatLogic.AddLastStand ...

function game.AddOnDamagedFunction(a, b) end
---@alias game-Scripts-CombatLogic.AddOnDamagedFunction ...

function game.AddOutgoingCritModifier(a, b) end
---@alias game-Scripts-CombatLogic.AddOutgoingCritModifier ...

function game.AddOutgoingDamageModifier(a, b) end
---@alias game-Scripts-CombatLogic.AddOutgoingDamageModifier ...

function game.AddOutgoingDoubleDamageModifier(a, b) end
---@alias game-Scripts-CombatLogic.AddOutgoingDoubleDamageModifier ...

function game.AddOutgoingLifestealModifier(a, b) end
---@alias game-Scripts-CombatLogic.AddOutgoingLifestealModifier ...

function game.AddPlaceholderEnemyCount() end
---@alias game-Scripts-CombatLogic.AddPlaceholderEnemyCount ...

function game.AddPlayerImmuneToForce(a) end
---@alias game-Scripts-CombatLogic.AddPlayerImmuneToForce ...

function game.AggroSpawns(a, b, c) end
---@alias game-Scripts-CombatLogic.AggroSpawns ...

function game.AIHealthThresholdReached(a) end
---@alias game-Scripts-CombatLogic.AIHealthThresholdReached ...

function game.AmmoPackPickupTrigger(a, b) end
---@alias game-Scripts-CombatLogic.AmmoPackPickupTrigger ...

function game.BlockDumbFireWeapons(a, b) end
---@alias game-Scripts-CombatLogic.BlockDumbFireWeapons ...

function game.CalcEasyModeMultiplier(a) end
---@alias game-Scripts-CombatLogic.CalcEasyModeMultiplier ...

function game.CalculateBaseDamage(a, b, c) end
---@alias game-Scripts-CombatLogic.CalculateBaseDamage ...

function game.CalculateBaseDamageAdditions(a, b, c) end
---@alias game-Scripts-CombatLogic.CalculateBaseDamageAdditions ...

function game.CalculateCritChance(a, b, c, d) end
---@alias game-Scripts-CombatLogic.CalculateCritChance ...

function game.CalculateDamageAdditions(a, b, c, d) end
---@alias game-Scripts-CombatLogic.CalculateDamageAdditions ...

function game.CalculateDamageMultipliers(a, b, c, d) end
---@alias game-Scripts-CombatLogic.CalculateDamageMultipliers ...

function game.CalculateDoubleDamageChance(a, b, c, d) end
---@alias game-Scripts-CombatLogic.CalculateDoubleDamageChance ...

function game.CalculateLifestealModifiers(a, b, c, d) end
---@alias game-Scripts-CombatLogic.CalculateLifestealModifiers ...

function game.CheckAllRequiredKillEnemiesDead(a) end
---@alias game-Scripts-CombatLogic.CheckAllRequiredKillEnemiesDead ...

function game.CheckBurningHitReaction(a, b, c) end
---@alias game-Scripts-CombatLogic.CheckBurningHitReaction ...

function game.CheckDashOverride(a) end
---@alias game-Scripts-CombatLogic.CheckDashOverride ...

function game.CheckImpactReaction(a, b, c, d) end
---@alias game-Scripts-CombatLogic.CheckImpactReaction ...

function game.CheckInvulnerabilityFrameTrigger(a, b) end
---@alias game-Scripts-CombatLogic.CheckInvulnerabilityFrameTrigger ...

function game.CheckLastStand(a, b) end
---@alias game-Scripts-CombatLogic.CheckLastStand ...

function game.CheckOnArmedHitEffect(a, b, c) end
---@alias game-Scripts-CombatLogic.CheckOnArmedHitEffect ...

function game.CheckOnKillWeaponUpgrades(a, b, c) end
---@alias game-Scripts-CombatLogic.CheckOnKillWeaponUpgrades ...

function game.CheckUnitInvulnerableHit(a, b) end
---@alias game-Scripts-CombatLogic.CheckUnitInvulnerableHit ...

function game.CleanupEnemies(a) end
---@alias game-Scripts-CombatLogic.CleanupEnemies ...

function game.CleanupEnemy(a) end
---@alias game-Scripts-CombatLogic.CleanupEnemy ...

function game.ClearGameplayElapsedTimeMultipliers() end
---@alias game-Scripts-CombatLogic.ClearGameplayElapsedTimeMultipliers ...

function game.Damage(a, b) end
---@alias game-Scripts-CombatLogic.Damage ...

function game.DamageEnemy(a, b) end
---@alias game-Scripts-CombatLogic.DamageEnemy ...

function game.DamageHero(a, b) end
---@alias game-Scripts-CombatLogic.DamageHero ...

function game.DelayedApplyForce(a) end
---@alias game-Scripts-CombatLogic.DelayedApplyForce ...

function game.DestroyOnDelay(a, b, c) end
---@alias game-Scripts-CombatLogic.DestroyOnDelay ...

function game.DisableAllyUnits() end
---@alias game-Scripts-CombatLogic.DisableAllyUnits ...

function game.DoBlock(a) end
---@alias game-Scripts-CombatLogic.DoBlock ...

function game.DoEnemyHealthBufferDeplete(a) end
---@alias game-Scripts-CombatLogic.DoEnemyHealthBufferDeplete ...

function game.DoEnemyHealthBuffered(a) end
---@alias game-Scripts-CombatLogic.DoEnemyHealthBuffered ...

function game.DoReaction(a, b, c) end
---@alias game-Scripts-CombatLogic.DoReaction ...

function game.DropMinorConsumable(a, b, c, d, e) end
---@alias game-Scripts-CombatLogic.DropMinorConsumable ...

function game.DropStoredAmmoHero(a, b) end
---@alias game-Scripts-CombatLogic.DropStoredAmmoHero ...

function game.EffectApply(a, b) end
---@alias game-Scripts-CombatLogic.EffectApply ...

function game.EffectClear(a, b) end
---@alias game-Scripts-CombatLogic.EffectClear ...

function game.EffectPostClearAll(a, b) end
---@alias game-Scripts-CombatLogic.EffectPostClearAll ...

function game.EndWeaponSlowMotion(a, b) end
---@alias game-Scripts-CombatLogic.EndWeaponSlowMotion ...

function game.EnemyDodge(a, b) end
---@alias game-Scripts-CombatLogic.EnemyDodge ...

function game.EnemyDodgeEnd(a, b) end
---@alias game-Scripts-CombatLogic.EnemyDodgeEnd ...

function game.EquipPlayerWeapon(a, b) end
---@alias game-Scripts-CombatLogic.EquipPlayerWeapon ...

function game.ExpireOnDelay(a, b, c) end
---@alias game-Scripts-CombatLogic.ExpireOnDelay ...

function game.FirstHealHitSetup(a, b) end
---@alias game-Scripts-CombatLogic.FirstHealHitSetup ...

function game.FreezeEscape(a) end
---@alias game-Scripts-CombatLogic.FreezeEscape ...

function game.FuseSpawns(a, b, c) end
---@alias game-Scripts-CombatLogic.FuseSpawns ...

function game.GameplaySetElapsedTimeMultiplier(a) end
---@alias game-Scripts-CombatLogic.GameplaySetElapsedTimeMultiplier ...

function game.GetGameplayElapsedTimeMultiplier(a) end
---@alias game-Scripts-CombatLogic.GetGameplayElapsedTimeMultiplier ...

function game.GetOutgoingDamageModifier(a, b) end
---@alias game-Scripts-CombatLogic.GetOutgoingDamageModifier ...

function game.GetPlayerAngle() end
---@alias game-Scripts-CombatLogic.GetPlayerAngle ...

function game.GetPlayerGameplayElapsedTimeMultiplier() end
---@alias game-Scripts-CombatLogic.GetPlayerGameplayElapsedTimeMultiplier ...

function game.GetWeaponData(a, b) end
---@alias game-Scripts-CombatLogic.GetWeaponData ...

function game.HandleDeathWeapon(a, b) end
---@alias game-Scripts-CombatLogic.HandleDeathWeapon ...

function game.HandleStoredProjectileDeath(a, b) end
---@alias game-Scripts-CombatLogic.HandleStoredProjectileDeath ...

function game.HasEffectWithEffectGroup(a, b) end
---@alias game-Scripts-CombatLogic.HasEffectWithEffectGroup ...

function game.HasLastStand(a) end
---@alias game-Scripts-CombatLogic.HasLastStand ...

function game.HasOutgoingCritModifierType(a, b) end
---@alias game-Scripts-CombatLogic.HasOutgoingCritModifierType ...

function game.HasVulnerabilityGenusEffect(a, b) end
---@alias game-Scripts-CombatLogic.HasVulnerabilityGenusEffect ...

function game.HitByFreezeWeapon(a) end
---@alias game-Scripts-CombatLogic.HitByFreezeWeapon ...

function game.IsLastStandManaReserveEligible() end
---@alias game-Scripts-CombatLogic.IsLastStandManaReserveEligible ...

function game.IsOnlyInvulnerableSource(a) end
---@alias game-Scripts-CombatLogic.IsOnlyInvulnerableSource ...

function game.IsPlayerInterruptible() end
---@alias game-Scripts-CombatLogic.IsPlayerInterruptible ...

function game.Kill(a, b) end
---@alias game-Scripts-CombatLogic.Kill ...

function game.KillEnemy(a, b) end
---@alias game-Scripts-CombatLogic.KillEnemy ...

function game.LastStandManaReserve(a, b) end
---@alias game-Scripts-CombatLogic.LastStandManaReserve ...

function game.OnlySourceOfInvulnerability(a) end
---@alias game-Scripts-CombatLogic.OnlySourceOfInvulnerability ...

function game.PlayerLastStandHeal(a, b, c, d) end
---@alias game-Scripts-CombatLogic.PlayerLastStandHeal ...

function game.ProcessHealthBuffer(a, b) end
---@alias game-Scripts-CombatLogic.ProcessHealthBuffer ...

function game.ProjectileSpawnUnitOnDeath(a, b) end
---@alias game-Scripts-CombatLogic.ProjectileSpawnUnitOnDeath ...

function game.QueueOnHitVoiceLines(a, b) end
---@alias game-Scripts-CombatLogic.QueueOnHitVoiceLines ...

function game.RecordBossKillerName(a, b, c) end
---@alias game-Scripts-CombatLogic.RecordBossKillerName ...

function game.RecordSpeedModifier(a, b) end
---@alias game-Scripts-CombatLogic.RecordSpeedModifier ...

function game.RemoveIncomingDamageModifier(a, b) end
---@alias game-Scripts-CombatLogic.RemoveIncomingDamageModifier ...

function game.RemoveLastStand(a, b) end
---@alias game-Scripts-CombatLogic.RemoveLastStand ...

function game.RemoveOnDamagedFunction(a, b) end
---@alias game-Scripts-CombatLogic.RemoveOnDamagedFunction ...

function game.RemoveOutgoingCritModifier(a, b) end
---@alias game-Scripts-CombatLogic.RemoveOutgoingCritModifier ...

function game.RemoveOutgoingDamageModifier(a, b) end
---@alias game-Scripts-CombatLogic.RemoveOutgoingDamageModifier ...

function game.RemoveOutgoingDoubleDamageModifier(a, b) end
---@alias game-Scripts-CombatLogic.RemoveOutgoingDoubleDamageModifier ...

function game.RemovePlayerAttackSpecialChargeSpeed(a) end
---@alias game-Scripts-CombatLogic.RemovePlayerAttackSpecialChargeSpeed ...

function game.RemovePlayerImmuneToForce(a) end
---@alias game-Scripts-CombatLogic.RemovePlayerImmuneToForce ...

function game.RespawnVictim(a, b, c, d) end
---@alias game-Scripts-CombatLogic.RespawnVictim ...

function game.RestoreLastStandManaReserve(a) end
---@alias game-Scripts-CombatLogic.RestoreLastStandManaReserve ...

function game.ScaleToHealthPercentage(a, b) end
---@alias game-Scripts-CombatLogic.ScaleToHealthPercentage ...

function game.SelfDestruct(a) end
---@alias game-Scripts-CombatLogic.SelfDestruct ...

function game.SetCastArmDisabled(a) end
---@alias game-Scripts-CombatLogic.SetCastArmDisabled ...

function game.SetCastArmEnabled(a) end
---@alias game-Scripts-CombatLogic.SetCastArmEnabled ...

function game.SetPlayerAttackSpecialChargeSpeed(a, b) end
---@alias game-Scripts-CombatLogic.SetPlayerAttackSpecialChargeSpeed ...

function game.SetPlayerDarkside(a) end
---@alias game-Scripts-CombatLogic.SetPlayerDarkside ...

function game.SetPlayerInterruptible(a) end
---@alias game-Scripts-CombatLogic.SetPlayerInterruptible ...

function game.SetPlayerInvulnerable(a) end
---@alias game-Scripts-CombatLogic.SetPlayerInvulnerable ...

function game.SetPlayerNotStopsProjectiles(a) end
---@alias game-Scripts-CombatLogic.SetPlayerNotStopsProjectiles ...

function game.SetPlayerPhasing(a) end
---@alias game-Scripts-CombatLogic.SetPlayerPhasing ...

function game.SetPlayerStopsProjectiles(a) end
---@alias game-Scripts-CombatLogic.SetPlayerStopsProjectiles ...

function game.SetPlayerUnDarkside(a) end
---@alias game-Scripts-CombatLogic.SetPlayerUnDarkside ...

function game.SetPlayerUninterruptible(a) end
---@alias game-Scripts-CombatLogic.SetPlayerUninterruptible ...

function game.SetPlayerUnphasing(a) end
---@alias game-Scripts-CombatLogic.SetPlayerUnphasing ...

function game.SetPlayerVulnerable(a) end
---@alias game-Scripts-CombatLogic.SetPlayerVulnerable ...

function game.SetUnitInvulnerable(a, b, c) end
---@alias game-Scripts-CombatLogic.SetUnitInvulnerable ...

function game.SetUnitVulnerable(a, b) end
---@alias game-Scripts-CombatLogic.SetUnitVulnerable ...

function game.SkellyDeath(a, b) end
---@alias game-Scripts-CombatLogic.SkellyDeath ...

function game.SlingshotRepulse(a, b) end
---@alias game-Scripts-CombatLogic.SlingshotRepulse ...

function game.SpawnImpactReactionObstacle(a, b) end
---@alias game-Scripts-CombatLogic.SpawnImpactReactionObstacle ...

function game.SpawnImpactReactionObstacles(a, b) end
---@alias game-Scripts-CombatLogic.SpawnImpactReactionObstacles ...

function game.SpawnObstacleOnProjectileDeath(a, b) end
---@alias game-Scripts-CombatLogic.SpawnObstacleOnProjectileDeath ...

function game.SpawnObstaclesOnDeath(a, b) end
---@alias game-Scripts-CombatLogic.SpawnObstaclesOnDeath ...

function game.SpreadBrushFire(a) end
---@alias game-Scripts-CombatLogic.SpreadBrushFire ...

function game.StartWeaponSlowMotion(a, b, c) end
---@alias game-Scripts-CombatLogic.StartWeaponSlowMotion ...

function game.UnitDeathCheckRoomExitsReady() end
---@alias game-Scripts-CombatLogic.UnitDeathCheckRoomExitsReady ...

function game.UpdatePlayerAttackSpecialChargeSpeed() end
---@alias game-Scripts-CombatLogic.UpdatePlayerAttackSpecialChargeSpeed ...

function game.VulnerableAfterDelay(a, b, c) end
---@alias game-Scripts-CombatLogic.VulnerableAfterDelay ...

function game.WipeSpawnsOnKill(a, b, c) end
---@alias game-Scripts-CombatLogic.WipeSpawnsOnKill ...

return game