---@meta game-Scripts-CombatPresentation
local game = {}

---@class game-Scripts-CombatPresentation*PolymorphPresentationData
---@field [any] any

---@type game-Scripts-CombatPresentation*PolymorphPresentationData
game.PolymorphPresentationData = ...
---@alias game-Scripts-CombatPresentation.PolymorphPresentationData ...

function game.ActivateFusePresentation(a) end
---@alias game-Scripts-CombatPresentation.ActivateFusePresentation ...

function game.AddSimSpeedChange(a, b) end
---@alias game-Scripts-CombatPresentation.AddSimSpeedChange ...

function game.AllyHitPresentation(a, b, c) end
---@alias game-Scripts-CombatPresentation.AllyHitPresentation ...

function game.AmmoPackPickup(a, b, c) end
---@alias game-Scripts-CombatPresentation.AmmoPackPickup ...

function game.ArmorBreakPresentation(a) end
---@alias game-Scripts-CombatPresentation.ArmorBreakPresentation ...

function game.ArmorBreakPresentationQueue(a) end
---@alias game-Scripts-CombatPresentation.ArmorBreakPresentationQueue ...

function game.ArmorDamagePresentation(a, b) end
---@alias game-Scripts-CombatPresentation.ArmorDamagePresentation ...

function game.BlockAttackPresentation(a, b, c) end
---@alias game-Scripts-CombatPresentation.BlockAttackPresentation ...

function game.BlockDeathCanceledPresentation(a) end
---@alias game-Scripts-CombatPresentation.BlockDeathCanceledPresentation ...

function game.BlockDeathLastStandPresentationEnd() end
---@alias game-Scripts-CombatPresentation.BlockDeathLastStandPresentationEnd ...

function game.BlockDeathLastStandPresentationStart(a) end
---@alias game-Scripts-CombatPresentation.BlockDeathLastStandPresentationStart ...

function game.BlockedDamageInvulnerablePresentation(a, b) end
---@alias game-Scripts-CombatPresentation.BlockedDamageInvulnerablePresentation ...

function game.BossChillKillPresentation(a) end
---@alias game-Scripts-CombatPresentation.BossChillKillPresentation ...

function game.BossDeathFlash(a) end
---@alias game-Scripts-CombatPresentation.BossDeathFlash ...

function game.BossResistChillKillPresentation(a) end
---@alias game-Scripts-CombatPresentation.BossResistChillKillPresentation ...

function game.CastArmedPresentation(a) end
---@alias game-Scripts-CombatPresentation.CastArmedPresentation ...

function game.CastEmbeddedPresentationEnd() end
---@alias game-Scripts-CombatPresentation.CastEmbeddedPresentationEnd ...

function game.CastEmbeddedPresentationStart() end
---@alias game-Scripts-CombatPresentation.CastEmbeddedPresentationStart ...

function game.ChronosTyphonFightHitPresentation(a, b) end
---@alias game-Scripts-CombatPresentation.ChronosTyphonFightHitPresentation ...

function game.ClearCastEmbededAnchors() end
---@alias game-Scripts-CombatPresentation.ClearCastEmbededAnchors ...

function game.ClearManaChargeIndicator(a, b) end
---@alias game-Scripts-CombatPresentation.ClearManaChargeIndicator ...

function game.ClearSimSpeedChanges() end
---@alias game-Scripts-CombatPresentation.ClearSimSpeedChanges ...

function game.CocoonHitPresentation(a) end
---@alias game-Scripts-CombatPresentation.CocoonHitPresentation ...

function game.CreateHealthBar(a) end
---@alias game-Scripts-CombatPresentation.CreateHealthBar ...

function game.CreateLevelDisplay(a, b) end
---@alias game-Scripts-CombatPresentation.CreateLevelDisplay ...

function game.CreateScorchHealthBar(a) end
---@alias game-Scripts-CombatPresentation.CreateScorchHealthBar ...

function game.DamagePresentation(a, b) end
---@alias game-Scripts-CombatPresentation.DamagePresentation ...

function game.DeferredCombatPresentation() end
---@alias game-Scripts-CombatPresentation.DeferredCombatPresentation ...

function game.DisplayDamageText(a, b) end
---@alias game-Scripts-CombatPresentation.DisplayDamageText ...

function game.DoCameraMotion(a) end
---@alias game-Scripts-CombatPresentation.DoCameraMotion ...

function game.DoHeroHitRumble(a) end
---@alias game-Scripts-CombatPresentation.DoHeroHitRumble ...

function game.DoImpactSound(a, b) end
---@alias game-Scripts-CombatPresentation.DoImpactSound ...

function game.DoReactionPresentation(a, b) end
---@alias game-Scripts-CombatPresentation.DoReactionPresentation ...

function game.DoRumble(a) end
---@alias game-Scripts-CombatPresentation.DoRumble ...

function game.DoubleStrikePresentation(a) end
---@alias game-Scripts-CombatPresentation.DoubleStrikePresentation ...

function game.DoUnitArmorShake(a, b) end
---@alias game-Scripts-CombatPresentation.DoUnitArmorShake ...

function game.DoUnitArmorSpark(a, b) end
---@alias game-Scripts-CombatPresentation.DoUnitArmorSpark ...

function game.DoUnitHitFlash(a, b) end
---@alias game-Scripts-CombatPresentation.DoUnitHitFlash ...

function game.DoUnitHitShake(a, b) end
---@alias game-Scripts-CombatPresentation.DoUnitHitShake ...

function game.DoWeaponCancelEffectSimulationSlow(a) end
---@alias game-Scripts-CombatPresentation.DoWeaponCancelEffectSimulationSlow ...

function game.DoWeaponChargeRumble(a) end
---@alias game-Scripts-CombatPresentation.DoWeaponChargeRumble ...

function game.DoWeaponFireRadialBlur(a) end
---@alias game-Scripts-CombatPresentation.DoWeaponFireRadialBlur ...

function game.DoWeaponFireSimulationSlow(a) end
---@alias game-Scripts-CombatPresentation.DoWeaponFireSimulationSlow ...

function game.DoWeaponHitRumble(a, b) end
---@alias game-Scripts-CombatPresentation.DoWeaponHitRumble ...

function game.DoWeaponHitSimulationSlow(a, b, c) end
---@alias game-Scripts-CombatPresentation.DoWeaponHitSimulationSlow ...

function game.DoWeaponHitSimulationSlowThread(a, b) end
---@alias game-Scripts-CombatPresentation.DoWeaponHitSimulationSlowThread ...

function game.DoWeaponRadialBlur(a) end
---@alias game-Scripts-CombatPresentation.DoWeaponRadialBlur ...

function game.DoWeaponScreenshake(a, b, c) end
---@alias game-Scripts-CombatPresentation.DoWeaponScreenshake ...

function game.DoWeaponScreenshakeThread(a) end
---@alias game-Scripts-CombatPresentation.DoWeaponScreenshakeThread ...

function game.DoWeaponSounds(a, b, c) end
---@alias game-Scripts-CombatPresentation.DoWeaponSounds ...

function game.EndLavaPresentation() end
---@alias game-Scripts-CombatPresentation.EndLavaPresentation ...

function game.EndPoisonPresentation() end
---@alias game-Scripts-CombatPresentation.EndPoisonPresentation ...

function game.EnemyDodgePresentation(a, b) end
---@alias game-Scripts-CombatPresentation.EnemyDodgePresentation ...

function game.EquipPlayerWeaponPresentation(a, b) end
---@alias game-Scripts-CombatPresentation.EquipPlayerWeaponPresentation ...

function game.ErisReloadJamPresentation(a, b, c, d) end
---@alias game-Scripts-CombatPresentation.ErisReloadJamPresentation ...

function game.ExecutePresentation(a, b) end
---@alias game-Scripts-CombatPresentation.ExecutePresentation ...

function game.FadeUnitActivation(a) end
---@alias game-Scripts-CombatPresentation.FadeUnitActivation ...

function game.FirstOnHitSound(a, b, c) end
---@alias game-Scripts-CombatPresentation.FirstOnHitSound ...

function game.GainLastStandPresentation(a) end
---@alias game-Scripts-CombatPresentation.GainLastStandPresentation ...

function game.GenericBossKillPresentation(a, b) end
---@alias game-Scripts-CombatPresentation.GenericBossKillPresentation ...

function game.GenericDamagePresentation(a, b) end
---@alias game-Scripts-CombatPresentation.GenericDamagePresentation ...

function game.GetDamagedFx(a, b, c) end
---@alias game-Scripts-CombatPresentation.GetDamagedFx ...

function game.GetDamageNumberTextScale(a) end
---@alias game-Scripts-CombatPresentation.GetDamageNumberTextScale ...

function game.GetHideChargeDuration(a) end
---@alias game-Scripts-CombatPresentation.GetHideChargeDuration ...

function game.GetNumBossHealthBars() end
---@alias game-Scripts-CombatPresentation.GetNumBossHealthBars ...

function game.GetPlayerDamageNumberTextScale(a) end
---@alias game-Scripts-CombatPresentation.GetPlayerDamageNumberTextScale ...

function game.HandleManaChargeIndicator(a) end
---@alias game-Scripts-CombatPresentation.HandleManaChargeIndicator ...

function game.HealthTickDecrementPresentation(a, b) end
---@alias game-Scripts-CombatPresentation.HealthTickDecrementPresentation ...

function game.HeraManaRestorePresentation(a, b) end
---@alias game-Scripts-CombatPresentation.HeraManaRestorePresentation ...

function game.HeroRootApplyPresentation(a) end
---@alias game-Scripts-CombatPresentation.HeroRootApplyPresentation ...

function game.HeroRootClearPresentation(a) end
---@alias game-Scripts-CombatPresentation.HeroRootClearPresentation ...

function game.HighHealthCombatTextPresentation(a, b) end
---@alias game-Scripts-CombatPresentation.HighHealthCombatTextPresentation ...

function game.HighRollHitPresentation() end
---@alias game-Scripts-CombatPresentation.HighRollHitPresentation ...

function game.HitBySmokeTrapWeaponPresentation(a) end
---@alias game-Scripts-CombatPresentation.HitBySmokeTrapWeaponPresentation ...

function game.HitInvulnerablePresentation(a, b, c) end
---@alias game-Scripts-CombatPresentation.HitInvulnerablePresentation ...

function game.HuntersMarkApplyPresentation(a) end
---@alias game-Scripts-CombatPresentation.HuntersMarkApplyPresentation ...

function game.HuntersMarkUnitDeathPresentation(a) end
---@alias game-Scripts-CombatPresentation.HuntersMarkUnitDeathPresentation ...

function game.InCombatText(a, b, c, d) end
---@alias game-Scripts-CombatPresentation.InCombatText ...

function game.InCombatTextArgs(a) end
---@alias game-Scripts-CombatPresentation.InCombatTextArgs ...

function game.InCombatTextEvent(a, b) end
---@alias game-Scripts-CombatPresentation.InCombatTextEvent ...

function game.IndestructibleObstacleHitPresentation(a, b) end
---@alias game-Scripts-CombatPresentation.IndestructibleObstacleHitPresentation ...

function game.InfiniteLastStandPresentationEnd() end
---@alias game-Scripts-CombatPresentation.InfiniteLastStandPresentationEnd ...

function game.InfiniteLastStandPresentationStart(a) end
---@alias game-Scripts-CombatPresentation.InfiniteLastStandPresentationStart ...

function game.InvulnerabilityFramePresentationEnd(a, b, c) end
---@alias game-Scripts-CombatPresentation.InvulnerabilityFramePresentationEnd ...

function game.InvulnerabilityFramePresentationStart(a, b, c) end
---@alias game-Scripts-CombatPresentation.InvulnerabilityFramePresentationStart ...

function game.IsCancelSimEffectAllowed(a, b) end
---@alias game-Scripts-CombatPresentation.IsCancelSimEffectAllowed ...

function game.KillPresentation(a, b, c) end
---@alias game-Scripts-CombatPresentation.KillPresentation ...

function game.KillVoiceLinesQueue(a, b, c) end
---@alias game-Scripts-CombatPresentation.KillVoiceLinesQueue ...

function game.LastKillPresentation(a) end
---@alias game-Scripts-CombatPresentation.LastKillPresentation ...

function game.LastKillVulnerable() end
---@alias game-Scripts-CombatPresentation.LastKillVulnerable ...

function game.LockCameraMotion(a) end
---@alias game-Scripts-CombatPresentation.LockCameraMotion ...

function game.LostLastStandPresentation() end
---@alias game-Scripts-CombatPresentation.LostLastStandPresentation ...

function game.LowHealthCombatTextPresentation(a, b) end
---@alias game-Scripts-CombatPresentation.LowHealthCombatTextPresentation ...

function game.OnInvisStartPresentation(a) end
---@alias game-Scripts-CombatPresentation.OnInvisStartPresentation ...

function game.ParryAttackPresentation(a) end
---@alias game-Scripts-CombatPresentation.ParryAttackPresentation ...

function game.PerfectClearObjectiveFailedPresentation(a) end
---@alias game-Scripts-CombatPresentation.PerfectClearObjectiveFailedPresentation ...

function game.PlayerBlockDeathProcText(a) end
---@alias game-Scripts-CombatPresentation.PlayerBlockDeathProcText ...

function game.PlayerBlockDeathVoicelines(a) end
---@alias game-Scripts-CombatPresentation.PlayerBlockDeathVoicelines ...

function game.PlayerDodgePresentation() end
---@alias game-Scripts-CombatPresentation.PlayerDodgePresentation ...

function game.PlayerInfiniteLastStandSFX() end
---@alias game-Scripts-CombatPresentation.PlayerInfiniteLastStandSFX ...

function game.PlayerInfiniteLastStandVoicelines(a) end
---@alias game-Scripts-CombatPresentation.PlayerInfiniteLastStandVoicelines ...

function game.PlayerLastStandHealingPresentation() end
---@alias game-Scripts-CombatPresentation.PlayerLastStandHealingPresentation ...

function game.PlayerLastStandHealingText(a) end
---@alias game-Scripts-CombatPresentation.PlayerLastStandHealingText ...

function game.PlayerLastStandManaGainText(a) end
---@alias game-Scripts-CombatPresentation.PlayerLastStandManaGainText ...

function game.PlayerLastStandPresentationEnd() end
---@alias game-Scripts-CombatPresentation.PlayerLastStandPresentationEnd ...

function game.PlayerLastStandPresentationStart(a) end
---@alias game-Scripts-CombatPresentation.PlayerLastStandPresentationStart ...

function game.PlayerLastStandProcText(a) end
---@alias game-Scripts-CombatPresentation.PlayerLastStandProcText ...

function game.PlayerLastStandSFX() end
---@alias game-Scripts-CombatPresentation.PlayerLastStandSFX ...

function game.PlayerLastStandVoicelines(a) end
---@alias game-Scripts-CombatPresentation.PlayerLastStandVoicelines ...

function game.PlayerMissPresentation() end
---@alias game-Scripts-CombatPresentation.PlayerMissPresentation ...

function game.PolymorphApplyPresentation(a, b) end
---@alias game-Scripts-CombatPresentation.PolymorphApplyPresentation ...

function game.PolymorphClearPresentation(a, b) end
---@alias game-Scripts-CombatPresentation.PolymorphClearPresentation ...

function game.PolymorphSimSlow() end
---@alias game-Scripts-CombatPresentation.PolymorphSimSlow ...

function game.PostActivatFusePresentation(a) end
---@alias game-Scripts-CombatPresentation.PostActivatFusePresentation ...

function game.PostEnemyKillPresentation(a, b) end
---@alias game-Scripts-CombatPresentation.PostEnemyKillPresentation ...

function game.PostFuseRevivePresentation(a) end
---@alias game-Scripts-CombatPresentation.PostFuseRevivePresentation ...

function game.PreSpawnFx(a) end
---@alias game-Scripts-CombatPresentation.PreSpawnFx ...

function game.PulseCombatText(a) end
---@alias game-Scripts-CombatPresentation.PulseCombatText ...

function game.RecreateEffectVfx(a) end
---@alias game-Scripts-CombatPresentation.RecreateEffectVfx ...

function game.RecreateEnemyUI(a) end
---@alias game-Scripts-CombatPresentation.RecreateEnemyUI ...

function game.RemoveEnemyHealthBar(a) end
---@alias game-Scripts-CombatPresentation.RemoveEnemyHealthBar ...

function game.RemoveEnemyUI(a) end
---@alias game-Scripts-CombatPresentation.RemoveEnemyUI ...

function game.RemoveHitShieldPresentation(a) end
---@alias game-Scripts-CombatPresentation.RemoveHitShieldPresentation ...

function game.RemoveSimSpeedChange(a, b) end
---@alias game-Scripts-CombatPresentation.RemoveSimSpeedChange ...

function game.ScreamerDistortionEffect(a, b, c) end
---@alias game-Scripts-CombatPresentation.ScreamerDistortionEffect ...

function game.SpawnKillPresentation(a) end
---@alias game-Scripts-CombatPresentation.SpawnKillPresentation ...

function game.SpecialHitPresentation(a, b) end
---@alias game-Scripts-CombatPresentation.SpecialHitPresentation ...

function game.SpellChargeEndTimeSlowPresentation() end
---@alias game-Scripts-CombatPresentation.SpellChargeEndTimeSlowPresentation ...

function game.SpellChargeTimeSlowPresentation() end
---@alias game-Scripts-CombatPresentation.SpellChargeTimeSlowPresentation ...

function game.SpellChargeTimeSlowPresentationSoftVignette() end
---@alias game-Scripts-CombatPresentation.SpellChargeTimeSlowPresentationSoftVignette ...

function game.SprintPhasingMelPresentation(a, b) end
---@alias game-Scripts-CombatPresentation.SprintPhasingMelPresentation ...

function game.SprintPhasingUnitPresentation(a, b) end
---@alias game-Scripts-CombatPresentation.SprintPhasingUnitPresentation ...

function game.StartBlockDeathPresentation(a) end
---@alias game-Scripts-CombatPresentation.StartBlockDeathPresentation ...

function game.StartOrRefreshLavaPresentation() end
---@alias game-Scripts-CombatPresentation.StartOrRefreshLavaPresentation ...

function game.StartPoisonPresentation(a) end
---@alias game-Scripts-CombatPresentation.StartPoisonPresentation ...

function game.StartWavePresentation(a, b) end
---@alias game-Scripts-CombatPresentation.StartWavePresentation ...

function game.StopWeaponSounds(a, b, c) end
---@alias game-Scripts-CombatPresentation.StopWeaponSounds ...

function game.TickBlockDeathPresentation(a, b) end
---@alias game-Scripts-CombatPresentation.TickBlockDeathPresentation ...

function game.TintUnitActivation(a) end
---@alias game-Scripts-CombatPresentation.TintUnitActivation ...

function game.TyphonHeadPostCombatReload(a, b) end
---@alias game-Scripts-CombatPresentation.TyphonHeadPostCombatReload ...

function game.UnblockableAttackPresentation(a) end
---@alias game-Scripts-CombatPresentation.UnblockableAttackPresentation ...

function game.UnitActivatePresentation(a, b) end
---@alias game-Scripts-CombatPresentation.UnitActivatePresentation ...

function game.UnitInvulnerableHitPresentation(a, b) end
---@alias game-Scripts-CombatPresentation.UnitInvulnerableHitPresentation ...

function game.UnlockCameraMotion(a) end
---@alias game-Scripts-CombatPresentation.UnlockCameraMotion ...

function game.UnusedWeaponBonusPresentation() end
---@alias game-Scripts-CombatPresentation.UnusedWeaponBonusPresentation ...

function game.UpdateBossHealthBarFalloff(a) end
---@alias game-Scripts-CombatPresentation.UpdateBossHealthBarFalloff ...

function game.UpdatedBossHealthBarRecord(a, b, c) end
---@alias game-Scripts-CombatPresentation.UpdatedBossHealthBarRecord ...

function game.UpdateEnemyHealthBarFalloff(a, b) end
---@alias game-Scripts-CombatPresentation.UpdateEnemyHealthBarFalloff ...

function game.UpdateGroupHealthBarFalloff(a) end
---@alias game-Scripts-CombatPresentation.UpdateGroupHealthBarFalloff ...

function game.UpdateGroupHealthBarReal(a) end
---@alias game-Scripts-CombatPresentation.UpdateGroupHealthBarReal ...

function game.UpdateHealthBar(a, b, c) end
---@alias game-Scripts-CombatPresentation.UpdateHealthBar ...

function game.UpdateHealthBarIcons(a) end
---@alias game-Scripts-CombatPresentation.UpdateHealthBarIcons ...

function game.UpdateHealthBarReal(a) end
---@alias game-Scripts-CombatPresentation.UpdateHealthBarReal ...

function game.UpdateSimulationSpeed(a, b) end
---@alias game-Scripts-CombatPresentation.UpdateSimulationSpeed ...

function game.UseLastStandDropPresentation(a) end
---@alias game-Scripts-CombatPresentation.UseLastStandDropPresentation ...

function game.VictimDeathHold(a, b, c) end
---@alias game-Scripts-CombatPresentation.VictimDeathHold ...

function game.WebSlowedPresentation(a) end
---@alias game-Scripts-CombatPresentation.WebSlowedPresentation ...

function game.ZagreusBossDreamRunIntro(a, b) end
---@alias game-Scripts-CombatPresentation.ZagreusBossDreamRunIntro ...

function game.ZagreusKillPresentation(a, b) end
---@alias game-Scripts-CombatPresentation.ZagreusKillPresentation ...

return game