---@meta game-Scripts-CosmeticsLogic
local game = {}

function game.ActivateConditionalItem(a, b) end
---@alias game-Scripts-CosmeticsLogic.ActivateConditionalItem ...

function game.ActivateConditionalItems(a, b) end
---@alias game-Scripts-CosmeticsLogic.ActivateConditionalItems ...

function game.AnyCosmeticActiveInFamily(a) end
---@alias game-Scripts-CosmeticsLogic.AnyCosmeticActiveInFamily ...

function game.CloseCosmeticsShopScreen(a, b, c) end
---@alias game-Scripts-CosmeticsLogic.CloseCosmeticsShopScreen ...

function game.CosmeticShopAllowViewItem(a, b, c) end
---@alias game-Scripts-CosmeticsLogic.CosmeticShopAllowViewItem ...

function game.CosmeticShopDisplayCategory(a, b) end
---@alias game-Scripts-CosmeticsLogic.CosmeticShopDisplayCategory ...

function game.CosmeticShopScrollDown(a, b) end
---@alias game-Scripts-CosmeticsLogic.CosmeticShopScrollDown ...

function game.CosmeticShopScrollUp(a, b) end
---@alias game-Scripts-CosmeticsLogic.CosmeticShopScrollUp ...

function game.CosmeticShopUpdateVisibility(a, b) end
---@alias game-Scripts-CosmeticsLogic.CosmeticShopUpdateVisibility ...

function game.DeactivateConditionalItem(a, b) end
---@alias game-Scripts-CosmeticsLogic.DeactivateConditionalItem ...

function game.DoCosmeticShopPurchase(a, b, c) end
---@alias game-Scripts-CosmeticsLogic.DoCosmeticShopPurchase ...

function game.DoCosmeticShopRemoval(a, b) end
---@alias game-Scripts-CosmeticsLogic.DoCosmeticShopRemoval ...

function game.HandleCosmeticShopPurchase(a, b, c) end
---@alias game-Scripts-CosmeticsLogic.HandleCosmeticShopPurchase ...

function game.HandleCosmeticShopReAdd(a, b) end
---@alias game-Scripts-CosmeticsLogic.HandleCosmeticShopReAdd ...

function game.HandleCosmeticShopRemoval(a, b) end
---@alias game-Scripts-CosmeticsLogic.HandleCosmeticShopRemoval ...

function game.HasNewCosmeticsAvailable(a, b) end
---@alias game-Scripts-CosmeticsLogic.HasNewCosmeticsAvailable ...

function game.OpenCosmeticsShopScreen(a, b) end
---@alias game-Scripts-CosmeticsLogic.OpenCosmeticsShopScreen ...

function game.UseCosmeticsShop(a, b) end
---@alias game-Scripts-CosmeticsLogic.UseCosmeticsShop ...

return game