---@meta game-Scripts-DeathLoopLogic
local game = {}

function game.ActivateAmbientCritters(a, b) end
---@alias game-Scripts-DeathLoopLogic.ActivateAmbientCritters ...

function game.ClearMapBlockers(a, b) end
---@alias game-Scripts-DeathLoopLogic.ClearMapBlockers ...

function game.DeathAreaRoomTransition(a, b) end
---@alias game-Scripts-DeathLoopLogic.DeathAreaRoomTransition ...

function game.DeathAreaSwitchRoom(a, b) end
---@alias game-Scripts-DeathLoopLogic.DeathAreaSwitchRoom ...

function game.EasyModeIsAtCap() end
---@alias game-Scripts-DeathLoopLogic.EasyModeIsAtCap ...

function game.GamePhaseTick(a) end
---@alias game-Scripts-DeathLoopLogic.GamePhaseTick ...

function game.GetRunsUntilNextGamePhase() end
---@alias game-Scripts-DeathLoopLogic.GetRunsUntilNextGamePhase ...

function game.HideAmbientCritters(a, b) end
---@alias game-Scripts-DeathLoopLogic.HideAmbientCritters ...

function game.HubPostBountyLoad(a, b) end
---@alias game-Scripts-DeathLoopLogic.HubPostBountyLoad ...

function game.HubPostDreamLoad(a, b) end
---@alias game-Scripts-DeathLoopLogic.HubPostDreamLoad ...

function game.KillHero(a, b) end
---@alias game-Scripts-DeathLoopLogic.KillHero ...

function game.NPCFollowPath(a, b) end
---@alias game-Scripts-DeathLoopLogic.NPCFollowPath ...

function game.NPCLittering(a, b) end
---@alias game-Scripts-DeathLoopLogic.NPCLittering ...

function game.RequestPreRunLoadoutChangeSave() end
---@alias game-Scripts-DeathLoopLogic.RequestPreRunLoadoutChangeSave ...

function game.RestoreLitter(a, b) end
---@alias game-Scripts-DeathLoopLogic.RestoreLitter ...

function game.SetupCamera(a, b) end
---@alias game-Scripts-DeathLoopLogic.SetupCamera ...

function game.SetupDynamicLitter(a, b) end
---@alias game-Scripts-DeathLoopLogic.SetupDynamicLitter ...

function game.ShouldIncrementEasyMode() end
---@alias game-Scripts-DeathLoopLogic.ShouldIncrementEasyMode ...

function game.SpawnSkelly(a) end
---@alias game-Scripts-DeathLoopLogic.SpawnSkelly ...

function game.StartDeathLoop(a, b) end
---@alias game-Scripts-DeathLoopLogic.StartDeathLoop ...

function game.StartOver(a) end
---@alias game-Scripts-DeathLoopLogic.StartOver ...

function game.UnlockDeathAreaInteractables() end
---@alias game-Scripts-DeathLoopLogic.UnlockDeathAreaInteractables ...

function game.UpdateAffordabilityStatus() end
---@alias game-Scripts-DeathLoopLogic.UpdateAffordabilityStatus ...

function game.UseDreamRunDoor(a, b) end
---@alias game-Scripts-DeathLoopLogic.UseDreamRunDoor ...

function game.UseEscapeDoor(a, b) end
---@alias game-Scripts-DeathLoopLogic.UseEscapeDoor ...

function game.UseTrashPoint(a, b, c) end
---@alias game-Scripts-DeathLoopLogic.UseTrashPoint ...

return game