---@meta game-Scripts-Debug
local game = {}

function game.AnimateOnDistance(a, b) end
---@alias game-Scripts-Debug.AnimateOnDistance ...

function game.AnimateOutsideDistance(a, b) end
---@alias game-Scripts-Debug.AnimateOutsideDistance ...

function game.AnimTest1(a, b, c) end
---@alias game-Scripts-Debug.AnimTest1 ...

function game.AnimTest2(a, b, c) end
---@alias game-Scripts-Debug.AnimTest2 ...

function game.AnimTest3(a, b, c) end
---@alias game-Scripts-Debug.AnimTest3 ...

function game.AutoPlayOff() end
---@alias game-Scripts-Debug.AutoPlayOff ...

function game.AutoPlayOn() end
---@alias game-Scripts-Debug.AutoPlayOn ...

function game.CreateDebugEnemySpawnPage(a, b) end
---@alias game-Scripts-Debug.CreateDebugEnemySpawnPage ...

function game.CreateDevSaveName(a, b) end
---@alias game-Scripts-Debug.CreateDevSaveName ...

function game.CreateNPCSpawnButtons(a, b) end
---@alias game-Scripts-Debug.CreateNPCSpawnButtons ...

function game.DebugAddRerollsAndTalentPoints() end
---@alias game-Scripts-Debug.DebugAddRerollsAndTalentPoints ...

function game.DebugConversationMouseOff(a) end
---@alias game-Scripts-Debug.DebugConversationMouseOff ...

function game.DebugConversationMouseOver(a) end
---@alias game-Scripts-Debug.DebugConversationMouseOver ...

function game.DebugConversationsClose(a, b) end
---@alias game-Scripts-Debug.DebugConversationsClose ...

function game.DebugConversationsEnemyButton(a, b) end
---@alias game-Scripts-Debug.DebugConversationsEnemyButton ...

function game.DebugConversationsPageLeft(a, b) end
---@alias game-Scripts-Debug.DebugConversationsPageLeft ...

function game.DebugConversationsPageRight(a, b) end
---@alias game-Scripts-Debug.DebugConversationsPageRight ...

function game.DebugConversationsTextLinesButton(a, b) end
---@alias game-Scripts-Debug.DebugConversationsTextLinesButton ...

function game.DebugConversationsUpdateVisibility(a, b) end
---@alias game-Scripts-Debug.DebugConversationsUpdateVisibility ...

function game.DebugEnemySpawnButton(a, b) end
---@alias game-Scripts-Debug.DebugEnemySpawnButton ...

function game.DebugEnemySpawnPageButton(a, b) end
---@alias game-Scripts-Debug.DebugEnemySpawnPageButton ...

function game.DebugEnemySpawnScreenClose(a, b) end
---@alias game-Scripts-Debug.DebugEnemySpawnScreenClose ...

function game.DebugNPCSpawn(a, b, c) end
---@alias game-Scripts-Debug.DebugNPCSpawn ...

function game.DebugPrintTable(a, b, c) end
---@alias game-Scripts-Debug.DebugPrintTable ...

function game.DebugSpawnConsumables(a, b) end
---@alias game-Scripts-Debug.DebugSpawnConsumables ...

function game.DebugSpawnEnemy(a, b) end
---@alias game-Scripts-Debug.DebugSpawnEnemy ...

function game.DebugSpawnMoney() end
---@alias game-Scripts-Debug.DebugSpawnMoney ...

function game.DebugUnlockMetaUpgrades(a, b) end
---@alias game-Scripts-Debug.DebugUnlockMetaUpgrades ...

function game.EditingModeOff() end
---@alias game-Scripts-Debug.EditingModeOff ...

function game.EditingModeOn() end
---@alias game-Scripts-Debug.EditingModeOn ...

function game.EditorActivateAllHarvestPoints() end
---@alias game-Scripts-Debug.EditorActivateAllHarvestPoints ...

function game.EquipTestWeapon(a, b, c) end
---@alias game-Scripts-Debug.EquipTestWeapon ...

function game.LiveFillInShopOptions() end
---@alias game-Scripts-Debug.LiveFillInShopOptions ...

function game.OnHotLoadLua(a) end
---@alias game-Scripts-Debug.OnHotLoadLua ...

function game.OnHotLoadXML() end
---@alias game-Scripts-Debug.OnHotLoadXML ...

function game.OpenDebugConversationScreen() end
---@alias game-Scripts-Debug.OpenDebugConversationScreen ...

function game.OpenDebugEnemySpawnScreen() end
---@alias game-Scripts-Debug.OpenDebugEnemySpawnScreen ...

function game.PostHotloadXML() end
---@alias game-Scripts-Debug.PostHotloadXML ...

function game.PreEditingModeOn() end
---@alias game-Scripts-Debug.PreEditingModeOn ...

function game.ReloadAllTraits() end
---@alias game-Scripts-Debug.ReloadAllTraits ...

function game.SafeModeOff() end
---@alias game-Scripts-Debug.SafeModeOff ...

function game.SafeModeOn() end
---@alias game-Scripts-Debug.SafeModeOn ...

function game.SetupDebugConversationsTextLinesButton(a, b, c, d, e) end
---@alias game-Scripts-Debug.SetupDebugConversationsTextLinesButton ...

function game.SetupTestWeaponKit(a, b) end
---@alias game-Scripts-Debug.SetupTestWeaponKit ...

function game.ToggleConfigOption(a) end
---@alias game-Scripts-Debug.ToggleConfigOption ...

function game.ToggleDebugEnemySpawnAtHero(a, b) end
---@alias game-Scripts-Debug.ToggleDebugEnemySpawnAtHero ...

function game.ToggleDebugEnemySpawnIdle(a, b) end
---@alias game-Scripts-Debug.ToggleDebugEnemySpawnIdle ...

function game.ToggleDebugEnemySpawnWithAttribute(a, b) end
---@alias game-Scripts-Debug.ToggleDebugEnemySpawnWithAttribute ...

function game.UnlockAllWeapons(a, b) end
---@alias game-Scripts-Debug.UnlockAllWeapons ...

function game.UnlockElementalIcons() end
---@alias game-Scripts-Debug.UnlockElementalIcons ...

function game.UnlockEntireCodex() end
---@alias game-Scripts-Debug.UnlockEntireCodex ...

return game