---@meta game-Scripts-EffectLogic
local game = {}

---@class game-Scripts-EffectLogic*CastLockWeapons

---@type game-Scripts-EffectLogic*CastLockWeapons
game.CastLockWeapons = ...
---@alias game-Scripts-EffectLogic.CastLockWeapons ...

function game.AddBlinkLockLayer(a) end
---@alias game-Scripts-EffectLogic.AddBlinkLockLayer ...

function game.AddCastLockLayer(a) end
---@alias game-Scripts-EffectLogic.AddCastLockLayer ...

function game.AddLobWeaponLockLayer(a) end
---@alias game-Scripts-EffectLogic.AddLobWeaponLockLayer ...

function game.AddSpecialLockLayer(a, b) end
---@alias game-Scripts-EffectLogic.AddSpecialLockLayer ...

function game.AddSuitWeaponLockLayer(a) end
---@alias game-Scripts-EffectLogic.AddSuitWeaponLockLayer ...

function game.AresStatusApply(a) end
---@alias game-Scripts-EffectLogic.AresStatusApply ...

function game.AxeSpecialBlockSelfTriggerLockApply(a) end
---@alias game-Scripts-EffectLogic.AxeSpecialBlockSelfTriggerLockApply ...

function game.AxeSpecialBlockSelfTriggerLockClear(a) end
---@alias game-Scripts-EffectLogic.AxeSpecialBlockSelfTriggerLockClear ...

function game.BlinkAndCastTriggerLockApply(a) end
---@alias game-Scripts-EffectLogic.BlinkAndCastTriggerLockApply ...

function game.BlinkAndCastTriggerLockClear(a) end
---@alias game-Scripts-EffectLogic.BlinkAndCastTriggerLockClear ...

function game.BlinkAndSpecialTriggerLockApply(a) end
---@alias game-Scripts-EffectLogic.BlinkAndSpecialTriggerLockApply ...

function game.BlinkAndSpecialTriggerLockClear(a) end
---@alias game-Scripts-EffectLogic.BlinkAndSpecialTriggerLockClear ...

function game.BlinkTriggerLockApply(a) end
---@alias game-Scripts-EffectLogic.BlinkTriggerLockApply ...

function game.BlinkTriggerLockClear(a) end
---@alias game-Scripts-EffectLogic.BlinkTriggerLockClear ...

function game.BurnEffectApply(a) end
---@alias game-Scripts-EffectLogic.BurnEffectApply ...

function game.BurnEffectClear(a) end
---@alias game-Scripts-EffectLogic.BurnEffectClear ...

function game.CastGripEffectApply(a) end
---@alias game-Scripts-EffectLogic.CastGripEffectApply ...

function game.CastGripEffectClear(a) end
---@alias game-Scripts-EffectLogic.CastGripEffectClear ...

function game.CharmApply(a) end
---@alias game-Scripts-EffectLogic.CharmApply ...

function game.CharmClear(a) end
---@alias game-Scripts-EffectLogic.CharmClear ...

function game.CheckInvulnerableFalloff(a) end
---@alias game-Scripts-EffectLogic.CheckInvulnerableFalloff ...

function game.CheckOmegaBlitzTrigger(a, b, c) end
---@alias game-Scripts-EffectLogic.CheckOmegaBlitzTrigger ...

function game.CheckOverheatConsecutiveDamage(a, b, c) end
---@alias game-Scripts-EffectLogic.CheckOverheatConsecutiveDamage ...

function game.CheckPoseidonFont(a, b) end
---@alias game-Scripts-EffectLogic.CheckPoseidonFont ...

function game.CheckSafeZoneRecharge() end
---@alias game-Scripts-EffectLogic.CheckSafeZoneRecharge ...

function game.CheckSprintBlitz(a, b, c) end
---@alias game-Scripts-EffectLogic.CheckSprintBlitz ...

function game.CheckStunAnimation(a) end
---@alias game-Scripts-EffectLogic.CheckStunAnimation ...

function game.CheckTriggerAllDamageEcho(a) end
---@alias game-Scripts-EffectLogic.CheckTriggerAllDamageEcho ...

function game.ChronosPolymorphApply(a) end
---@alias game-Scripts-EffectLogic.ChronosPolymorphApply ...

function game.ChronosPolymorphClear(a) end
---@alias game-Scripts-EffectLogic.ChronosPolymorphClear ...

function game.ClearCastApply(a) end
---@alias game-Scripts-EffectLogic.ClearCastApply ...

function game.ClearCastClear(a) end
---@alias game-Scripts-EffectLogic.ClearCastClear ...

function game.ClearSuitAttackShield(a) end
---@alias game-Scripts-EffectLogic.ClearSuitAttackShield ...

function game.DaggerSpecialTriggerLockApply(a) end
---@alias game-Scripts-EffectLogic.DaggerSpecialTriggerLockApply ...

function game.DaggerSpecialTriggerLockClear(a) end
---@alias game-Scripts-EffectLogic.DaggerSpecialTriggerLockClear ...

function game.DamageEchoApply(a) end
---@alias game-Scripts-EffectLogic.DamageEchoApply ...

function game.DamageEchoClear(a) end
---@alias game-Scripts-EffectLogic.DamageEchoClear ...

function game.DamageEchoProcess(a, b) end
---@alias game-Scripts-EffectLogic.DamageEchoProcess ...

function game.DamageEchoTrigger(a, b, c, d, e) end
---@alias game-Scripts-EffectLogic.DamageEchoTrigger ...

function game.DamageOverTimeApply(a) end
---@alias game-Scripts-EffectLogic.DamageOverTimeApply ...

function game.DamageShareApply(a) end
---@alias game-Scripts-EffectLogic.DamageShareApply ...

function game.DamageShareClear(a) end
---@alias game-Scripts-EffectLogic.DamageShareClear ...

function game.DelayedKnockbackEffectApply(a) end
---@alias game-Scripts-EffectLogic.DelayedKnockbackEffectApply ...

function game.EffectUninterruptibleApply(a) end
---@alias game-Scripts-EffectLogic.EffectUninterruptibleApply ...

function game.EffectUninterruptibleClear(a) end
---@alias game-Scripts-EffectLogic.EffectUninterruptibleClear ...

function game.EncounterInvulnerableFalloffWarning(a, b) end
---@alias game-Scripts-EffectLogic.EncounterInvulnerableFalloffWarning ...

function game.FrenzyApply(a) end
---@alias game-Scripts-EffectLogic.FrenzyApply ...

function game.FrenzyClear(a) end
---@alias game-Scripts-EffectLogic.FrenzyClear ...

function game.GetExistingAnimationPriority(a, b) end
---@alias game-Scripts-EffectLogic.GetExistingAnimationPriority ...

function game.HandleBurnStacks(a, b) end
---@alias game-Scripts-EffectLogic.HandleBurnStacks ...

function game.HandleBurnTicks(a) end
---@alias game-Scripts-EffectLogic.HandleBurnTicks ...

function game.HandleSpecialTriggerLockClear(a, b) end
---@alias game-Scripts-EffectLogic.HandleSpecialTriggerLockClear ...

function game.HecateDarkSideApply(a, b) end
---@alias game-Scripts-EffectLogic.HecateDarkSideApply ...

function game.HecateDarkSideClear(a, b) end
---@alias game-Scripts-EffectLogic.HecateDarkSideClear ...

function game.HecatePolymorphApply(a) end
---@alias game-Scripts-EffectLogic.HecatePolymorphApply ...

function game.HecatePolymorphClear(a) end
---@alias game-Scripts-EffectLogic.HecatePolymorphClear ...

function game.HecatePolymorphEquipWeapons(a) end
---@alias game-Scripts-EffectLogic.HecatePolymorphEquipWeapons ...

function game.HecatePolymorphUnequipWeapons(a) end
---@alias game-Scripts-EffectLogic.HecatePolymorphUnequipWeapons ...

function game.LobDisableTriggerLockApply(a) end
---@alias game-Scripts-EffectLogic.LobDisableTriggerLockApply ...

function game.LobDisableTriggerLockClear(a) end
---@alias game-Scripts-EffectLogic.LobDisableTriggerLockClear ...

function game.LobShortInvulnerableApply(a) end
---@alias game-Scripts-EffectLogic.LobShortInvulnerableApply ...

function game.LobShortInvulnerableClear(a) end
---@alias game-Scripts-EffectLogic.LobShortInvulnerableClear ...

function game.MatiHypnosisApply(a) end
---@alias game-Scripts-EffectLogic.MatiHypnosisApply ...

function game.MatiHypnosisClear(a) end
---@alias game-Scripts-EffectLogic.MatiHypnosisClear ...

function game.MiasmaSlowApply(a) end
---@alias game-Scripts-EffectLogic.MiasmaSlowApply ...

function game.MiasmaSlowClear(a) end
---@alias game-Scripts-EffectLogic.MiasmaSlowClear ...

function game.MoonBeamVulnerabilityApply(a) end
---@alias game-Scripts-EffectLogic.MoonBeamVulnerabilityApply ...

function game.MoonBeamVulnerabilityClear(a) end
---@alias game-Scripts-EffectLogic.MoonBeamVulnerabilityClear ...

function game.OmegaBuffApply(a) end
---@alias game-Scripts-EffectLogic.OmegaBuffApply ...

function game.OmegaBuffClear(a) end
---@alias game-Scripts-EffectLogic.OmegaBuffClear ...

function game.OverheatApply(a) end
---@alias game-Scripts-EffectLogic.OverheatApply ...

function game.OverheatClear(a) end
---@alias game-Scripts-EffectLogic.OverheatClear ...

function game.OverheatConsecutiveFalloff(a, b) end
---@alias game-Scripts-EffectLogic.OverheatConsecutiveFalloff ...

function game.PlayerSprintPhasingApply(a) end
---@alias game-Scripts-EffectLogic.PlayerSprintPhasingApply ...

function game.PlayerSprintPhasingClear(a) end
---@alias game-Scripts-EffectLogic.PlayerSprintPhasingClear ...

function game.PolyphemusPlayerGrabApply(a) end
---@alias game-Scripts-EffectLogic.PolyphemusPlayerGrabApply ...

function game.PolyphemusPlayerGrabClear(a) end
---@alias game-Scripts-EffectLogic.PolyphemusPlayerGrabClear ...

function game.PotionBuffApply(a) end
---@alias game-Scripts-EffectLogic.PotionBuffApply ...

function game.PotionBuffClear(a) end
---@alias game-Scripts-EffectLogic.PotionBuffClear ...

function game.ProcessDamageShare(a, b) end
---@alias game-Scripts-EffectLogic.ProcessDamageShare ...

function game.PulseUnitColor(a, b) end
---@alias game-Scripts-EffectLogic.PulseUnitColor ...

function game.RecordSafeZoneFired(a, b, c) end
---@alias game-Scripts-EffectLogic.RecordSafeZoneFired ...

function game.RemoveBlinkLockLayer(a) end
---@alias game-Scripts-EffectLogic.RemoveBlinkLockLayer ...

function game.RemoveCastLockLayer(a) end
---@alias game-Scripts-EffectLogic.RemoveCastLockLayer ...

function game.RemoveEffectBlockOnDelay(a, b, c) end
---@alias game-Scripts-EffectLogic.RemoveEffectBlockOnDelay ...

function game.RemoveEffectOnDelay(a, b, c) end
---@alias game-Scripts-EffectLogic.RemoveEffectOnDelay ...

function game.RemoveLobWeaponLockLayer(a) end
---@alias game-Scripts-EffectLogic.RemoveLobWeaponLockLayer ...

function game.RemoveSpecialLockLayer(a, b) end
---@alias game-Scripts-EffectLogic.RemoveSpecialLockLayer ...

function game.RemoveSuitWeaponLockLayer(a) end
---@alias game-Scripts-EffectLogic.RemoveSuitWeaponLockLayer ...

function game.RootedApply(a) end
---@alias game-Scripts-EffectLogic.RootedApply ...

function game.RootedClear(a) end
---@alias game-Scripts-EffectLogic.RootedClear ...

function game.ShivaAttackBoostApply(a) end
---@alias game-Scripts-EffectLogic.ShivaAttackBoostApply ...

function game.ShivaAttackBoostClear(a) end
---@alias game-Scripts-EffectLogic.ShivaAttackBoostClear ...

function game.StaffSelfBuffApply(a) end
---@alias game-Scripts-EffectLogic.StaffSelfBuffApply ...

function game.StaffSelfBuffClear(a) end
---@alias game-Scripts-EffectLogic.StaffSelfBuffClear ...

function game.StaffSpecialTriggerLockApply(a) end
---@alias game-Scripts-EffectLogic.StaffSpecialTriggerLockApply ...

function game.StaffSpecialTriggerLockClear(a) end
---@alias game-Scripts-EffectLogic.StaffSpecialTriggerLockClear ...

function game.SuitDashAttackLockApply(a) end
---@alias game-Scripts-EffectLogic.SuitDashAttackLockApply ...

function game.SuitDisableTriggerLockApply(a) end
---@alias game-Scripts-EffectLogic.SuitDisableTriggerLockApply ...

function game.SuitDisableTriggerLockClear(a) end
---@alias game-Scripts-EffectLogic.SuitDisableTriggerLockClear ...

function game.TorchSpecialTriggerLockApply(a) end
---@alias game-Scripts-EffectLogic.TorchSpecialTriggerLockApply ...

function game.TorchSpecialTriggerLockClear(a) end
---@alias game-Scripts-EffectLogic.TorchSpecialTriggerLockClear ...

function game.TyphonBlindEffectApply(a) end
---@alias game-Scripts-EffectLogic.TyphonBlindEffectApply ...

function game.TyphonBlindEffectClear(a) end
---@alias game-Scripts-EffectLogic.TyphonBlindEffectClear ...

function game.TyphonWeakEffectApply(a) end
---@alias game-Scripts-EffectLogic.TyphonWeakEffectApply ...

function game.TyphonWeakEffectClear(a) end
---@alias game-Scripts-EffectLogic.TyphonWeakEffectClear ...

function game.ZeusRepeatedStun(a) end
---@alias game-Scripts-EffectLogic.ZeusRepeatedStun ...

return game