---@meta game-Scripts-EncounterPresentation
local game = {}

function game.AngleNPCToHero(a) end
---@alias game-Scripts-EncounterPresentation.AngleNPCToHero ...

function game.ArachneCombatDrumCheck(a) end
---@alias game-Scripts-EncounterPresentation.ArachneCombatDrumCheck ...

function game.ArachneExit(a, b) end
---@alias game-Scripts-EncounterPresentation.ArachneExit ...

function game.ArtemisAppearancePresentation(a) end
---@alias game-Scripts-EncounterPresentation.ArtemisAppearancePresentation ...

function game.ArtemisExitPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.ArtemisExitPresentation ...

function game.ArtemisFirstAppearancePresentation(a) end
---@alias game-Scripts-EncounterPresentation.ArtemisFirstAppearancePresentation ...

function game.ArtemisPreSpawnPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.ArtemisPreSpawnPresentation ...

function game.AthenaExitPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.AthenaExitPresentation ...

function game.AthenaSpawnPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.AthenaSpawnPresentation ...

function game.CapturePointEncounterEndPresentation(a) end
---@alias game-Scripts-EncounterPresentation.CapturePointEncounterEndPresentation ...

function game.CapturePointEncounterStartPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.CapturePointEncounterStartPresentation ...

function game.ChallengeEncounterEndPresentation(a) end
---@alias game-Scripts-EncounterPresentation.ChallengeEncounterEndPresentation ...

function game.ChallengeEncounterStartPresentation(a) end
---@alias game-Scripts-EncounterPresentation.ChallengeEncounterStartPresentation ...

function game.CheckEnemySightedVoiceLines(a, b, c) end
---@alias game-Scripts-EncounterPresentation.CheckEnemySightedVoiceLines ...

function game.ChronosPolymorphChallengeEndPresentation(a) end
---@alias game-Scripts-EncounterPresentation.ChronosPolymorphChallengeEndPresentation ...

function game.ChronosPolymorphChallengeStartPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.ChronosPolymorphChallengeStartPresentation ...

function game.CrowdReactionPresentation(a) end
---@alias game-Scripts-EncounterPresentation.CrowdReactionPresentation ...

function game.CrowdReactionPresentationEventSource(a, b) end
---@alias game-Scripts-EncounterPresentation.CrowdReactionPresentationEventSource ...

function game.DevotionTestPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.DevotionTestPresentation ...

function game.DoHadesSpeakingPresentation(a, b, c) end
---@alias game-Scripts-EncounterPresentation.DoHadesSpeakingPresentation ...

function game.EliteChallengeSpawnPresentation(a) end
---@alias game-Scripts-EncounterPresentation.EliteChallengeSpawnPresentation ...

function game.EliteEncounterStartPresentation(a) end
---@alias game-Scripts-EncounterPresentation.EliteEncounterStartPresentation ...

function game.EncounterEndPresentation() end
---@alias game-Scripts-EncounterPresentation.EncounterEndPresentation ...

function game.ExtraDoorEncounterStartPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.ExtraDoorEncounterStartPresentation ...

function game.HadesSpeakingPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.HadesSpeakingPresentation ...

function game.HadesVoicelineBlur(a) end
---@alias game-Scripts-EncounterPresentation.HadesVoicelineBlur ...

function game.HandleWrapping(a, b) end
---@alias game-Scripts-EncounterPresentation.HandleWrapping ...

function game.HeraclesBountySpawnPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.HeraclesBountySpawnPresentation ...

function game.HeraclesEncounterEndPresentation(a) end
---@alias game-Scripts-EncounterPresentation.HeraclesEncounterEndPresentation ...

function game.HeraclesEncounterStartPresentation(a) end
---@alias game-Scripts-EncounterPresentation.HeraclesEncounterStartPresentation ...

function game.HeraclesExit(a, b) end
---@alias game-Scripts-EncounterPresentation.HeraclesExit ...

function game.HeraclesObjectiveResultPresentation(a) end
---@alias game-Scripts-EncounterPresentation.HeraclesObjectiveResultPresentation ...

function game.HeraclesPreSpawnPresentation(a) end
---@alias game-Scripts-EncounterPresentation.HeraclesPreSpawnPresentation ...

function game.HeraclesRequiredKillPresentation(a, b, c) end
---@alias game-Scripts-EncounterPresentation.HeraclesRequiredKillPresentation ...

function game.HeraclesSpawnPresentation() end
---@alias game-Scripts-EncounterPresentation.HeraclesSpawnPresentation ...

function game.HeroicStandPulse(a) end
---@alias game-Scripts-EncounterPresentation.HeroicStandPulse ...

function game.IcarusAppearancePresentation(a) end
---@alias game-Scripts-EncounterPresentation.IcarusAppearancePresentation ...

function game.IcarusExitPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.IcarusExitPresentation ...

function game.IcarusFlyByPresentation(a, b, c, d) end
---@alias game-Scripts-EncounterPresentation.IcarusFlyByPresentation ...

function game.IcarusPostChoicePresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.IcarusPostChoicePresentation ...

function game.IcarusPreChoicePresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.IcarusPreChoicePresentation ...

function game.IcarusPreSpawnPresentation(a, b, c) end
---@alias game-Scripts-EncounterPresentation.IcarusPreSpawnPresentation ...

function game.MedeaMusicManager(a, b) end
---@alias game-Scripts-EncounterPresentation.MedeaMusicManager ...

function game.NemesisBetPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.NemesisBetPresentation ...

function game.NemesisEncounterEndPresentation(a) end
---@alias game-Scripts-EncounterPresentation.NemesisEncounterEndPresentation ...

function game.NemesisEncounterStartPresentation(a) end
---@alias game-Scripts-EncounterPresentation.NemesisEncounterStartPresentation ...

function game.NemesisFieldsApproachPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.NemesisFieldsApproachPresentation ...

function game.NemesisFieldsBackAwayFromPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.NemesisFieldsBackAwayFromPresentation ...

function game.NemesisPostFieldsCombatCheckExits(a, b) end
---@alias game-Scripts-EncounterPresentation.NemesisPostFieldsCombatCheckExits ...

function game.NemesisPostTradeCheckExits(a, b) end
---@alias game-Scripts-EncounterPresentation.NemesisPostTradeCheckExits ...

function game.NemesisSpawnPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.NemesisSpawnPresentation ...

function game.NemesisSpawnPresentationFields(a) end
---@alias game-Scripts-EncounterPresentation.NemesisSpawnPresentationFields ...

function game.NemesisTeleportExitPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.NemesisTeleportExitPresentation ...

function game.NemesisThemePresentation(a, b, c) end
---@alias game-Scripts-EncounterPresentation.NemesisThemePresentation ...

function game.PerfectClearEncounterEndPresentation(a) end
---@alias game-Scripts-EncounterPresentation.PerfectClearEncounterEndPresentation ...

function game.PerfectClearEncounterStartPresentation(a) end
---@alias game-Scripts-EncounterPresentation.PerfectClearEncounterStartPresentation ...

function game.SetHeroAngleWithMoveOrder(a) end
---@alias game-Scripts-EncounterPresentation.SetHeroAngleWithMoveOrder ...

function game.ShoppingFailedPresentation(a) end
---@alias game-Scripts-EncounterPresentation.ShoppingFailedPresentation ...

function game.ShoppingFidgetPresentation(a) end
---@alias game-Scripts-EncounterPresentation.ShoppingFidgetPresentation ...

function game.ShoppingSuccessHeraclesPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.ShoppingSuccessHeraclesPresentation ...

function game.ShoppingSuccessItemPresentation(a) end
---@alias game-Scripts-EncounterPresentation.ShoppingSuccessItemPresentation ...

function game.ShoppingSuccessNemesisPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.ShoppingSuccessNemesisPresentation ...

function game.SurvivalEncounterStartPresentation(a, b) end
---@alias game-Scripts-EncounterPresentation.SurvivalEncounterStartPresentation ...

function game.TrackTimeChallengeProgress(a) end
---@alias game-Scripts-EncounterPresentation.TrackTimeChallengeProgress ...

function game.WrapObstacle(a, b, c) end
---@alias game-Scripts-EncounterPresentation.WrapObstacle ...

return game