---@meta game-Scripts-EnemyAILogic
local game = {}

game.AIThreadName = "AIThread"
---@alias game-Scripts-EnemyAILogic.AIThreadName ...

function game.AggroAI(a) end
---@alias game-Scripts-EnemyAILogic.AggroAI ...

function game.AggroNearbyUnits(a, b) end
---@alias game-Scripts-EnemyAILogic.AggroNearbyUnits ...

function game.AggroUnit(a, b) end
---@alias game-Scripts-EnemyAILogic.AggroUnit ...

function game.AIFireProjectile(a, b, c) end
---@alias game-Scripts-EnemyAILogic.AIFireProjectile ...

function game.AIFireWeapon(a, b) end
---@alias game-Scripts-EnemyAILogic.AIFireWeapon ...

function game.AIWait(a, b, c, d) end
---@alias game-Scripts-EnemyAILogic.AIWait ...

function game.AllAIAttack(a, b) end
---@alias game-Scripts-EnemyAILogic.AllAIAttack ...

function game.AllAIFollow(a, b) end
---@alias game-Scripts-EnemyAILogic.AllAIFollow ...

function game.AllAIStop(a, b) end
---@alias game-Scripts-EnemyAILogic.AllAIStop ...

function game.AmbientBattleAggroAI(a) end
---@alias game-Scripts-EnemyAILogic.AmbientBattleAggroAI ...

function game.ArtemisHealDrop(a, b) end
---@alias game-Scripts-EnemyAILogic.ArtemisHealDrop ...

function game.ArtemisPostCombat(a) end
---@alias game-Scripts-EnemyAILogic.ArtemisPostCombat ...

function game.AttackAndDie(a) end
---@alias game-Scripts-EnemyAILogic.AttackAndDie ...

function game.AttackerAI(a) end
---@alias game-Scripts-EnemyAILogic.AttackerAI ...

function game.BlendInAI(a) end
---@alias game-Scripts-EnemyAILogic.BlendInAI ...

function game.CalcEnemyWait(a, b, c) end
---@alias game-Scripts-EnemyAILogic.CalcEnemyWait ...

function game.CharybdisScyllaFightGroupAI(a, b) end
---@alias game-Scripts-EnemyAILogic.CharybdisScyllaFightGroupAI ...

function game.CharybdisTransition(a, b, c) end
---@alias game-Scripts-EnemyAILogic.CharybdisTransition ...

function game.CheckEagleRetreat(a, b, c) end
---@alias game-Scripts-EnemyAILogic.CheckEagleRetreat ...

function game.CheckElapsedTimeMultiplierIgnores(a, b) end
---@alias game-Scripts-EnemyAILogic.CheckElapsedTimeMultiplierIgnores ...

function game.CheckStun(a, b) end
---@alias game-Scripts-EnemyAILogic.CheckStun ...

function game.CheckWeaponInterrupt(a) end
---@alias game-Scripts-EnemyAILogic.CheckWeaponInterrupt ...

function game.ChooseWanderSpawnPoints(a, b) end
---@alias game-Scripts-EnemyAILogic.ChooseWanderSpawnPoints ...

function game.ChronosTimeSlow(a, b, c, d) end
---@alias game-Scripts-EnemyAILogic.ChronosTimeSlow ...

function game.ClearAllEffects(a, b) end
---@alias game-Scripts-EnemyAILogic.ClearAllEffects ...

function game.ClearEnemyEffect(a, b, c, d) end
---@alias game-Scripts-EnemyAILogic.ClearEnemyEffect ...

function game.ClearLootDrops(a) end
---@alias game-Scripts-EnemyAILogic.ClearLootDrops ...

function game.CollectShadeMerc(a) end
---@alias game-Scripts-EnemyAILogic.CollectShadeMerc ...

function game.CreateTargetMarker(a, b) end
---@alias game-Scripts-EnemyAILogic.CreateTargetMarker ...

function game.DefenseAI(a) end
---@alias game-Scripts-EnemyAILogic.DefenseAI ...

function game.DestructibleTreeHit(a, b, c) end
---@alias game-Scripts-EnemyAILogic.DestructibleTreeHit ...

function game.DieAI(a) end
---@alias game-Scripts-EnemyAILogic.DieAI ...

function game.DoAttack(a, b) end
---@alias game-Scripts-EnemyAILogic.DoAttack ...

function game.DoAttackerAILoop(a, b) end
---@alias game-Scripts-EnemyAILogic.DoAttackerAILoop ...

function game.DoWeaponFire(a, b) end
---@alias game-Scripts-EnemyAILogic.DoWeaponFire ...

function game.DumbFireAttack(a, b) end
---@alias game-Scripts-EnemyAILogic.DumbFireAttack ...

function game.EagleAttackAndFlee(a) end
---@alias game-Scripts-EnemyAILogic.EagleAttackAndFlee ...

function game.EliteMetallicInvulnerability(a) end
---@alias game-Scripts-EnemyAILogic.EliteMetallicInvulnerability ...

function game.EmptyAI() end
---@alias game-Scripts-EnemyAILogic.EmptyAI ...

function game.EndChronosTimeSlow(a, b) end
---@alias game-Scripts-EnemyAILogic.EndChronosTimeSlow ...

function game.EndOrbitAITimer(a, b) end
---@alias game-Scripts-EnemyAILogic.EndOrbitAITimer ...

function game.EndPreAttackFx(a, b) end
---@alias game-Scripts-EnemyAILogic.EndPreAttackFx ...

function game.EnemyGainHitShields(a, b) end
---@alias game-Scripts-EnemyAILogic.EnemyGainHitShields ...

function game.EnforcerBoostActivate(a, b, c, d) end
---@alias game-Scripts-EnemyAILogic.EnforcerBoostActivate ...

function game.ErisOilTransition(a, b) end
---@alias game-Scripts-EnemyAILogic.ErisOilTransition ...

function game.FinishTargetMarker(a) end
---@alias game-Scripts-EnemyAILogic.FinishTargetMarker ...

function game.FireAndQuit(a) end
---@alias game-Scripts-EnemyAILogic.FireAndQuit ...

function game.FireFloodTraps(a, b, c, d) end
---@alias game-Scripts-EnemyAILogic.FireFloodTraps ...

function game.FloodManager(a, b) end
---@alias game-Scripts-EnemyAILogic.FloodManager ...

function game.FogAI(a) end
---@alias game-Scripts-EnemyAILogic.FogAI ...

function game.FollowAI(a, b) end
---@alias game-Scripts-EnemyAILogic.FollowAI ...

function game.GetAllAllyIds(a) end
---@alias game-Scripts-EnemyAILogic.GetAllAllyIds ...

function game.GetTargetId(a, b) end
---@alias game-Scripts-EnemyAILogic.GetTargetId ...

function game.GetWeaponAIData(a, b) end
---@alias game-Scripts-EnemyAILogic.GetWeaponAIData ...

function game.GroupAI(a) end
---@alias game-Scripts-EnemyAILogic.GroupAI ...

function game.GuardAI(a) end
---@alias game-Scripts-EnemyAILogic.GuardAI ...

function game.HandleEnemyRushCollision(a, b, c) end
---@alias game-Scripts-EnemyAILogic.HandleEnemyRushCollision ...

function game.HandleEnemyTeleportation(a, b) end
---@alias game-Scripts-EnemyAILogic.HandleEnemyTeleportation ...

function game.HandleMinionWeapons(a, b) end
---@alias game-Scripts-EnemyAILogic.HandleMinionWeapons ...

function game.HandleSpawnerBurst(a, b) end
---@alias game-Scripts-EnemyAILogic.HandleSpawnerBurst ...

function game.HecateComboBreakerSplit(a, b) end
---@alias game-Scripts-EnemyAILogic.HecateComboBreakerSplit ...

function game.HecateStageTransition1(a, b, c) end
---@alias game-Scripts-EnemyAILogic.HecateStageTransition1 ...

function game.HecateStageTransition2(a, b, c) end
---@alias game-Scripts-EnemyAILogic.HecateStageTransition2 ...

function game.HecateWolfHowl(a, b) end
---@alias game-Scripts-EnemyAILogic.HecateWolfHowl ...

function game.HeraclesPostCombat(a) end
---@alias game-Scripts-EnemyAILogic.HeraclesPostCombat ...

function game.HideAndPeekAI(a) end
---@alias game-Scripts-EnemyAILogic.HideAndPeekAI ...

function game.IcarusPostCombat(a) end
---@alias game-Scripts-EnemyAILogic.IcarusPostCombat ...

function game.IdleAI(a) end
---@alias game-Scripts-EnemyAILogic.IdleAI ...

function game.IdleAIStage(a) end
---@alias game-Scripts-EnemyAILogic.IdleAIStage ...

function game.IsAIActive(a) end
---@alias game-Scripts-EnemyAILogic.IsAIActive ...

function game.IsEnemyProjectileEligible(a, b) end
---@alias game-Scripts-EnemyAILogic.IsEnemyProjectileEligible ...

function game.IsEnemyWeaponEligible(a, b, c) end
---@alias game-Scripts-EnemyAILogic.IsEnemyWeaponEligible ...

function game.IsEnemyWeaponForced(a, b) end
---@alias game-Scripts-EnemyAILogic.IsEnemyWeaponForced ...

function game.LayDrop(a, b) end
---@alias game-Scripts-EnemyAILogic.LayDrop ...

function game.Leap(a, b, c) end
---@alias game-Scripts-EnemyAILogic.Leap ...

function game.LeapIntoRangeAI(a, b) end
---@alias game-Scripts-EnemyAILogic.LeapIntoRangeAI ...

function game.MatiCloseEye(a, b) end
---@alias game-Scripts-EnemyAILogic.MatiCloseEye ...

function game.MatiOpenEye(a) end
---@alias game-Scripts-EnemyAILogic.MatiOpenEye ...

function game.MedeaCorpseExplode(a, b, c, d) end
---@alias game-Scripts-EnemyAILogic.MedeaCorpseExplode ...

function game.MineAI(a) end
---@alias game-Scripts-EnemyAILogic.MineAI ...

function game.MinionFollowAI(a) end
---@alias game-Scripts-EnemyAILogic.MinionFollowAI ...

function game.MoveToRandomLocation(a, b, c, d, e) end
---@alias game-Scripts-EnemyAILogic.MoveToRandomLocation ...

function game.MoveWithinRange(a, b, c) end
---@alias game-Scripts-EnemyAILogic.MoveWithinRange ...

function game.NemesisPostCombat(a) end
---@alias game-Scripts-EnemyAILogic.NemesisPostCombat ...

function game.NumAttacksSinceWeapon(a, b) end
---@alias game-Scripts-EnemyAILogic.NumAttacksSinceWeapon ...

function game.NumConsecutiveUses(a, b) end
---@alias game-Scripts-EnemyAILogic.NumConsecutiveUses ...

function game.OilPuddleOnHit(a, b) end
---@alias game-Scripts-EnemyAILogic.OilPuddleOnHit ...

function game.OrbitAI(a, b) end
---@alias game-Scripts-EnemyAILogic.OrbitAI ...

function game.OrbitId(a, b, c, d) end
---@alias game-Scripts-EnemyAILogic.OrbitId ...

function game.PassiveAI(a) end
---@alias game-Scripts-EnemyAILogic.PassiveAI ...

function game.PigHit(a, b, c) end
---@alias game-Scripts-EnemyAILogic.PigHit ...

function game.PolyphemusPickup(a, b, c) end
---@alias game-Scripts-EnemyAILogic.PolyphemusPickup ...

function game.ProcessAttackSlots(a, b) end
---@alias game-Scripts-EnemyAILogic.ProcessAttackSlots ...

function game.ProcessFireProjecile(a, b) end
---@alias game-Scripts-EnemyAILogic.ProcessFireProjecile ...

function game.PrometheusCancelPostAttackForesight(a, b) end
---@alias game-Scripts-EnemyAILogic.PrometheusCancelPostAttackForesight ...

function game.PrometheusHeraclesRoleSwitcher(a, b) end
---@alias game-Scripts-EnemyAILogic.PrometheusHeraclesRoleSwitcher ...

function game.PrometheusPostAttackForesight(a, b, c, d) end
---@alias game-Scripts-EnemyAILogic.PrometheusPostAttackForesight ...

function game.RamAILoop(a, b) end
---@alias game-Scripts-EnemyAILogic.RamAILoop ...

function game.ReachedAIStageEnd(a) end
---@alias game-Scripts-EnemyAILogic.ReachedAIStageEnd ...

function game.ReapplyProjectileSpeedMultiplier(a, b, c) end
---@alias game-Scripts-EnemyAILogic.ReapplyProjectileSpeedMultiplier ...

function game.ResetSentry(a) end
---@alias game-Scripts-EnemyAILogic.ResetSentry ...

function game.Retreat(a, b, c, d) end
---@alias game-Scripts-EnemyAILogic.Retreat ...

function game.SafeZoneAI(a) end
---@alias game-Scripts-EnemyAILogic.SafeZoneAI ...

function game.ScyllaFightTrackSpotlight(a) end
---@alias game-Scripts-EnemyAILogic.ScyllaFightTrackSpotlight ...

function game.SelectTentacleBurrowPoints(a, b) end
---@alias game-Scripts-EnemyAILogic.SelectTentacleBurrowPoints ...

function game.SelectWeapon(a) end
---@alias game-Scripts-EnemyAILogic.SelectWeapon ...

function game.SentryAI(a) end
---@alias game-Scripts-EnemyAILogic.SentryAI ...

function game.SetAI(a, b, c) end
---@alias game-Scripts-EnemyAILogic.SetAI ...

function game.ShadeMercAI(a) end
---@alias game-Scripts-EnemyAILogic.ShadeMercAI ...

function game.SheepAI(a) end
---@alias game-Scripts-EnemyAILogic.SheepAI ...

function game.SheepHit(a, b, c) end
---@alias game-Scripts-EnemyAILogic.SheepHit ...

function game.SpawnChronosBanners(a, b) end
---@alias game-Scripts-EnemyAILogic.SpawnChronosBanners ...

function game.SpawnSheepGhost(a) end
---@alias game-Scripts-EnemyAILogic.SpawnSheepGhost ...

function game.StagedAI(a) end
---@alias game-Scripts-EnemyAILogic.StagedAI ...

function game.SurroundAI(a) end
---@alias game-Scripts-EnemyAILogic.SurroundAI ...

function game.SurroundAIRetaliate(a) end
---@alias game-Scripts-EnemyAILogic.SurroundAIRetaliate ...

function game.TakeAmbientBattleDamage(a) end
---@alias game-Scripts-EnemyAILogic.TakeAmbientBattleDamage ...

function game.TentacleCoordinatedAttack(a, b) end
---@alias game-Scripts-EnemyAILogic.TentacleCoordinatedAttack ...

function game.TentacleDeathCheck(a) end
---@alias game-Scripts-EnemyAILogic.TentacleDeathCheck ...

function game.ThornTreeHit(a, b, c) end
---@alias game-Scripts-EnemyAILogic.ThornTreeHit ...

function game.TyphonHeadEggAI(a) end
---@alias game-Scripts-EnemyAILogic.TyphonHeadEggAI ...

function game.TyphonMineAI(a) end
---@alias game-Scripts-EnemyAILogic.TyphonMineAI ...

function game.UnitConsumeHeal(a, b) end
---@alias game-Scripts-EnemyAILogic.UnitConsumeHeal ...

function game.UnitSplit(a, b) end
---@alias game-Scripts-EnemyAILogic.UnitSplit ...

function game.UseGodStatueTrap(a, b) end
---@alias game-Scripts-EnemyAILogic.UseGodStatueTrap ...

function game.WanderToId(a, b) end
---@alias game-Scripts-EnemyAILogic.WanderToId ...

function game.WeaponRevertStunImmunity(a, b) end
---@alias game-Scripts-EnemyAILogic.WeaponRevertStunImmunity ...

function game.WeaponSetImmuneToStun(a, b) end
---@alias game-Scripts-EnemyAILogic.WeaponSetImmuneToStun ...

function game.ZagreusCollectCastAmmo(a, b, c, d) end
---@alias game-Scripts-EnemyAILogic.ZagreusCollectCastAmmo ...

function game.ZagreusUseCastAmmo(a, b, c, d) end
---@alias game-Scripts-EnemyAILogic.ZagreusUseCastAmmo ...

return game