---@meta game-Scripts-EventLogic
local game = {}

function game.ActivateForPriorityConversation(a, b, c, d) end
---@alias game-Scripts-EventLogic.ActivateForPriorityConversation ...

function game.ActivateObjects(a, b) end
---@alias game-Scripts-EventLogic.ActivateObjects ...

function game.ActivatePrePlaced(a, b) end
---@alias game-Scripts-EventLogic.ActivatePrePlaced ...

function game.ActivatePrePlacedObstacles(a, b) end
---@alias game-Scripts-EventLogic.ActivatePrePlacedObstacles ...

function game.ActivatePrePlacedUnits(a, b) end
---@alias game-Scripts-EventLogic.ActivatePrePlacedUnits ...

function game.ActivateRotatingNPCs(a, b) end
---@alias game-Scripts-EventLogic.ActivateRotatingNPCs ...

function game.AddLimitedManaRegen(a) end
---@alias game-Scripts-EventLogic.AddLimitedManaRegen ...

function game.AddLimitedSwapTrait(a) end
---@alias game-Scripts-EventLogic.AddLimitedSwapTrait ...

function game.ArachneCostumeChoice(a, b, c) end
---@alias game-Scripts-EventLogic.ArachneCostumeChoice ...

function game.AwardContractTrait() end
---@alias game-Scripts-EventLogic.AwardContractTrait ...

function game.CallFunctionName(a, b, c, d, e, f, g, h, i, ...) end
---@alias game-Scripts-EventLogic.CallFunctionName ...

function game.CheckComboBreakerDamageInWindow(a, b, c) end
---@alias game-Scripts-EventLogic.CheckComboBreakerDamageInWindow ...

function game.CheckDamageInWindow(a, b, c) end
---@alias game-Scripts-EventLogic.CheckDamageInWindow ...

function game.CheckPriorityConversations(a, b) end
---@alias game-Scripts-EventLogic.CheckPriorityConversations ...

function game.CirceBlessingChoice(a, b, c) end
---@alias game-Scripts-EventLogic.CirceBlessingChoice ...

function game.CirceEnlarge(a, b, c) end
---@alias game-Scripts-EventLogic.CirceEnlarge ...

function game.CirceHeal(a) end
---@alias game-Scripts-EventLogic.CirceHeal ...

function game.CirceMetaUpgradeRarity(a) end
---@alias game-Scripts-EventLogic.CirceMetaUpgradeRarity ...

function game.CircePetMultiplier(a, b) end
---@alias game-Scripts-EventLogic.CircePetMultiplier ...

function game.CircePolymorph(a, b, c) end
---@alias game-Scripts-EventLogic.CircePolymorph ...

function game.CirceRandomMetaUpgrade(a) end
---@alias game-Scripts-EventLogic.CirceRandomMetaUpgrade ...

function game.CirceRemoveShrineUpgrades(a) end
---@alias game-Scripts-EventLogic.CirceRemoveShrineUpgrades ...

function game.CirceShrink(a, b, c) end
---@alias game-Scripts-EventLogic.CirceShrink ...

function game.ClearPauseMenuTakeover() end
---@alias game-Scripts-EventLogic.ClearPauseMenuTakeover ...

function game.CollectRemainingMercenaries(a, b) end
---@alias game-Scripts-EventLogic.CollectRemainingMercenaries ...

function game.EchoChoice(a, b, c) end
---@alias game-Scripts-EventLogic.EchoChoice ...

function game.EchoDoubleLevelBoon() end
---@alias game-Scripts-EventLogic.EchoDoubleLevelBoon ...

function game.EchoIncreaseStats(a, b) end
---@alias game-Scripts-EventLogic.EchoIncreaseStats ...

function game.EchoLastReward(a) end
---@alias game-Scripts-EventLogic.EchoLastReward ...

function game.EchoLastRunBoon(a, b) end
---@alias game-Scripts-EventLogic.EchoLastRunBoon ...

function game.EchoPostLastRunBoonChoice(a, b) end
---@alias game-Scripts-EventLogic.EchoPostLastRunBoonChoice ...

function game.EchoRefillLastStands(a) end
---@alias game-Scripts-EventLogic.EchoRefillLastStands ...

function game.EchoRepeatKeepsake(a, b) end
---@alias game-Scripts-EventLogic.EchoRepeatKeepsake ...

function game.GetEchoLastRewardDescription(a) end
---@alias game-Scripts-EventLogic.GetEchoLastRewardDescription ...

function game.GetLootPoint(a, b) end
---@alias game-Scripts-EventLogic.GetLootPoint ...

function game.HandleChallengeLoot(a, b) end
---@alias game-Scripts-EventLogic.HandleChallengeLoot ...

function game.HandleChallengeLootDecay(a, b) end
---@alias game-Scripts-EventLogic.HandleChallengeLootDecay ...

function game.HasAnyCirceRemovableShrineUpgrade() end
---@alias game-Scripts-EventLogic.HasAnyCirceRemovableShrineUpgrade ...

function game.HealthFountainNExitCheck(a) end
---@alias game-Scripts-EventLogic.HealthFountainNExitCheck ...

function game.HealthFountainNRestoreState(a) end
---@alias game-Scripts-EventLogic.HealthFountainNRestoreState ...

function game.IcarusBenefitChoice(a, b, c) end
---@alias game-Scripts-EventLogic.IcarusBenefitChoice ...

function game.IsActivationEligible(a, b) end
---@alias game-Scripts-EventLogic.IsActivationEligible ...

function game.MedeaCurseChoice(a, b, c) end
---@alias game-Scripts-EventLogic.MedeaCurseChoice ...

function game.NarcissusBenefitChoice(a, b, c) end
---@alias game-Scripts-EventLogic.NarcissusBenefitChoice ...

function game.NemesisDamageContestHit(a, b, c) end
---@alias game-Scripts-EventLogic.NemesisDamageContestHit ...

function game.NemesisDamageContestTimer(a, b) end
---@alias game-Scripts-EventLogic.NemesisDamageContestTimer ...

function game.NemesisTradeChoice(a, b, c) end
---@alias game-Scripts-EventLogic.NemesisTradeChoice ...

function game.OlympusEagleSpawn(a, b) end
---@alias game-Scripts-EventLogic.OlympusEagleSpawn ...

function game.PauseMenuTakeoverClosed() end
---@alias game-Scripts-EventLogic.PauseMenuTakeoverClosed ...

function game.RunEvents(a, b) end
---@alias game-Scripts-EventLogic.RunEvents ...

function game.RunEventsGeneric(a, b, c) end
---@alias game-Scripts-EventLogic.RunEventsGeneric ...

function game.RunThreadedEvents(a, b) end
---@alias game-Scripts-EventLogic.RunThreadedEvents ...

function game.SelectEchoBoon(a, b, c) end
---@alias game-Scripts-EventLogic.SelectEchoBoon ...

function game.SelectFieldsDoorCageCount(a, b) end
---@alias game-Scripts-EventLogic.SelectFieldsDoorCageCount ...

function game.SetupMissingDistanceTrigger(a, b) end
---@alias game-Scripts-EventLogic.SetupMissingDistanceTrigger ...

function game.SetupPauseMenuTakeover(a, b) end
---@alias game-Scripts-EventLogic.SetupPauseMenuTakeover ...

function game.SetupPrePlacedUnits(a, b) end
---@alias game-Scripts-EventLogic.SetupPrePlacedUnits ...

function game.SetupUnits(a, b) end
---@alias game-Scripts-EventLogic.SetupUnits ...

function game.ShouldRotatorActivate(a, b, c, d, e) end
---@alias game-Scripts-EventLogic.ShouldRotatorActivate ...

function game.SpawnAllLoot(a, b) end
---@alias game-Scripts-EventLogic.SpawnAllLoot ...

function game.SpawnZagContract(a, b) end
---@alias game-Scripts-EventLogic.SpawnZagContract ...

function game.SpawnZagContractRewards(a, b) end
---@alias game-Scripts-EventLogic.SpawnZagContractRewards ...

function game.StartNemesisDamageContest(a, b) end
---@alias game-Scripts-EventLogic.StartNemesisDamageContest ...

function game.StartSkellyCastQuest(a, b) end
---@alias game-Scripts-EventLogic.StartSkellyCastQuest ...

function game.StartSkellyHitQuest(a, b) end
---@alias game-Scripts-EventLogic.StartSkellyHitQuest ...

function game.StartSkellyInventoryQuest(a, b) end
---@alias game-Scripts-EventLogic.StartSkellyInventoryQuest ...

function game.StartSkellyKillQuest(a, b) end
---@alias game-Scripts-EventLogic.StartSkellyKillQuest ...

function game.StartSkellyShadeMercQuest(a, b) end
---@alias game-Scripts-EventLogic.StartSkellyShadeMercQuest ...

function game.StartSkellySprintQuest(a, b) end
---@alias game-Scripts-EventLogic.StartSkellySprintQuest ...

function game.StartSkellyWeaponTutorial(a, b) end
---@alias game-Scripts-EventLogic.StartSkellyWeaponTutorial ...

function game.StripInteractTextRequirements(a, b) end
---@alias game-Scripts-EventLogic.StripInteractTextRequirements ...

function game.StripRequirements(a) end
---@alias game-Scripts-EventLogic.StripRequirements ...

function game.TyphonIncursion(a, b) end
---@alias game-Scripts-EventLogic.TyphonIncursion ...

function game.UpdateSkellyHitQuest(a) end
---@alias game-Scripts-EventLogic.UpdateSkellyHitQuest ...

return game