---@meta game-Scripts-EventPresentation
local game = {}

function game.ActivateTempInvulnerabilityPresentation() end
---@alias game-Scripts-EventPresentation.ActivateTempInvulnerabilityPresentation ...

function game.AddAmmoPresentation() end
---@alias game-Scripts-EventPresentation.AddAmmoPresentation ...

function game.AddedMetaUpgradePresentation(a, b) end
---@alias game-Scripts-EventPresentation.AddedMetaUpgradePresentation ...

function game.AddOverheadText(a, b) end
---@alias game-Scripts-EventPresentation.AddOverheadText ...

function game.AddReadiedMassiveAttackPolymorphPresentation() end
---@alias game-Scripts-EventPresentation.AddReadiedMassiveAttackPolymorphPresentation ...

function game.AddReadiedMassiveAttackPresentation(a) end
---@alias game-Scripts-EventPresentation.AddReadiedMassiveAttackPresentation ...

function game.AmbientCatsReaction(a) end
---@alias game-Scripts-EventPresentation.AmbientCatsReaction ...

function game.AmbientCatsSmallReaction(a) end
---@alias game-Scripts-EventPresentation.AmbientCatsSmallReaction ...

function game.AmbientDogsReaction(a) end
---@alias game-Scripts-EventPresentation.AmbientDogsReaction ...

function game.AmbientFrogsReaction(a) end
---@alias game-Scripts-EventPresentation.AmbientFrogsReaction ...

function game.ArachneCombatRewardSpawnPresentation(a, b) end
---@alias game-Scripts-EventPresentation.ArachneCombatRewardSpawnPresentation ...

function game.AresRendApplyPresentation(a, b, c) end
---@alias game-Scripts-EventPresentation.AresRendApplyPresentation ...

function game.AtLastStandMaxPresentation(a) end
---@alias game-Scripts-EventPresentation.AtLastStandMaxPresentation ...

function game.BankPayoutPresentation(a, b) end
---@alias game-Scripts-EventPresentation.BankPayoutPresentation ...

function game.BiomeDamagePresentation(a) end
---@alias game-Scripts-EventPresentation.BiomeDamagePresentation ...

function game.BiomeTimerAboutToExpirePresentation(a) end
---@alias game-Scripts-EventPresentation.BiomeTimerAboutToExpirePresentation ...

function game.BiomeTimerExpiredPresentation() end
---@alias game-Scripts-EventPresentation.BiomeTimerExpiredPresentation ...

function game.BlockedKeepsakePresentation(a, b) end
---@alias game-Scripts-EventPresentation.BlockedKeepsakePresentation ...

function game.BloomRequestEnd(a) end
---@alias game-Scripts-EventPresentation.BloomRequestEnd ...

function game.BloomRequestStart(a) end
---@alias game-Scripts-EventPresentation.BloomRequestStart ...

function game.BonusHealthAndManaPresentation(a, b, c) end
---@alias game-Scripts-EventPresentation.BonusHealthAndManaPresentation ...

function game.BonusManaPresentation(a) end
---@alias game-Scripts-EventPresentation.BonusManaPresentation ...

function game.BoonGrantedPresentation(a, b) end
---@alias game-Scripts-EventPresentation.BoonGrantedPresentation ...

function game.BossShieldTriggeredPresentation() end
---@alias game-Scripts-EventPresentation.BossShieldTriggeredPresentation ...

function game.BouldyBlessingPresentation(a) end
---@alias game-Scripts-EventPresentation.BouldyBlessingPresentation ...

function game.CannotRerollPanelPresentation(a) end
---@alias game-Scripts-EventPresentation.CannotRerollPanelPresentation ...

function game.CannotUseDoorPresentation(a) end
---@alias game-Scripts-EventPresentation.CannotUseDoorPresentation ...

function game.CannotUseFieldsRewardFinderPresentation(a) end
---@alias game-Scripts-EventPresentation.CannotUseFieldsRewardFinderPresentation ...

function game.CannotUseKeepsakeRackPresentation(a) end
---@alias game-Scripts-EventPresentation.CannotUseKeepsakeRackPresentation ...

function game.CannotUseObjectPresentation(a) end
---@alias game-Scripts-EventPresentation.CannotUseObjectPresentation ...

function game.CannotUseZoomOutPresentation(a) end
---@alias game-Scripts-EventPresentation.CannotUseZoomOutPresentation ...

function game.CantAffordPresentation(a) end
---@alias game-Scripts-EventPresentation.CantAffordPresentation ...

function game.CantPurchasePresentation(a) end
---@alias game-Scripts-EventPresentation.CantPurchasePresentation ...

function game.CantPurchaseWorldItemPresentation(a) end
---@alias game-Scripts-EventPresentation.CantPurchaseWorldItemPresentation ...

function game.CatFamiliarReaction(a) end
---@alias game-Scripts-EventPresentation.CatFamiliarReaction ...

function game.CerberusReaction(a, b) end
---@alias game-Scripts-EventPresentation.CerberusReaction ...

function game.ChaosHammerPresentation(a, b) end
---@alias game-Scripts-EventPresentation.ChaosHammerPresentation ...

function game.ChaosKeepsakeAcquiredPresentation(a) end
---@alias game-Scripts-EventPresentation.ChaosKeepsakeAcquiredPresentation ...

function game.ChaosManaDrainPresentation() end
---@alias game-Scripts-EventPresentation.ChaosManaDrainPresentation ...

function game.ChaosRewardIncreasedPresentation(a, b) end
---@alias game-Scripts-EventPresentation.ChaosRewardIncreasedPresentation ...

function game.ChaosTimerAboutToExpirePresentation(a) end
---@alias game-Scripts-EventPresentation.ChaosTimerAboutToExpirePresentation ...

function game.ChaosTimerExpirePresentation() end
---@alias game-Scripts-EventPresentation.ChaosTimerExpirePresentation ...

function game.ChaosTimerReallyAboutToExpirePing() end
---@alias game-Scripts-EventPresentation.ChaosTimerReallyAboutToExpirePing ...

function game.ChaosTimerReallyAboutToExpirePresentation(a) end
---@alias game-Scripts-EventPresentation.ChaosTimerReallyAboutToExpirePresentation ...

function game.ChaosTransformationPresentation(a, b) end
---@alias game-Scripts-EventPresentation.ChaosTransformationPresentation ...

function game.CheckPlayerTempArmorFalloffPresentation(a) end
---@alias game-Scripts-EventPresentation.CheckPlayerTempArmorFalloffPresentation ...

function game.CheckSpawnNearIdEndPresentation(a) end
---@alias game-Scripts-EventPresentation.CheckSpawnNearIdEndPresentation ...

function game.CheckSpawnNearIdPresentation(a, b) end
---@alias game-Scripts-EventPresentation.CheckSpawnNearIdPresentation ...

function game.ChillApplyPresentation(a, b) end
---@alias game-Scripts-EventPresentation.ChillApplyPresentation ...

function game.ChillClearPresentation(a, b) end
---@alias game-Scripts-EventPresentation.ChillClearPresentation ...

function game.ChronosNPCSetup(a, b) end
---@alias game-Scripts-EventPresentation.ChronosNPCSetup ...

function game.ChronosRepulseFromObject(a, b, c) end
---@alias game-Scripts-EventPresentation.ChronosRepulseFromObject ...

function game.CirceEnlargePresentation() end
---@alias game-Scripts-EventPresentation.CirceEnlargePresentation ...

function game.CirceRemoveShrinePresentation(a, b) end
---@alias game-Scripts-EventPresentation.CirceRemoveShrinePresentation ...

function game.CirceShrinkPresentation() end
---@alias game-Scripts-EventPresentation.CirceShrinkPresentation ...

function game.ClearPlayerFade(a, b) end
---@alias game-Scripts-EventPresentation.ClearPlayerFade ...

function game.CollectRemainingMercenariesPresentation() end
---@alias game-Scripts-EventPresentation.CollectRemainingMercenariesPresentation ...

function game.ConvertMetaRewardPresentation(a) end
---@alias game-Scripts-EventPresentation.ConvertMetaRewardPresentation ...

function game.CreateDialogueBackground() end
---@alias game-Scripts-EventPresentation.CreateDialogueBackground ...

function game.DaggerBlockActivePresentation(a, b) end
---@alias game-Scripts-EventPresentation.DaggerBlockActivePresentation ...

function game.DaggerBlockClearedPresentation(a) end
---@alias game-Scripts-EventPresentation.DaggerBlockClearedPresentation ...

function game.DaggerBlockTriggeredPresentation(a) end
---@alias game-Scripts-EventPresentation.DaggerBlockTriggeredPresentation ...

function game.DaggerFinalHitPresentation(a, b) end
---@alias game-Scripts-EventPresentation.DaggerFinalHitPresentation ...

function game.DecayingBoostKeepsakeExpiredPresentation() end
---@alias game-Scripts-EventPresentation.DecayingBoostKeepsakeExpiredPresentation ...

function game.DestroyGroup(a, b) end
---@alias game-Scripts-EventPresentation.DestroyGroup ...

function game.DiminishingDodgeExpiredPresentation() end
---@alias game-Scripts-EventPresentation.DiminishingDodgeExpiredPresentation ...

function game.DirectionHintPresentation(a, b) end
---@alias game-Scripts-EventPresentation.DirectionHintPresentation ...

function game.DisableTempInvulnerabilityPresentation(a) end
---@alias game-Scripts-EventPresentation.DisableTempInvulnerabilityPresentation ...

function game.DisplayEnemyHealingText(a, b) end
---@alias game-Scripts-EventPresentation.DisplayEnemyHealingText ...

function game.DisplayFreezeEscapeHint(a) end
---@alias game-Scripts-EventPresentation.DisplayFreezeEscapeHint ...

function game.DisplayPlayerDamageText(a) end
---@alias game-Scripts-EventPresentation.DisplayPlayerDamageText ...

function game.DisplayPlayerHealingText(a) end
---@alias game-Scripts-EventPresentation.DisplayPlayerHealingText ...

function game.DisplayTrueEndingInfoBanner(a, b) end
---@alias game-Scripts-EventPresentation.DisplayTrueEndingInfoBanner ...

function game.DoorHealKeepsakeExpiredPresentation(a) end
---@alias game-Scripts-EventPresentation.DoorHealKeepsakeExpiredPresentation ...

function game.DoRootApplyPresentation(a) end
---@alias game-Scripts-EventPresentation.DoRootApplyPresentation ...

function game.DoubleBoonPresentation(a, b) end
---@alias game-Scripts-EventPresentation.DoubleBoonPresentation ...

function game.DoubleRewardPresentation(a) end
---@alias game-Scripts-EventPresentation.DoubleRewardPresentation ...

function game.DrainClearCastMeter(a) end
---@alias game-Scripts-EventPresentation.DrainClearCastMeter ...

function game.EchoDoubleBoonLevelPresentation(a) end
---@alias game-Scripts-EventPresentation.EchoDoubleBoonLevelPresentation ...

function game.EchoLastRunBoonPresentation(a) end
---@alias game-Scripts-EventPresentation.EchoLastRunBoonPresentation ...

function game.ElementalTraitUpdatedPresentationReal() end
---@alias game-Scripts-EventPresentation.ElementalTraitUpdatedPresentationReal ...

function game.EncounterStartInvulnerableWarnPresentation() end
---@alias game-Scripts-EventPresentation.EncounterStartInvulnerableWarnPresentation ...

function game.EndClearCastPresentation() end
---@alias game-Scripts-EventPresentation.EndClearCastPresentation ...

function game.EndHermesEntranceVisuals() end
---@alias game-Scripts-EventPresentation.EndHermesEntranceVisuals ...

function game.EndSpellSlowPresentation() end
---@alias game-Scripts-EventPresentation.EndSpellSlowPresentation ...

function game.EndTimeSlowPresentation() end
---@alias game-Scripts-EventPresentation.EndTimeSlowPresentation ...

function game.FamiliarCosmeticReaction(a) end
---@alias game-Scripts-EventPresentation.FamiliarCosmeticReaction ...

function game.FatedValidityStatePresentation(a) end
---@alias game-Scripts-EventPresentation.FatedValidityStatePresentation ...

function game.FinishedTextLinesPresentation(a, b) end
---@alias game-Scripts-EventPresentation.FinishedTextLinesPresentation ...

function game.FirstSummonHitPresentation(a, b, c) end
---@alias game-Scripts-EventPresentation.FirstSummonHitPresentation ...

function game.FirstTimeWeaponPickupPresentation(a) end
---@alias game-Scripts-EventPresentation.FirstTimeWeaponPickupPresentation ...

function game.FreezeEscapeInputPresentation(a) end
---@alias game-Scripts-EventPresentation.FreezeEscapeInputPresentation ...

function game.FrenzyStartAnimation() end
---@alias game-Scripts-EventPresentation.FrenzyStartAnimation ...

function game.FrogFamiliarReaction(a) end
---@alias game-Scripts-EventPresentation.FrogFamiliarReaction ...

function game.FrozenPresentation(a) end
---@alias game-Scripts-EventPresentation.FrozenPresentation ...

function game.GenericPresentation(a, b) end
---@alias game-Scripts-EventPresentation.GenericPresentation ...

function game.GiftPointEpicRefundPresentation() end
---@alias game-Scripts-EventPresentation.GiftPointEpicRefundPresentation ...

function game.GiftPointRareRefundPresentation() end
---@alias game-Scripts-EventPresentation.GiftPointRareRefundPresentation ...

function game.GiftPointRefundPresentation() end
---@alias game-Scripts-EventPresentation.GiftPointRefundPresentation ...

function game.GodLootPickupPresentation(a, b) end
---@alias game-Scripts-EventPresentation.GodLootPickupPresentation ...

function game.GoldifyPresentation(a) end
---@alias game-Scripts-EventPresentation.GoldifyPresentation ...

function game.GrantedLowHealthBonusBuffStatePresentation(a, b, c) end
---@alias game-Scripts-EventPresentation.GrantedLowHealthBonusBuffStatePresentation ...

function game.HadesKeepsakeAcquiredPresentation(a) end
---@alias game-Scripts-EventPresentation.HadesKeepsakeAcquiredPresentation ...

function game.HadesPreDamagePresentation(a, b, c) end
---@alias game-Scripts-EventPresentation.HadesPreDamagePresentation ...

function game.HammerKeepsakeAcquiredPresentation(a) end
---@alias game-Scripts-EventPresentation.HammerKeepsakeAcquiredPresentation ...

function game.HammerKeepsakeLostPresentation(a) end
---@alias game-Scripts-EventPresentation.HammerKeepsakeLostPresentation ...

function game.HeraTraitRarityPresentation(a, b, c) end
---@alias game-Scripts-EventPresentation.HeraTraitRarityPresentation ...

function game.HeroArmorDamagePresentationThread(a, b) end
---@alias game-Scripts-EventPresentation.HeroArmorDamagePresentationThread ...

function game.HeroDamageLowHealthPresentation(a) end
---@alias game-Scripts-EventPresentation.HeroDamageLowHealthPresentation ...

function game.HeroDamagePresentation(a, b) end
---@alias game-Scripts-EventPresentation.HeroDamagePresentation ...

function game.HeroDamagePresentationThread(a, b) end
---@alias game-Scripts-EventPresentation.HeroDamagePresentationThread ...

function game.HeroFinalDamagePresentationThread(a, b) end
---@alias game-Scripts-EventPresentation.HeroFinalDamagePresentationThread ...

function game.HeroLowHealthBarPulseThread() end
---@alias game-Scripts-EventPresentation.HeroLowHealthBarPulseThread ...

function game.HeroLowHealthPresentationThread(a) end
---@alias game-Scripts-EventPresentation.HeroLowHealthPresentationThread ...

function game.HeroLowHealthShroudPulseThread() end
---@alias game-Scripts-EventPresentation.HeroLowHealthShroudPulseThread ...

function game.HeroMajorDamagePresentationThread(a, b) end
---@alias game-Scripts-EventPresentation.HeroMajorDamagePresentationThread ...

function game.HeroShopDeliveryPresentation(a) end
---@alias game-Scripts-EventPresentation.HeroShopDeliveryPresentation ...

function game.HeroTraitTransformPresentation(a) end
---@alias game-Scripts-EventPresentation.HeroTraitTransformPresentation ...

function game.HideGameplayTimers() end
---@alias game-Scripts-EventPresentation.HideGameplayTimers ...

function game.HypnosPointRefundPresentation() end
---@alias game-Scripts-EventPresentation.HypnosPointRefundPresentation ...

function game.IncreasedHammerRarityPresentation(a, b) end
---@alias game-Scripts-EventPresentation.IncreasedHammerRarityPresentation ...

function game.IncreasedTraitLevelPresentation(a, b, c) end
---@alias game-Scripts-EventPresentation.IncreasedTraitLevelPresentation ...

function game.IncreasedTraitRarityPresentation(a, b) end
---@alias game-Scripts-EventPresentation.IncreasedTraitRarityPresentation ...

function game.InRunFateDisabledPresentation(a) end
---@alias game-Scripts-EventPresentation.InRunFateDisabledPresentation ...

function game.InRunHadesBoonRemoved(a, b) end
---@alias game-Scripts-EventPresentation.InRunHadesBoonRemoved ...

function game.InteractBlockedByEnemiesPresentation(a, b, c) end
---@alias game-Scripts-EventPresentation.InteractBlockedByEnemiesPresentation ...

function game.KeepsakeLevelUpPresentation(a) end
---@alias game-Scripts-EventPresentation.KeepsakeLevelUpPresentation ...

function game.KeepsakeScreenClearSaveFirstPresentation(a) end
---@alias game-Scripts-EventPresentation.KeepsakeScreenClearSaveFirstPresentation ...

function game.KeepsakeScreenSaveFirstPresentation(a) end
---@alias game-Scripts-EventPresentation.KeepsakeScreenSaveFirstPresentation ...

function game.LastShotFiredPresentation(a) end
---@alias game-Scripts-EventPresentation.LastShotFiredPresentation ...

function game.LootPickupPresentation(a, b) end
---@alias game-Scripts-EventPresentation.LootPickupPresentation ...

function game.LowHealthBonusBuffStatePresentation(a) end
---@alias game-Scripts-EventPresentation.LowHealthBonusBuffStatePresentation ...

function game.LowHealthCritKeepsakeExpiredPresentation(a) end
---@alias game-Scripts-EventPresentation.LowHealthCritKeepsakeExpiredPresentation ...

function game.MagicWordPresentation(a, b, c, d) end
---@alias game-Scripts-EventPresentation.MagicWordPresentation ...

function game.MatchModelToPortrait(a, b, c, d) end
---@alias game-Scripts-EventPresentation.MatchModelToPortrait ...

function game.MaxHealthChangedPresentation(a, b) end
---@alias game-Scripts-EventPresentation.MaxHealthChangedPresentation ...

function game.MaxManaChangedPresentation(a, b) end
---@alias game-Scripts-EventPresentation.MaxManaChangedPresentation ...

function game.MedeaCursePreChoicePresentation(a, b) end
---@alias game-Scripts-EventPresentation.MedeaCursePreChoicePresentation ...

function game.MetaPointRoomRewardPresentation(a) end
---@alias game-Scripts-EventPresentation.MetaPointRoomRewardPresentation ...

function game.MetaPointRoomRewardPresentationThread(a) end
---@alias game-Scripts-EventPresentation.MetaPointRoomRewardPresentationThread ...

function game.MoneyFlashRed() end
---@alias game-Scripts-EventPresentation.MoneyFlashRed ...

function game.MoneyShieldBlockPresentation(a, b) end
---@alias game-Scripts-EventPresentation.MoneyShieldBlockPresentation ...

function game.MoneyShieldDeactivatedPresentation() end
---@alias game-Scripts-EventPresentation.MoneyShieldDeactivatedPresentation ...

function game.MultipleEncounterStartPresentation(a, b) end
---@alias game-Scripts-EventPresentation.MultipleEncounterStartPresentation ...

function game.NemesisDamageContestCountdownPresentation(a, b, c) end
---@alias game-Scripts-EventPresentation.NemesisDamageContestCountdownPresentation ...

function game.NemesisDamageContestFailPresentation(a, b) end
---@alias game-Scripts-EventPresentation.NemesisDamageContestFailPresentation ...

function game.NemesisDamageContestFinalHitPresentation(a, b) end
---@alias game-Scripts-EventPresentation.NemesisDamageContestFinalHitPresentation ...

function game.NemesisDamageContestGreatSuccessPresentation(a, b) end
---@alias game-Scripts-EventPresentation.NemesisDamageContestGreatSuccessPresentation ...

function game.NemesisDamageContestHitPresentation(a, b) end
---@alias game-Scripts-EventPresentation.NemesisDamageContestHitPresentation ...

function game.NemesisDamageContestStartPresentation(a, b) end
---@alias game-Scripts-EventPresentation.NemesisDamageContestStartPresentation ...

function game.NemesisDamageContestSuccessPresentation(a, b) end
---@alias game-Scripts-EventPresentation.NemesisDamageContestSuccessPresentation ...

function game.NeoChronosAppear(a, b) end
---@alias game-Scripts-EventPresentation.NeoChronosAppear ...

function game.NeoChronosNPCSetup(a, b) end
---@alias game-Scripts-EventPresentation.NeoChronosNPCSetup ...

function game.OnManaRestored(a) end
---@alias game-Scripts-EventPresentation.OnManaRestored ...

function game.OnPlayerArmorGain(a) end
---@alias game-Scripts-EventPresentation.OnPlayerArmorGain ...

function game.OnPlayerHealed(a, b) end
---@alias game-Scripts-EventPresentation.OnPlayerHealed ...

function game.OverheatStartPresentation(a) end
---@alias game-Scripts-EventPresentation.OverheatStartPresentation ...

function game.PartnersChattingPresentation(a, b, c) end
---@alias game-Scripts-EventPresentation.PartnersChattingPresentation ...

function game.PartnersChattingStop() end
---@alias game-Scripts-EventPresentation.PartnersChattingStop ...

function game.PerfectChargeRefundPresentation() end
---@alias game-Scripts-EventPresentation.PerfectChargeRefundPresentation ...

function game.PerfectDamageBoonExpire() end
---@alias game-Scripts-EventPresentation.PerfectDamageBoonExpire ...

function game.PerfectDamageBoonRenewed() end
---@alias game-Scripts-EventPresentation.PerfectDamageBoonRenewed ...

function game.PermafyShopItemPresentation(a) end
---@alias game-Scripts-EventPresentation.PermafyShopItemPresentation ...

function game.PickSpawnAngle(a, b) end
---@alias game-Scripts-EventPresentation.PickSpawnAngle ...

function game.PlayCharacterAnim(a, b) end
---@alias game-Scripts-EventPresentation.PlayCharacterAnim ...

function game.PlayEmote(a) end
---@alias game-Scripts-EventPresentation.PlayEmote ...

function game.PlayEmoteAnimFromSource(a, b, c, d) end
---@alias game-Scripts-EventPresentation.PlayEmoteAnimFromSource ...

function game.PlayEmoteSimple(a, b, c) end
---@alias game-Scripts-EventPresentation.PlayEmoteSimple ...

function game.PlayerArmorBreakPresentation(a) end
---@alias game-Scripts-EventPresentation.PlayerArmorBreakPresentation ...

function game.PlayerArmorBreakSimSpeed() end
---@alias game-Scripts-EventPresentation.PlayerArmorBreakSimSpeed ...

function game.PlayHecateTauntAnim(a, b) end
---@alias game-Scripts-EventPresentation.PlayHecateTauntAnim ...

function game.PolecatFamiliarReaction(a) end
---@alias game-Scripts-EventPresentation.PolecatFamiliarReaction ...

function game.PopOverheadText(a) end
---@alias game-Scripts-EventPresentation.PopOverheadText ...

function game.PoseidonClearCastPresentation() end
---@alias game-Scripts-EventPresentation.PoseidonClearCastPresentation ...

function game.PoseidonPotionPresentation(a, b) end
---@alias game-Scripts-EventPresentation.PoseidonPotionPresentation ...

function game.PoseidonSprintBallDetachPresentation(a) end
---@alias game-Scripts-EventPresentation.PoseidonSprintBallDetachPresentation ...

function game.PostEpiloguePresentation(a, b) end
---@alias game-Scripts-EventPresentation.PostEpiloguePresentation ...

function game.PostRerollPanelPresentation(a, b) end
---@alias game-Scripts-EventPresentation.PostRerollPanelPresentation ...

function game.PotionClearCastPresentation(a) end
---@alias game-Scripts-EventPresentation.PotionClearCastPresentation ...

function game.PowerWordPresentation(a, b, c, d) end
---@alias game-Scripts-EventPresentation.PowerWordPresentation ...

function game.PowerWordPresentationWorld(a, b) end
---@alias game-Scripts-EventPresentation.PowerWordPresentationWorld ...

function game.PreDamagePresentation(a, b, c) end
---@alias game-Scripts-EventPresentation.PreDamagePresentation ...

function game.PreRerollPanelPresentation(a, b) end
---@alias game-Scripts-EventPresentation.PreRerollPanelPresentation ...

function game.PulseAnimation(a) end
---@alias game-Scripts-EventPresentation.PulseAnimation ...

function game.PulseText(a) end
---@alias game-Scripts-EventPresentation.PulseText ...

function game.RaiseDeadPresentation(a) end
---@alias game-Scripts-EventPresentation.RaiseDeadPresentation ...

function game.RandomStoreItemPresentation(a) end
---@alias game-Scripts-EventPresentation.RandomStoreItemPresentation ...

function game.RangedFailedNoAmmoPresentation() end
---@alias game-Scripts-EventPresentation.RangedFailedNoAmmoPresentation ...

function game.RavenFamiliarReaction(a) end
---@alias game-Scripts-EventPresentation.RavenFamiliarReaction ...

function game.RefundKeepsakeExpiredPresentation(a) end
---@alias game-Scripts-EventPresentation.RefundKeepsakeExpiredPresentation ...

function game.RemoveHermesInPerson(a, b) end
---@alias game-Scripts-EventPresentation.RemoveHermesInPerson ...

function game.RemovePlayerTempArmorPresentation(a) end
---@alias game-Scripts-EventPresentation.RemovePlayerTempArmorPresentation ...

function game.RemoveReadiedMassiveAttackPresentation(a) end
---@alias game-Scripts-EventPresentation.RemoveReadiedMassiveAttackPresentation ...

function game.RepulseFromObject(a, b) end
---@alias game-Scripts-EventPresentation.RepulseFromObject ...

function game.ResourceGiftedInEventPresentation(a, b) end
---@alias game-Scripts-EventPresentation.ResourceGiftedInEventPresentation ...

function game.ResourceGiftedPresentation(a) end
---@alias game-Scripts-EventPresentation.ResourceGiftedPresentation ...

function game.RoomStartLowHealthBonusBuffStatePresentation() end
---@alias game-Scripts-EventPresentation.RoomStartLowHealthBonusBuffStatePresentation ...

function game.RootApplyPresentation(a, b) end
---@alias game-Scripts-EventPresentation.RootApplyPresentation ...

function game.RootClearPresentation(a, b) end
---@alias game-Scripts-EventPresentation.RootClearPresentation ...

function game.RunStartChaosBlessingPresentation() end
---@alias game-Scripts-EventPresentation.RunStartChaosBlessingPresentation ...

function game.RunStartHadesKeepsakeAcquiredPresentation() end
---@alias game-Scripts-EventPresentation.RunStartHadesKeepsakeAcquiredPresentation ...

function game.RunStartHammerKeepsakeAcquiredPresentation() end
---@alias game-Scripts-EventPresentation.RunStartHammerKeepsakeAcquiredPresentation ...

function game.SetPlayerFade(a) end
---@alias game-Scripts-EventPresentation.SetPlayerFade ...

function game.SetPlayerTempArmorPresentation(a) end
---@alias game-Scripts-EventPresentation.SetPlayerTempArmorPresentation ...

function game.SetupCerberusStory(a, b) end
---@alias game-Scripts-EventPresentation.SetupCerberusStory ...

function game.SetupElementalTraitUpdatedPresentation(a, b, c, d) end
---@alias game-Scripts-EventPresentation.SetupElementalTraitUpdatedPresentation ...

function game.ShowCrystalPresentation(a, b) end
---@alias game-Scripts-EventPresentation.ShowCrystalPresentation ...

function game.ShowInvincibubbleOnObject(a, b) end
---@alias game-Scripts-EventPresentation.ShowInvincibubbleOnObject ...

function game.ShowMetaUpgradeCard(a, b, c) end
---@alias game-Scripts-EventPresentation.ShowMetaUpgradeCard ...

function game.SkipEncounterEndPresentation() end
---@alias game-Scripts-EventPresentation.SkipEncounterEndPresentation ...

function game.SkipEncounterPresentation() end
---@alias game-Scripts-EventPresentation.SkipEncounterPresentation ...

function game.SpawnHermesInPerson(a, b) end
---@alias game-Scripts-EventPresentation.SpawnHermesInPerson ...

function game.SpellSlowWarnPresentation() end
---@alias game-Scripts-EventPresentation.SpellSlowWarnPresentation ...

function game.SprintShieldTriggeredPresentation() end
---@alias game-Scripts-EventPresentation.SprintShieldTriggeredPresentation ...

function game.StaffHealPresentation(a) end
---@alias game-Scripts-EventPresentation.StaffHealPresentation ...

function game.StartBlinkTrailPresentation() end
---@alias game-Scripts-EventPresentation.StartBlinkTrailPresentation ...

function game.StartedTextLinesPresentation(a, b) end
---@alias game-Scripts-EventPresentation.StartedTextLinesPresentation ...

function game.StartHermesVisualEffects(a) end
---@alias game-Scripts-EventPresentation.StartHermesVisualEffects ...

function game.StartHeroLowHealthPresentation() end
---@alias game-Scripts-EventPresentation.StartHeroLowHealthPresentation ...

function game.StartSpellSlowPresentation() end
---@alias game-Scripts-EventPresentation.StartSpellSlowPresentation ...

function game.StartTimeSlowPresentation(a) end
---@alias game-Scripts-EventPresentation.StartTimeSlowPresentation ...

function game.StasisPresentation(a) end
---@alias game-Scripts-EventPresentation.StasisPresentation ...

function game.StopHephaestusVfx() end
---@alias game-Scripts-EventPresentation.StopHephaestusVfx ...

function game.StoreRestockPresentation(a) end
---@alias game-Scripts-EventPresentation.StoreRestockPresentation ...

function game.StoreRewardRandomStackPresentation() end
---@alias game-Scripts-EventPresentation.StoreRewardRandomStackPresentation ...

function game.SuperGiftPointRefundPresentation() end
---@alias game-Scripts-EventPresentation.SuperGiftPointRefundPresentation ...

function game.SuperSacrificePresentation(a, b, c) end
---@alias game-Scripts-EventPresentation.SuperSacrificePresentation ...

function game.SurpriseNPCPresentation(a, b) end
---@alias game-Scripts-EventPresentation.SurpriseNPCPresentation ...

function game.SwapAnimations(a, b) end
---@alias game-Scripts-EventPresentation.SwapAnimations ...

function game.TempArmorEndWarnPresentation() end
---@alias game-Scripts-EventPresentation.TempArmorEndWarnPresentation ...

function game.TemporaryHealExpirationPresentation() end
---@alias game-Scripts-EventPresentation.TemporaryHealExpirationPresentation ...

function game.TerminateBlinkTrail() end
---@alias game-Scripts-EventPresentation.TerminateBlinkTrail ...

function game.TimedBuffExpiredPresentation(a) end
---@alias game-Scripts-EventPresentation.TimedBuffExpiredPresentation ...

function game.TrackPlayer(a, b) end
---@alias game-Scripts-EventPresentation.TrackPlayer ...

function game.TraitLockedPresentation(a) end
---@alias game-Scripts-EventPresentation.TraitLockedPresentation ...

function game.TraitSacrificedPresentation(a) end
---@alias game-Scripts-EventPresentation.TraitSacrificedPresentation ...

function game.UnfrozenPresentation(a, b) end
---@alias game-Scripts-EventPresentation.UnfrozenPresentation ...

function game.UnlockCosmeticsShop(a, b) end
---@alias game-Scripts-EventPresentation.UnlockCosmeticsShop ...

function game.UnwrapLootPresentation(a) end
---@alias game-Scripts-EventPresentation.UnwrapLootPresentation ...

function game.UpgradeBoonRarityPresentation(a) end
---@alias game-Scripts-EventPresentation.UpgradeBoonRarityPresentation ...

function game.WeaponFiredGenericPresentation(a, b, c, d) end
---@alias game-Scripts-EventPresentation.WeaponFiredGenericPresentation ...

function game.WorldShopItemRestockPresentation(a) end
---@alias game-Scripts-EventPresentation.WorldShopItemRestockPresentation ...

function game.ZagreusDeathDefiancePresentation(a, b, c) end
---@alias game-Scripts-EventPresentation.ZagreusDeathDefiancePresentation ...

return game