---@meta game-Scripts-FamiliarLogic
local game = {}

function game.ActivateFamiliar(a, b) end
---@alias game-Scripts-FamiliarLogic.ActivateFamiliar ...

function game.AdjustFamiliarPathfinding(a, b) end
---@alias game-Scripts-FamiliarLogic.AdjustFamiliarPathfinding ...

function game.AssignFamiliarKits(a, b) end
---@alias game-Scripts-FamiliarLogic.AssignFamiliarKits ...

function game.CatFamiliarAI(a, b) end
---@alias game-Scripts-FamiliarLogic.CatFamiliarAI ...

function game.CatFamiliarMoveToLocation(a, b) end
---@alias game-Scripts-FamiliarLogic.CatFamiliarMoveToLocation ...

function game.CatFamiliarMoveToRandomLocation(a, b) end
---@alias game-Scripts-FamiliarLogic.CatFamiliarMoveToRandomLocation ...

function game.CatFamiliarShouldAlert(a, b) end
---@alias game-Scripts-FamiliarLogic.CatFamiliarShouldAlert ...

function game.CatFamiliarStopAI(a) end
---@alias game-Scripts-FamiliarLogic.CatFamiliarStopAI ...

function game.ClearRavenMark(a, b) end
---@alias game-Scripts-FamiliarLogic.ClearRavenMark ...

function game.EquipFamiliar(a, b) end
---@alias game-Scripts-FamiliarLogic.EquipFamiliar ...

function game.FamiliarSetup(a, b) end
---@alias game-Scripts-FamiliarLogic.FamiliarSetup ...

function game.FamiliarShouldUseCombatLogic() end
---@alias game-Scripts-FamiliarLogic.FamiliarShouldUseCombatLogic ...

function game.FrogFamiliarAI(a, b) end
---@alias game-Scripts-FamiliarLogic.FrogFamiliarAI ...

function game.FrogFamiliarGetRecoveryTime(a) end
---@alias game-Scripts-FamiliarLogic.FrogFamiliarGetRecoveryTime ...

function game.FrogFamiliarLinkBegin(a) end
---@alias game-Scripts-FamiliarLogic.FrogFamiliarLinkBegin ...

function game.FrogFamiliarMoveToLocation(a, b) end
---@alias game-Scripts-FamiliarLogic.FrogFamiliarMoveToLocation ...

function game.FrogFamiliarStopAI(a) end
---@alias game-Scripts-FamiliarLogic.FrogFamiliarStopAI ...

function game.FrogHitResponse(a, b) end
---@alias game-Scripts-FamiliarLogic.FrogHitResponse ...

function game.FrogLeap(a, b) end
---@alias game-Scripts-FamiliarLogic.FrogLeap ...

function game.GetFamiliarUpgradeCount(a) end
---@alias game-Scripts-FamiliarLogic.GetFamiliarUpgradeCount ...

function game.HoundFamiliarAI(a, b) end
---@alias game-Scripts-FamiliarLogic.HoundFamiliarAI ...

function game.HoundFamiliarMoveToLocation(a, b) end
---@alias game-Scripts-FamiliarLogic.HoundFamiliarMoveToLocation ...

function game.HoundFamiliarStartEncounter(a) end
---@alias game-Scripts-FamiliarLogic.HoundFamiliarStartEncounter ...

function game.HoundFamiliarStopAI(a) end
---@alias game-Scripts-FamiliarLogic.HoundFamiliarStopAI ...

function game.PolecatFamiliarAI(a, b) end
---@alias game-Scripts-FamiliarLogic.PolecatFamiliarAI ...

function game.PolecatFamiliarBurrowCooldown(a) end
---@alias game-Scripts-FamiliarLogic.PolecatFamiliarBurrowCooldown ...

function game.PolecatFamiliarGuard(a, b) end
---@alias game-Scripts-FamiliarLogic.PolecatFamiliarGuard ...

function game.PolecatFamiliarMoveToLocation(a, b) end
---@alias game-Scripts-FamiliarLogic.PolecatFamiliarMoveToLocation ...

function game.PolecatFamiliarStartEncounter(a, b) end
---@alias game-Scripts-FamiliarLogic.PolecatFamiliarStartEncounter ...

function game.PolecatFamiliarStopAI(a, b) end
---@alias game-Scripts-FamiliarLogic.PolecatFamiliarStopAI ...

function game.RavenFamiliarAI(a, b) end
---@alias game-Scripts-FamiliarLogic.RavenFamiliarAI ...

function game.RavenFamiliarLinkBegin(a) end
---@alias game-Scripts-FamiliarLogic.RavenFamiliarLinkBegin ...

function game.RavenFamiliarMoveToLocation(a, b) end
---@alias game-Scripts-FamiliarLogic.RavenFamiliarMoveToLocation ...

function game.RavenFamiliarStopAI(a, b) end
---@alias game-Scripts-FamiliarLogic.RavenFamiliarStopAI ...

function game.RavenFamiliarTeleportWhenStopped(a, b) end
---@alias game-Scripts-FamiliarLogic.RavenFamiliarTeleportWhenStopped ...

function game.ReenableFamiliar(a, b) end
---@alias game-Scripts-FamiliarLogic.ReenableFamiliar ...

function game.ReturnFamiliarToKit(a, b, c) end
---@alias game-Scripts-FamiliarLogic.ReturnFamiliarToKit ...

function game.UnequipFamiliar(a, b) end
---@alias game-Scripts-FamiliarLogic.UnequipFamiliar ...

function game.UpdateFamiliarKits(a) end
---@alias game-Scripts-FamiliarLogic.UpdateFamiliarKits ...

function game.UseFamiliar(a, b, c) end
---@alias game-Scripts-FamiliarLogic.UseFamiliar ...

function game.UseFamiliarUnequip(a, b, c) end
---@alias game-Scripts-FamiliarLogic.UseFamiliarUnequip ...

function game.WaitForFamiliarLinkEnd(a, b) end
---@alias game-Scripts-FamiliarLogic.WaitForFamiliarLinkEnd ...

return game