---@meta game-Scripts-FamiliarPresentation
local game = {}

function game.CatFamiliarAlertedPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarAlertedPresentation ...

function game.CatFamiliarAttackPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarAttackPresentation ...

function game.CatFamiliarCostumedPresentation(a) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarCostumedPresentation ...

function game.CatFamiliarGiftedPresentation(a) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarGiftedPresentation ...

function game.CatFamiliarGoToSleepPresentation(a) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarGoToSleepPresentation ...

function game.CatFamiliarGoToSleepQuickPresentation(a) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarGoToSleepQuickPresentation ...

function game.CatFamiliarPreAttackPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarPreAttackPresentation ...

function game.CatFamiliarSpawnPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarSpawnPresentation ...

function game.CatFamiliarSpecialInteractLockedInRun(a, b) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarSpecialInteractLockedInRun ...

function game.CatFamiliarSpecialInteractUnlockedInHub(a, b) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarSpecialInteractUnlockedInHub ...

function game.CatFamiliarTeleportToHeroPresentation(a) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarTeleportToHeroPresentation ...

function game.EquipFamiliarPresentation(a) end
---@alias game-Scripts-FamiliarPresentation.EquipFamiliarPresentation ...

function game.FamiliarFledPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.FamiliarFledPresentation ...

function game.FamiliarRavenStartNewRunPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.FamiliarRavenStartNewRunPresentation ...

function game.FamiliarRecruitBannerPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.FamiliarRecruitBannerPresentation ...

function game.FamiliarRecruitPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.FamiliarRecruitPresentation ...

function game.FamiliarRoomExitPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.FamiliarRoomExitPresentation ...

function game.FamiliarTeleportPresentation(a) end
---@alias game-Scripts-FamiliarPresentation.FamiliarTeleportPresentation ...

function game.FamiliarVictoryPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.FamiliarVictoryPresentation ...

function game.FrogFamiliarSpawnPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.FrogFamiliarSpawnPresentation ...

function game.FrogFamiliarSpecialInteractUnlockedInHub(a, b) end
---@alias game-Scripts-FamiliarPresentation.FrogFamiliarSpecialInteractUnlockedInHub ...

function game.HoundFamiliarReaction(a, b) end
---@alias game-Scripts-FamiliarPresentation.HoundFamiliarReaction ...

function game.HoundFamiliarSpawnPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.HoundFamiliarSpawnPresentation ...

function game.HoundFamiliarSpecialInteractLockedInRun(a, b) end
---@alias game-Scripts-FamiliarPresentation.HoundFamiliarSpecialInteractLockedInRun ...

function game.HoundFamiliarSpecialInteractUnlockedInHub(a, b) end
---@alias game-Scripts-FamiliarPresentation.HoundFamiliarSpecialInteractUnlockedInHub ...

function game.PetFamiliarFrog(a, b) end
---@alias game-Scripts-FamiliarPresentation.PetFamiliarFrog ...

function game.PolecatFamiliarBurrowPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.PolecatFamiliarBurrowPresentation ...

function game.PolecatFamiliarGuardEndPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.PolecatFamiliarGuardEndPresentation ...

function game.PolecatFamiliarGuardPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.PolecatFamiliarGuardPresentation ...

function game.PolecatFamiliarGuardTimeoutThread(a, b) end
---@alias game-Scripts-FamiliarPresentation.PolecatFamiliarGuardTimeoutThread ...

function game.PolecatFamiliarSpawnPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.PolecatFamiliarSpawnPresentation ...

function game.PolecatFamiliarSpecialInteractLockedInRun(a, b) end
---@alias game-Scripts-FamiliarPresentation.PolecatFamiliarSpecialInteractLockedInRun ...

function game.PolecatFamiliarSpecialInteractUnlockedInHub(a, b) end
---@alias game-Scripts-FamiliarPresentation.PolecatFamiliarSpecialInteractUnlockedInHub ...

function game.PolecatFamiliarUnburrowPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.PolecatFamiliarUnburrowPresentation ...

function game.PolecatFamiliarVictoryPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.PolecatFamiliarVictoryPresentation ...

function game.RavenFamiliarAttackPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.RavenFamiliarAttackPresentation ...

function game.RavenFamiliarDropEnterPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.RavenFamiliarDropEnterPresentation ...

function game.RavenFamiliarDropExitPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.RavenFamiliarDropExitPresentation ...

function game.RavenFamiliarRoomExitPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.RavenFamiliarRoomExitPresentation ...

function game.RavenFamiliarSpawnPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.RavenFamiliarSpawnPresentation ...

function game.RavenFamiliarSpecialInteractLockedInRun(a, b) end
---@alias game-Scripts-FamiliarPresentation.RavenFamiliarSpecialInteractLockedInRun ...

function game.RavenFamiliarSpecialInteractUnlockedInHub(a, b) end
---@alias game-Scripts-FamiliarPresentation.RavenFamiliarSpecialInteractUnlockedInHub ...

function game.RavenFamiliarVictoryPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.RavenFamiliarVictoryPresentation ...

function game.UnequipFamiliarPresentation(a) end
---@alias game-Scripts-FamiliarPresentation.UnequipFamiliarPresentation ...

function game.UseCrossroadsPet01(a, b) end
---@alias game-Scripts-FamiliarPresentation.UseCrossroadsPet01 ...

return game