---@meta game-Scripts-FlashbackPresentation
local game = {}

function game.ChronosCrouchPresentation(a, b) end
---@alias game-Scripts-FlashbackPresentation.ChronosCrouchPresentation ...

function game.ConcludeFlashback() end
---@alias game-Scripts-FlashbackPresentation.ConcludeFlashback ...

function game.Flashback02Objective(a, b) end
---@alias game-Scripts-FlashbackPresentation.Flashback02Objective ...

function game.Flashback03MemoryPresentation(a, b) end
---@alias game-Scripts-FlashbackPresentation.Flashback03MemoryPresentation ...

function game.FlashbackExpandClamps() end
---@alias game-Scripts-FlashbackPresentation.FlashbackExpandClamps ...

function game.HecateFlashback02Exit(a, b) end
---@alias game-Scripts-FlashbackPresentation.HecateFlashback02Exit ...

function game.HecateHideAndSeekExit(a, b) end
---@alias game-Scripts-FlashbackPresentation.HecateHideAndSeekExit ...

function game.HecateHideAndSeekHint(a, b) end
---@alias game-Scripts-FlashbackPresentation.HecateHideAndSeekHint ...

function game.NightmareScreenEffects(a, b) end
---@alias game-Scripts-FlashbackPresentation.NightmareScreenEffects ...

function game.SetupFlashback01(a, b) end
---@alias game-Scripts-FlashbackPresentation.SetupFlashback01 ...

function game.SetupFlashback02(a, b) end
---@alias game-Scripts-FlashbackPresentation.SetupFlashback02 ...

function game.SetupFlashback02_DeathArea(a, b) end
---@alias game-Scripts-FlashbackPresentation.SetupFlashback02_DeathArea ...

function game.SetupFlashback03(a, b) end
---@alias game-Scripts-FlashbackPresentation.SetupFlashback03 ...

function game.SetupFlashbackMusic(a, b) end
---@alias game-Scripts-FlashbackPresentation.SetupFlashbackMusic ...

function game.SetupFlashbackPlayerUnitChronos(a, b) end
---@alias game-Scripts-FlashbackPresentation.SetupFlashbackPlayerUnitChronos ...

function game.SetupFlashbackPlayerUnitHades(a, b) end
---@alias game-Scripts-FlashbackPresentation.SetupFlashbackPlayerUnitHades ...

function game.SetupFlashbackPlayerUnitMel(a, b) end
---@alias game-Scripts-FlashbackPresentation.SetupFlashbackPlayerUnitMel ...

function game.ShowMemorySequence() end
---@alias game-Scripts-FlashbackPresentation.ShowMemorySequence ...

function game.StopHadesFlashbackSpeech(a, b) end
---@alias game-Scripts-FlashbackPresentation.StopHadesFlashbackSpeech ...

function game.UpdateChronosFlashback(a, b) end
---@alias game-Scripts-FlashbackPresentation.UpdateChronosFlashback ...

function game.UpdateHubMainFlashback(a, b) end
---@alias game-Scripts-FlashbackPresentation.UpdateHubMainFlashback ...

return game