---@meta game-Scripts-GameStatsLogic
local game = {}

function game.CloseGameStatsScreen(a, b) end
---@alias game-Scripts-GameStatsLogic.CloseGameStatsScreen ...

function game.GameStatsChangeSortMode(a, b) end
---@alias game-Scripts-GameStatsLogic.GameStatsChangeSortMode ...

function game.GameStatsCreateEntryTextbox(a, b, c) end
---@alias game-Scripts-GameStatsLogic.GameStatsCreateEntryTextbox ...

function game.GameStatsNextCategory(a, b) end
---@alias game-Scripts-GameStatsLogic.GameStatsNextCategory ...

function game.GameStatsPrevCategory(a, b) end
---@alias game-Scripts-GameStatsLogic.GameStatsPrevCategory ...

function game.GameStatsScreenCreateCategories(a) end
---@alias game-Scripts-GameStatsLogic.GameStatsScreenCreateCategories ...

function game.GameStatsScreenSort(a, b) end
---@alias game-Scripts-GameStatsLogic.GameStatsScreenSort ...

function game.GameStatsScrollDown(a, b) end
---@alias game-Scripts-GameStatsLogic.GameStatsScrollDown ...

function game.GameStatsScrollUp(a, b) end
---@alias game-Scripts-GameStatsLogic.GameStatsScrollUp ...

function game.GameStatsSelectCategory(a, b) end
---@alias game-Scripts-GameStatsLogic.GameStatsSelectCategory ...

function game.GameStatsUpdateVisibility(a) end
---@alias game-Scripts-GameStatsLogic.GameStatsUpdateVisibility ...

function game.OpenGameStatsScreen(a) end
---@alias game-Scripts-GameStatsLogic.OpenGameStatsScreen ...

function game.PassesTraitFilter(a, b) end
---@alias game-Scripts-GameStatsLogic.PassesTraitFilter ...

function game.ShowTraitStats(a) end
---@alias game-Scripts-GameStatsLogic.ShowTraitStats ...

function game.UseGameStatsScreenObject(a, b) end
---@alias game-Scripts-GameStatsLogic.UseGameStatsScreenObject ...

return game