---@meta game-Scripts-HarvestLogic
local game = {}

function game.ActivateHarvestPointBase(a) end
---@alias game-Scripts-HarvestLogic.ActivateHarvestPointBase ...

function game.AutoHarvestOnExit() end
---@alias game-Scripts-HarvestLogic.AutoHarvestOnExit ...

function game.BeginFamiliarHarvestInvulnerability() end
---@alias game-Scripts-HarvestLogic.BeginFamiliarHarvestInvulnerability ...

function game.CancelFishing() end
---@alias game-Scripts-HarvestLogic.CancelFishing ...

function game.EndFamiliarHarvestInvulnerability() end
---@alias game-Scripts-HarvestLogic.EndFamiliarHarvestInvulnerability ...

function game.ExorcismGenerateMoveSequence(a) end
---@alias game-Scripts-HarvestLogic.ExorcismGenerateMoveSequence ...

function game.ExorcismPointUseCanceled(a, b) end
---@alias game-Scripts-HarvestLogic.ExorcismPointUseCanceled ...

function game.ExorcismSequence(a, b, c, d) end
---@alias game-Scripts-HarvestLogic.ExorcismSequence ...

function game.FishingSequence(a, b) end
---@alias game-Scripts-HarvestLogic.FishingSequence ...

function game.GetCaughtFishName(a) end
---@alias game-Scripts-HarvestLogic.GetCaughtFishName ...

function game.GetCurrentFishingBiomeName() end
---@alias game-Scripts-HarvestLogic.GetCurrentFishingBiomeName ...

function game.GetHarvestPointSpawnChance(a, b) end
---@alias game-Scripts-HarvestLogic.GetHarvestPointSpawnChance ...

function game.GrantElementFromTool(a, b) end
---@alias game-Scripts-HarvestLogic.GrantElementFromTool ...

function game.HarvestPointUseCanceled(a, b) end
---@alias game-Scripts-HarvestLogic.HarvestPointUseCanceled ...

function game.IsAggroedUnitBlockingHarvest() end
---@alias game-Scripts-HarvestLogic.IsAggroedUnitBlockingHarvest ...

function game.IsComplexHarvestAllowed() end
---@alias game-Scripts-HarvestLogic.IsComplexHarvestAllowed ...

function game.PickaxePointUseCanceled(a, b) end
---@alias game-Scripts-HarvestLogic.PickaxePointUseCanceled ...

function game.SetupHarvestPoints(a, b) end
---@alias game-Scripts-HarvestLogic.SetupHarvestPoints ...

function game.ShovelPointUseCanceled(a, b) end
---@alias game-Scripts-HarvestLogic.ShovelPointUseCanceled ...

function game.StartFishing(a, b) end
---@alias game-Scripts-HarvestLogic.StartFishing ...

function game.UseDarknessOnExit(a, b, c) end
---@alias game-Scripts-HarvestLogic.UseDarknessOnExit ...

function game.UseExorcismPoint(a, b, c) end
---@alias game-Scripts-HarvestLogic.UseExorcismPoint ...

function game.UseExorcismPointOnExit(a, b, c) end
---@alias game-Scripts-HarvestLogic.UseExorcismPointOnExit ...

function game.UseFishingPoint(a, b, c) end
---@alias game-Scripts-HarvestLogic.UseFishingPoint ...

function game.UseFishingPointOnExit(a, b, c) end
---@alias game-Scripts-HarvestLogic.UseFishingPointOnExit ...

function game.UseHarvestPoint(a, b, c) end
---@alias game-Scripts-HarvestLogic.UseHarvestPoint ...

function game.UseHarvestPointOnExit(a, b, c) end
---@alias game-Scripts-HarvestLogic.UseHarvestPointOnExit ...

function game.UsePickaxePoint(a, b, c) end
---@alias game-Scripts-HarvestLogic.UsePickaxePoint ...

function game.UsePickaxePointOnExit(a, b, c) end
---@alias game-Scripts-HarvestLogic.UsePickaxePointOnExit ...

function game.UseShovelPoint(a, b, c) end
---@alias game-Scripts-HarvestLogic.UseShovelPoint ...

function game.UseShovelPointOnExit(a, b, c) end
---@alias game-Scripts-HarvestLogic.UseShovelPointOnExit ...

function game.WaitForFishingInput(a) end
---@alias game-Scripts-HarvestLogic.WaitForFishingInput ...

return game