---@meta game-Scripts-HarvestPresentation
local game = {}

function game.BackPlayerUpForHarvest(a, b, c) end
---@alias game-Scripts-HarvestPresentation.BackPlayerUpForHarvest ...

function game.ExorcismFailPresentation(a, b, c, d) end
---@alias game-Scripts-HarvestPresentation.ExorcismFailPresentation ...

function game.ExorcismGhostDissipate(a) end
---@alias game-Scripts-HarvestPresentation.ExorcismGhostDissipate ...

function game.ExorcismGhostEmotePresentation(a) end
---@alias game-Scripts-HarvestPresentation.ExorcismGhostEmotePresentation ...

function game.ExorcismInputCheckPresentation(a, b, c, d, e, f, g, h, i, j) end
---@alias game-Scripts-HarvestPresentation.ExorcismInputCheckPresentation ...

function game.ExorcismNextMovePresentation(a, b, c, d) end
---@alias game-Scripts-HarvestPresentation.ExorcismNextMovePresentation ...

function game.ExorcismPointChosenPresentation(a) end
---@alias game-Scripts-HarvestPresentation.ExorcismPointChosenPresentation ...

function game.ExorcismPointGetUseText(a) end
---@alias game-Scripts-HarvestPresentation.ExorcismPointGetUseText ...

function game.ExorcismStartPresentation(a, b, c) end
---@alias game-Scripts-HarvestPresentation.ExorcismStartPresentation ...

function game.ExorcismSuccessPresentation(a, b, c) end
---@alias game-Scripts-HarvestPresentation.ExorcismSuccessPresentation ...

function game.FamiliarExorcismStartPresentation(a, b, c) end
---@alias game-Scripts-HarvestPresentation.FamiliarExorcismStartPresentation ...

function game.FamiliarFishingPresentation(a) end
---@alias game-Scripts-HarvestPresentation.FamiliarFishingPresentation ...

function game.FamiliarHarvestStartPresentation(a, b, c) end
---@alias game-Scripts-HarvestPresentation.FamiliarHarvestStartPresentation ...

function game.FamiliarPickaxeStartPresentation(a, b, c) end
---@alias game-Scripts-HarvestPresentation.FamiliarPickaxeStartPresentation ...

function game.FamiliarShovelStartPresentation(a, b, c) end
---@alias game-Scripts-HarvestPresentation.FamiliarShovelStartPresentation ...

function game.FishingCaughtPresentation(a, b) end
---@alias game-Scripts-HarvestPresentation.FishingCaughtPresentation ...

function game.FishingEndPresentation(a, b, c) end
---@alias game-Scripts-HarvestPresentation.FishingEndPresentation ...

function game.FishingInProgressPresentation() end
---@alias game-Scripts-HarvestPresentation.FishingInProgressPresentation ...

function game.FishingPointGetUseText(a) end
---@alias game-Scripts-HarvestPresentation.FishingPointGetUseText ...

function game.FishingReadyForInputPresentation(a) end
---@alias game-Scripts-HarvestPresentation.FishingReadyForInputPresentation ...

function game.FishingStartPresentation(a, b) end
---@alias game-Scripts-HarvestPresentation.FishingStartPresentation ...

function game.GiftActivityFishingEndPresentation(a, b) end
---@alias game-Scripts-HarvestPresentation.GiftActivityFishingEndPresentation ...

function game.GiftActivityFishingStartPresentation(a, b) end
---@alias game-Scripts-HarvestPresentation.GiftActivityFishingStartPresentation ...

function game.HarvestBlockedPresentation(a, b) end
---@alias game-Scripts-HarvestPresentation.HarvestBlockedPresentation ...

function game.HarvestEndPresentation(a, b, c) end
---@alias game-Scripts-HarvestPresentation.HarvestEndPresentation ...

function game.HarvestNoToolPresentation(a, b, c, d) end
---@alias game-Scripts-HarvestPresentation.HarvestNoToolPresentation ...

function game.HarvestStartPresentation(a, b, c) end
---@alias game-Scripts-HarvestPresentation.HarvestStartPresentation ...

function game.PickaxeDepositDamagedPresentation(a, b, c) end
---@alias game-Scripts-HarvestPresentation.PickaxeDepositDamagedPresentation ...

function game.PickaxeDepositDestroyedPresentation(a, b) end
---@alias game-Scripts-HarvestPresentation.PickaxeDepositDestroyedPresentation ...

function game.PickaxeStartPresentation(a, b, c) end
---@alias game-Scripts-HarvestPresentation.PickaxeStartPresentation ...

function game.PulseExorcismIcon(a, b) end
---@alias game-Scripts-HarvestPresentation.PulseExorcismIcon ...

function game.ShovelEndPresentation(a, b, c) end
---@alias game-Scripts-HarvestPresentation.ShovelEndPresentation ...

function game.ShovelPointBombPresentation(a, b, c) end
---@alias game-Scripts-HarvestPresentation.ShovelPointBombPresentation ...

function game.ShovelStartPresentation(a, b, c) end
---@alias game-Scripts-HarvestPresentation.ShovelStartPresentation ...

function game.UsedFishingPointOnExitPresentation(a) end
---@alias game-Scripts-HarvestPresentation.UsedFishingPointOnExitPresentation ...

function game.UsedHarvestPointPresentation(a, b, c) end
---@alias game-Scripts-HarvestPresentation.UsedHarvestPointPresentation ...

function game.UsedShovelPointOnExitPresentation(a) end
---@alias game-Scripts-HarvestPresentation.UsedShovelPointOnExitPresentation ...

function game.UsedTrashPointPresentation(a, b, c) end
---@alias game-Scripts-HarvestPresentation.UsedTrashPointPresentation ...

return game