---@meta game-Scripts-HubPresentation
local game = {}

function game.ActivateHubAquarium(a) end
---@alias game-Scripts-HubPresentation.ActivateHubAquarium ...

function game.AltarEnterPresentation(a, b) end
---@alias game-Scripts-HubPresentation.AltarEnterPresentation ...

function game.AltarExitPresentation(a, b) end
---@alias game-Scripts-HubPresentation.AltarExitPresentation ...

function game.AltTavernaStartPresentation(a, b) end
---@alias game-Scripts-HubPresentation.AltTavernaStartPresentation ...

function game.BadgeSellerReaction(a) end
---@alias game-Scripts-HubPresentation.BadgeSellerReaction ...

function game.BathHouseEndPresentation(a, b) end
---@alias game-Scripts-HubPresentation.BathHouseEndPresentation ...

function game.BathHouseQuipPresentation(a, b, c) end
---@alias game-Scripts-HubPresentation.BathHouseQuipPresentation ...

function game.BathHouseStartPresentation(a, b, c) end
---@alias game-Scripts-HubPresentation.BathHouseStartPresentation ...

function game.BecomingCloserErisPresentation(a, b) end
---@alias game-Scripts-HubPresentation.BecomingCloserErisPresentation ...

function game.BecomingCloserErisRepeatablePresentation(a, b) end
---@alias game-Scripts-HubPresentation.BecomingCloserErisRepeatablePresentation ...

function game.BecomingCloserIcarusPresentation(a, b) end
---@alias game-Scripts-HubPresentation.BecomingCloserIcarusPresentation ...

function game.BecomingCloserIcarusRepeatablePresentation(a, b) end
---@alias game-Scripts-HubPresentation.BecomingCloserIcarusRepeatablePresentation ...

function game.BecomingCloserMorosPresentation(a, b) end
---@alias game-Scripts-HubPresentation.BecomingCloserMorosPresentation ...

function game.BecomingCloserMorosRepeatablePresentation(a, b) end
---@alias game-Scripts-HubPresentation.BecomingCloserMorosRepeatablePresentation ...

function game.BecomingCloserNemesisPresentation(a, b) end
---@alias game-Scripts-HubPresentation.BecomingCloserNemesisPresentation ...

function game.BecomingCloserNemesisRepeatablePresentation(a, b) end
---@alias game-Scripts-HubPresentation.BecomingCloserNemesisRepeatablePresentation ...

function game.BecomingCloserPresentation(a, b) end
---@alias game-Scripts-HubPresentation.BecomingCloserPresentation ...

function game.BlockHubExitForNarrative(a, b) end
---@alias game-Scripts-HubPresentation.BlockHubExitForNarrative ...

function game.BountyBoardReturnPresentationEnd() end
---@alias game-Scripts-HubPresentation.BountyBoardReturnPresentationEnd ...

function game.BountyBoardUnlockedFirstPresentation(a, b) end
---@alias game-Scripts-HubPresentation.BountyBoardUnlockedFirstPresentation ...

function game.CauldronAssistCompletePresentation(a, b) end
---@alias game-Scripts-HubPresentation.CauldronAssistCompletePresentation ...

function game.CauldronCastingJoinInVoiceLines(a, b) end
---@alias game-Scripts-HubPresentation.CauldronCastingJoinInVoiceLines ...

function game.CauldronCastingPresentation(a, b) end
---@alias game-Scripts-HubPresentation.CauldronCastingPresentation ...

function game.CauldronCastingVoiceLines(a, b) end
---@alias game-Scripts-HubPresentation.CauldronCastingVoiceLines ...

function game.CauldronPresentationBurst() end
---@alias game-Scripts-HubPresentation.CauldronPresentationBurst ...

function game.CauldronPresentationRing() end
---@alias game-Scripts-HubPresentation.CauldronPresentationRing ...

function game.CauldronWitchcraftPresentation(a, b) end
---@alias game-Scripts-HubPresentation.CauldronWitchcraftPresentation ...

function game.CenterInteractRange(a, b) end
---@alias game-Scripts-HubPresentation.CenterInteractRange ...

function game.CloseWeaponUpgradeScreenPresentation(a) end
---@alias game-Scripts-HubPresentation.CloseWeaponUpgradeScreenPresentation ...

function game.DeactivateHubAquarium(a) end
---@alias game-Scripts-HubPresentation.DeactivateHubAquarium ...

function game.DeathAreaAttackFailPresentation(a, b) end
---@alias game-Scripts-HubPresentation.DeathAreaAttackFailPresentation ...

function game.DoraCheckForNewItems(a, b) end
---@alias game-Scripts-HubPresentation.DoraCheckForNewItems ...

function game.DoraStartDissipate(a, b) end
---@alias game-Scripts-HubPresentation.DoraStartDissipate ...

function game.DoraStartHaunting(a, b) end
---@alias game-Scripts-HubPresentation.DoraStartHaunting ...

function game.DoraStopDissipate(a, b) end
---@alias game-Scripts-HubPresentation.DoraStopDissipate ...

function game.DoraStopHaunting(a) end
---@alias game-Scripts-HubPresentation.DoraStopHaunting ...

function game.DoraTeleportExit(a, b) end
---@alias game-Scripts-HubPresentation.DoraTeleportExit ...

function game.DoraTeleportHub(a) end
---@alias game-Scripts-HubPresentation.DoraTeleportHub ...

function game.EndFixedDashPresentationValues() end
---@alias game-Scripts-HubPresentation.EndFixedDashPresentationValues ...

function game.EndOverlookAdvanced(a, b) end
---@alias game-Scripts-HubPresentation.EndOverlookAdvanced ...

function game.EnterHubRoomPresentation(a, b) end
---@alias game-Scripts-HubPresentation.EnterHubRoomPresentation ...

function game.ErisExitPresentation(a, b) end
---@alias game-Scripts-HubPresentation.ErisExitPresentation ...

function game.EstablishConversationStartingPoint(a, b) end
---@alias game-Scripts-HubPresentation.EstablishConversationStartingPoint ...

function game.FadeBackgroundForestIn() end
---@alias game-Scripts-HubPresentation.FadeBackgroundForestIn ...

function game.FadeBackgroundForestOut() end
---@alias game-Scripts-HubPresentation.FadeBackgroundForestOut ...

function game.FamiliarPointsGiftedPresentation(a) end
---@alias game-Scripts-HubPresentation.FamiliarPointsGiftedPresentation ...

function game.FishingPierEndPresentation(a, b) end
---@alias game-Scripts-HubPresentation.FishingPierEndPresentation ...

function game.FishingPierStartPresentation(a, b) end
---@alias game-Scripts-HubPresentation.FishingPierStartPresentation ...

function game.GetRandomMelBecomingCloserSound(a, b) end
---@alias game-Scripts-HubPresentation.GetRandomMelBecomingCloserSound ...

function game.GhostEavesdroppers(a, b) end
---@alias game-Scripts-HubPresentation.GhostEavesdroppers ...

function game.GhostFollowerAI(a, b) end
---@alias game-Scripts-HubPresentation.GhostFollowerAI ...

function game.GhostFollowerGainAggroPresentation(a, b) end
---@alias game-Scripts-HubPresentation.GhostFollowerGainAggroPresentation ...

function game.GhostFollowerLoseAggroPresentation(a, b) end
---@alias game-Scripts-HubPresentation.GhostFollowerLoseAggroPresentation ...

function game.GhostFollowers(a, b) end
---@alias game-Scripts-HubPresentation.GhostFollowers ...

function game.GoSomeplaceStartPresentation(a, b) end
---@alias game-Scripts-HubPresentation.GoSomeplaceStartPresentation ...

function game.HubEastSideEnterPresentation(a, b) end
---@alias game-Scripts-HubPresentation.HubEastSideEnterPresentation ...

function game.HubPostBountyStartPresentation(a) end
---@alias game-Scripts-HubPresentation.HubPostBountyStartPresentation ...

function game.HubPostCreditsStartPresentation(a, b) end
---@alias game-Scripts-HubPresentation.HubPostCreditsStartPresentation ...

function game.HubPostDreamStartPresentation(a) end
---@alias game-Scripts-HubPresentation.HubPostDreamStartPresentation ...

function game.HubPostStoryResetStartPresentation(a, b) end
---@alias game-Scripts-HubPresentation.HubPostStoryResetStartPresentation ...

function game.HubWestSideEnterPresentation(a, b) end
---@alias game-Scripts-HubPresentation.HubWestSideEnterPresentation ...

function game.HypnosCutoutHit(a, b) end
---@alias game-Scripts-HubPresentation.HypnosCutoutHit ...

function game.HypnosDream01EndPresentation(a, b) end
---@alias game-Scripts-HubPresentation.HypnosDream01EndPresentation ...

function game.HypnosDream01StartPresentation(a, b) end
---@alias game-Scripts-HubPresentation.HypnosDream01StartPresentation ...

function game.HypnosDream02StartPresentation(a, b) end
---@alias game-Scripts-HubPresentation.HypnosDream02StartPresentation ...

function game.HypnosDream03StartPresentation(a, b) end
---@alias game-Scripts-HubPresentation.HypnosDream03StartPresentation ...

function game.HypnosExitPresentation(a, b) end
---@alias game-Scripts-HubPresentation.HypnosExitPresentation ...

function game.IcarusHubExitPresentation(a, b) end
---@alias game-Scripts-HubPresentation.IcarusHubExitPresentation ...

function game.LearnedSageReaction(a) end
---@alias game-Scripts-HubPresentation.LearnedSageReaction ...

function game.LeaveHubRoomPresentation(a, b) end
---@alias game-Scripts-HubPresentation.LeaveHubRoomPresentation ...

function game.LimitGraspShrineUpgradeEscapeDoorClosed(a, b) end
---@alias game-Scripts-HubPresentation.LimitGraspShrineUpgradeEscapeDoorClosed ...

function game.LockedSurfaceRunPresentation(a, b) end
---@alias game-Scripts-HubPresentation.LockedSurfaceRunPresentation ...

function game.LoungeRevelryPresentation(a, b) end
---@alias game-Scripts-HubPresentation.LoungeRevelryPresentation ...

function game.MelFootDrop() end
---@alias game-Scripts-HubPresentation.MelFootDrop ...

function game.MelReadyFlash() end
---@alias game-Scripts-HubPresentation.MelReadyFlash ...

function game.MusicMakerReaction(a) end
---@alias game-Scripts-HubPresentation.MusicMakerReaction ...

function game.NyxExitPresentation(a) end
---@alias game-Scripts-HubPresentation.NyxExitPresentation ...

function game.OdysseusArriveAtGardenPlot(a, b, c) end
---@alias game-Scripts-HubPresentation.OdysseusArriveAtGardenPlot ...

function game.OdysseusArriveAtShade(a, b, c) end
---@alias game-Scripts-HubPresentation.OdysseusArriveAtShade ...

function game.OdysseusArriveAtTable(a, b, c) end
---@alias game-Scripts-HubPresentation.OdysseusArriveAtTable ...

function game.OdysseusAtTaverna(a, b) end
---@alias game-Scripts-HubPresentation.OdysseusAtTaverna ...

function game.OncePerRunTentExitPresentation(a, b) end
---@alias game-Scripts-HubPresentation.OncePerRunTentExitPresentation ...

function game.OverlookAdvanced(a, b) end
---@alias game-Scripts-HubPresentation.OverlookAdvanced ...

function game.PlayHadesTheme(a, b) end
---@alias game-Scripts-HubPresentation.PlayHadesTheme ...

function game.PostBossFirstFloorPresentation(a, b) end
---@alias game-Scripts-HubPresentation.PostBossFirstFloorPresentation ...

function game.PostBossSecondFloorPresentation(a, b) end
---@alias game-Scripts-HubPresentation.PostBossSecondFloorPresentation ...

function game.PostRevealTavernaPresentation(a) end
---@alias game-Scripts-HubPresentation.PostRevealTavernaPresentation ...

function game.PreOpenWeaponUpgradeScreenPresentation(a) end
---@alias game-Scripts-HubPresentation.PreOpenWeaponUpgradeScreenPresentation ...

function game.PreRunBacktrackHintPresentation(a, b, c) end
---@alias game-Scripts-HubPresentation.PreRunBacktrackHintPresentation ...

function game.PreRunBacktrackHintPresentationEnd() end
---@alias game-Scripts-HubPresentation.PreRunBacktrackHintPresentationEnd ...

function game.PreRunCameraPresentation(a, b) end
---@alias game-Scripts-HubPresentation.PreRunCameraPresentation ...

function game.PreRunCameraPresentationEnd() end
---@alias game-Scripts-HubPresentation.PreRunCameraPresentationEnd ...

function game.RecordKeeperReaction(a) end
---@alias game-Scripts-HubPresentation.RecordKeeperReaction ...

function game.RevealBathHousePresentation(a) end
---@alias game-Scripts-HubPresentation.RevealBathHousePresentation ...

function game.RevealFishingPointPresentation(a) end
---@alias game-Scripts-HubPresentation.RevealFishingPointPresentation ...

function game.RevealTavernaPresentation(a) end
---@alias game-Scripts-HubPresentation.RevealTavernaPresentation ...

function game.RiverGhostPresentation(a, b) end
---@alias game-Scripts-HubPresentation.RiverGhostPresentation ...

function game.SetFixedDashPresentationValues() end
---@alias game-Scripts-HubPresentation.SetFixedDashPresentationValues ...

function game.SetupArachneDangling(a, b) end
---@alias game-Scripts-HubPresentation.SetupArachneDangling ...

function game.SetupCauldronWitchcraftPresentation(a, b) end
---@alias game-Scripts-HubPresentation.SetupCauldronWitchcraftPresentation ...

function game.SetupErisWarningSignCosmetic(a, b) end
---@alias game-Scripts-HubPresentation.SetupErisWarningSignCosmetic ...

function game.SetupErisWarningSignCosmeticThread(a, b) end
---@alias game-Scripts-HubPresentation.SetupErisWarningSignCosmeticThread ...

function game.SetupLockedGiftRack(a) end
---@alias game-Scripts-HubPresentation.SetupLockedGiftRack ...

function game.SetupStoryResetObject() end
---@alias game-Scripts-HubPresentation.SetupStoryResetObject ...

function game.ShadeSignSway(a, b) end
---@alias game-Scripts-HubPresentation.ShadeSignSway ...

function game.ShrineReturnPresentationEnd() end
---@alias game-Scripts-HubPresentation.ShrineReturnPresentationEnd ...

function game.ShrineUnlockedFirstPresentation(a, b) end
---@alias game-Scripts-HubPresentation.ShrineUnlockedFirstPresentation ...

function game.SkellyBackstoryPresentationEnd() end
---@alias game-Scripts-HubPresentation.SkellyBackstoryPresentationEnd ...

function game.SkellyBackstoryPresentationStart() end
---@alias game-Scripts-HubPresentation.SkellyBackstoryPresentationStart ...

function game.SkellyHitQuestCompletePresentation(a) end
---@alias game-Scripts-HubPresentation.SkellyHitQuestCompletePresentation ...

function game.SpecialInteractChangeNextRunRNG(a, b) end
---@alias game-Scripts-HubPresentation.SpecialInteractChangeNextRunRNG ...

function game.StartDeathLoopPresentation(a) end
---@alias game-Scripts-HubPresentation.StartDeathLoopPresentation ...

function game.StartNewRunPresentation(a, b) end
---@alias game-Scripts-HubPresentation.StartNewRunPresentation ...

function game.TavernaClearedRunPresentation(a) end
---@alias game-Scripts-HubPresentation.TavernaClearedRunPresentation ...

function game.TavernaEndPresentation(a, b) end
---@alias game-Scripts-HubPresentation.TavernaEndPresentation ...

function game.TavernaStartPresentation(a, b) end
---@alias game-Scripts-HubPresentation.TavernaStartPresentation ...

function game.TechTestEscapeDoorClosed(a, b) end
---@alias game-Scripts-HubPresentation.TechTestEscapeDoorClosed ...

function game.TeleportDoraForIncantation(a) end
---@alias game-Scripts-HubPresentation.TeleportDoraForIncantation ...

function game.TeleportToConversationStartingPoint(a, b) end
---@alias game-Scripts-HubPresentation.TeleportToConversationStartingPoint ...

function game.TentEnterPresentation(a, b) end
---@alias game-Scripts-HubPresentation.TentEnterPresentation ...

function game.TentExitPresentation(a, b) end
---@alias game-Scripts-HubPresentation.TentExitPresentation ...

function game.TimePassesFishingSFX(a, b) end
---@alias game-Scripts-HubPresentation.TimePassesFishingSFX ...

function game.TimePassesPresentation(a, b) end
---@alias game-Scripts-HubPresentation.TimePassesPresentation ...

function game.TrophyQuestReturnPresentationEnd() end
---@alias game-Scripts-HubPresentation.TrophyQuestReturnPresentationEnd ...

function game.TrophyQuestUnlockedFirstPresentation(a, b) end
---@alias game-Scripts-HubPresentation.TrophyQuestUnlockedFirstPresentation ...

function game.UnblockHubExitForNarrative() end
---@alias game-Scripts-HubPresentation.UnblockHubExitForNarrative ...

function game.UpdateEscapeDoorForLimitGraspShrineUpgrade(a, b) end
---@alias game-Scripts-HubPresentation.UpdateEscapeDoorForLimitGraspShrineUpgrade ...

function game.UpdateFamilyPortraitVisibility(a, b) end
---@alias game-Scripts-HubPresentation.UpdateFamilyPortraitVisibility ...

function game.UseAquariumPresentation(a) end
---@alias game-Scripts-HubPresentation.UseAquariumPresentation ...

function game.UseArtemisJoinSong(a, b) end
---@alias game-Scripts-HubPresentation.UseArtemisJoinSong ...

function game.UseCauldronJoinWitchcraft(a, b, c) end
---@alias game-Scripts-HubPresentation.UseCauldronJoinWitchcraft ...

function game.UseDreamCertificate(a, b) end
---@alias game-Scripts-HubPresentation.UseDreamCertificate ...

function game.UseExorcisedGhostsPreRun(a, b, c) end
---@alias game-Scripts-HubPresentation.UseExorcisedGhostsPreRun ...

function game.UseGhostEavesdropper(a, b, c) end
---@alias game-Scripts-HubPresentation.UseGhostEavesdropper ...

function game.UseHadesFountain(a, b) end
---@alias game-Scripts-HubPresentation.UseHadesFountain ...

function game.UseHypnosStatue(a, b) end
---@alias game-Scripts-HubPresentation.UseHypnosStatue ...

function game.UseLockedSystemObjectPresentation(a, b) end
---@alias game-Scripts-HubPresentation.UseLockedSystemObjectPresentation ...

function game.UseStarJar(a, b) end
---@alias game-Scripts-HubPresentation.UseStarJar ...

function game.UseSunMoonTimeSculpture(a, b) end
---@alias game-Scripts-HubPresentation.UseSunMoonTimeSculpture ...

function game.UseZagreusStatue(a, b) end
---@alias game-Scripts-HubPresentation.UseZagreusStatue ...

function game.ViewPortraitPresentation(a, b) end
---@alias game-Scripts-HubPresentation.ViewPortraitPresentation ...

function game.WaitForEndOverlookAdvancedInput(a, b, c) end
---@alias game-Scripts-HubPresentation.WaitForEndOverlookAdvancedInput ...

function game.WeaponKitSpecialInteractPresentation(a, b, c) end
---@alias game-Scripts-HubPresentation.WeaponKitSpecialInteractPresentation ...

function game.WretchedBrokerFlashbackReaction(a) end
---@alias game-Scripts-HubPresentation.WretchedBrokerFlashbackReaction ...

function game.WretchedBrokerReaction(a) end
---@alias game-Scripts-HubPresentation.WretchedBrokerReaction ...

return game