---@meta game-Scripts-HUDLogic
local game = {}

function game.ActivateTraitAfterDelay(a, b) end
---@alias game-Scripts-HUDLogic.ActivateTraitAfterDelay ...

function game.CreateLifePip(a) end
---@alias game-Scripts-HUDLogic.CreateLifePip ...

function game.GetExistingUITrait(a) end
---@alias game-Scripts-HUDLogic.GetExistingUITrait ...

function game.GetExistingUITraitName(a) end
---@alias game-Scripts-HUDLogic.GetExistingUITraitName ...

function game.GetTraitFrame(a) end
---@alias game-Scripts-HUDLogic.GetTraitFrame ...

function game.GetTraitIcon(a) end
---@alias game-Scripts-HUDLogic.GetTraitIcon ...

function game.GetTraitTooltip(a, b) end
---@alias game-Scripts-HUDLogic.GetTraitTooltip ...

function game.GetTraitTooltipTitle(a) end
---@alias game-Scripts-HUDLogic.GetTraitTooltipTitle ...

function game.HideAfterDelay() end
---@alias game-Scripts-HUDLogic.HideAfterDelay ...

function game.HideAmmoUI(a) end
---@alias game-Scripts-HUDLogic.HideAmmoUI ...

function game.HideAxeUI(a) end
---@alias game-Scripts-HUDLogic.HideAxeUI ...

function game.HideCombatUI(a, b) end
---@alias game-Scripts-HUDLogic.HideCombatUI ...

function game.HideDaggerUI(a) end
---@alias game-Scripts-HUDLogic.HideDaggerUI ...

function game.HideHealthUI(a) end
---@alias game-Scripts-HUDLogic.HideHealthUI ...

function game.HideLobUI(a) end
---@alias game-Scripts-HUDLogic.HideLobUI ...

function game.HideManaMeter(a) end
---@alias game-Scripts-HUDLogic.HideManaMeter ...

function game.HideMoneyUI(a) end
---@alias game-Scripts-HUDLogic.HideMoneyUI ...

function game.HideRerollUI(a) end
---@alias game-Scripts-HUDLogic.HideRerollUI ...

function game.HideResourceUIs(a) end
---@alias game-Scripts-HUDLogic.HideResourceUIs ...

function game.HideSuitUI(a) end
---@alias game-Scripts-HUDLogic.HideSuitUI ...

function game.HideTraitUI(a) end
---@alias game-Scripts-HUDLogic.HideTraitUI ...

function game.HUDHideTrait(a, b) end
---@alias game-Scripts-HUDLogic.HUDHideTrait ...

function game.HUDShowTrait(a, b) end
---@alias game-Scripts-HUDLogic.HUDShowTrait ...

function game.IsExistingTraitShown(a) end
---@alias game-Scripts-HUDLogic.IsExistingTraitShown ...

function game.IsHealthHidden() end
---@alias game-Scripts-HUDLogic.IsHealthHidden ...

function game.RecreateLifePips() end
---@alias game-Scripts-HUDLogic.RecreateLifePips ...

function game.ResetUI() end
---@alias game-Scripts-HUDLogic.ResetUI ...

function game.ShowAmmoUI(a) end
---@alias game-Scripts-HUDLogic.ShowAmmoUI ...

function game.ShowAxeUI() end
---@alias game-Scripts-HUDLogic.ShowAxeUI ...

function game.ShowCombatUI(a, b) end
---@alias game-Scripts-HUDLogic.ShowCombatUI ...

function game.ShowDaggerUI(a) end
---@alias game-Scripts-HUDLogic.ShowDaggerUI ...

function game.ShowHealthUI(a) end
---@alias game-Scripts-HUDLogic.ShowHealthUI ...

function game.ShowLobUI() end
---@alias game-Scripts-HUDLogic.ShowLobUI ...

function game.ShowManaMeter(a) end
---@alias game-Scripts-HUDLogic.ShowManaMeter ...

function game.ShowMoneyUI(a) end
---@alias game-Scripts-HUDLogic.ShowMoneyUI ...

function game.ShowRerollUI(a) end
---@alias game-Scripts-HUDLogic.ShowRerollUI ...

function game.ShowResourceUIs(a) end
---@alias game-Scripts-HUDLogic.ShowResourceUIs ...

function game.ShowSuitUI(a) end
---@alias game-Scripts-HUDLogic.ShowSuitUI ...

function game.ShowTraitUI(a) end
---@alias game-Scripts-HUDLogic.ShowTraitUI ...

function game.StartHideAfterDelayThread() end
---@alias game-Scripts-HUDLogic.StartHideAfterDelayThread ...

function game.TraitUIActivateTrait(a, b) end
---@alias game-Scripts-HUDLogic.TraitUIActivateTrait ...

function game.TraitUIActivateTraits(a) end
---@alias game-Scripts-HUDLogic.TraitUIActivateTraits ...

function game.TraitUIAdd(a, b) end
---@alias game-Scripts-HUDLogic.TraitUIAdd ...

function game.TraitUICreateText(a, b) end
---@alias game-Scripts-HUDLogic.TraitUICreateText ...

function game.TraitUIDeactivateTrait(a) end
---@alias game-Scripts-HUDLogic.TraitUIDeactivateTrait ...

function game.TraitUIRemove(a) end
---@alias game-Scripts-HUDLogic.TraitUIRemove ...

function game.TraitUIUpdateText(a) end
---@alias game-Scripts-HUDLogic.TraitUIUpdateText ...

function game.UnblockCombatUI(a) end
---@alias game-Scripts-HUDLogic.UnblockCombatUI ...

function game.UpdateAmmoUI(a) end
---@alias game-Scripts-HUDLogic.UpdateAmmoUI ...

function game.UpdateAxeUI(a) end
---@alias game-Scripts-HUDLogic.UpdateAxeUI ...

function game.UpdateDaggerUI() end
---@alias game-Scripts-HUDLogic.UpdateDaggerUI ...

function game.UpdateHealthUI(a) end
---@alias game-Scripts-HUDLogic.UpdateHealthUI ...

function game.UpdateLifePips(a) end
---@alias game-Scripts-HUDLogic.UpdateLifePips ...

function game.UpdateLobUI(a) end
---@alias game-Scripts-HUDLogic.UpdateLobUI ...

function game.UpdateManaMeterUI() end
---@alias game-Scripts-HUDLogic.UpdateManaMeterUI ...

function game.UpdateManaMeterUIReal() end
---@alias game-Scripts-HUDLogic.UpdateManaMeterUIReal ...

function game.UpdateMoneyUI(a) end
---@alias game-Scripts-HUDLogic.UpdateMoneyUI ...

function game.UpdateRerollUI(a) end
---@alias game-Scripts-HUDLogic.UpdateRerollUI ...

function game.UpdateSuitUI() end
---@alias game-Scripts-HUDLogic.UpdateSuitUI ...

function game.UpdateTimerDependentTraits() end
---@alias game-Scripts-HUDLogic.UpdateTimerDependentTraits ...

function game.UpdateTraitNumber(a) end
---@alias game-Scripts-HUDLogic.UpdateTraitNumber ...

function game.UpdateTraitSummary(a) end
---@alias game-Scripts-HUDLogic.UpdateTraitSummary ...

return game