---@meta game-Scripts-InteractPresentation
local game = {}

function game.BloodDropUsePresentation(a, b) end
---@alias game-Scripts-InteractPresentation.BloodDropUsePresentation ...

function game.ErisLitterPresentation(a, b) end
---@alias game-Scripts-InteractPresentation.ErisLitterPresentation ...

function game.GetEquippedWeaponValue(a) end
---@alias game-Scripts-InteractPresentation.GetEquippedWeaponValue ...

function game.GhostRecruitSpecialInteractPresentation(a, b) end
---@alias game-Scripts-InteractPresentation.GhostRecruitSpecialInteractPresentation ...

function game.HugHecate(a) end
---@alias game-Scripts-InteractPresentation.HugHecate ...

function game.HugPersephone(a, b) end
---@alias game-Scripts-InteractPresentation.HugPersephone ...

function game.HugZagreus(a, b) end
---@alias game-Scripts-InteractPresentation.HugZagreus ...

function game.LightRangedSalute(a, b) end
---@alias game-Scripts-InteractPresentation.LightRangedSalute ...

function game.ManaDropUsePresentation(a, b) end
---@alias game-Scripts-InteractPresentation.ManaDropUsePresentation ...

function game.NarcissusDropPresentation(a, b) end
---@alias game-Scripts-InteractPresentation.NarcissusDropPresentation ...

function game.NemesisInteractionBlockedPresentation(a, b) end
---@alias game-Scripts-InteractPresentation.NemesisInteractionBlockedPresentation ...

function game.PickupWeaponKitInteractPresentation(a) end
---@alias game-Scripts-InteractPresentation.PickupWeaponKitInteractPresentation ...

function game.PlantAdmirePresentation(a, b) end
---@alias game-Scripts-InteractPresentation.PlantAdmirePresentation ...

function game.PlayInteractAnimation(a, b) end
---@alias game-Scripts-InteractPresentation.PlayInteractAnimation ...

function game.PlayUnequipAnimation(a) end
---@alias game-Scripts-InteractPresentation.PlayUnequipAnimation ...

function game.PreNarrativeUnequipAnimation() end
---@alias game-Scripts-InteractPresentation.PreNarrativeUnequipAnimation ...

function game.RemoveInteractAnimationInputBlock() end
---@alias game-Scripts-InteractPresentation.RemoveInteractAnimationInputBlock ...

function game.SpecialInteractDieHardFanShade(a, b) end
---@alias game-Scripts-InteractPresentation.SpecialInteractDieHardFanShade ...

function game.SpecialInteractDieHardFanShadeSendToElysium(a, b) end
---@alias game-Scripts-InteractPresentation.SpecialInteractDieHardFanShadeSendToElysium ...

function game.SpecialInteractLightRanged(a, b) end
---@alias game-Scripts-InteractPresentation.SpecialInteractLightRanged ...

function game.SpecialInteractSalute(a, b) end
---@alias game-Scripts-InteractPresentation.SpecialInteractSalute ...

function game.SpecialInteractSaluteBroker(a, b) end
---@alias game-Scripts-InteractPresentation.SpecialInteractSaluteBroker ...

function game.SpecialInteractSaluteInterrupt(a, b) end
---@alias game-Scripts-InteractPresentation.SpecialInteractSaluteInterrupt ...

function game.SpecialInteractShade(a, b) end
---@alias game-Scripts-InteractPresentation.SpecialInteractShade ...

function game.SpecialInteractSirenFan(a, b) end
---@alias game-Scripts-InteractPresentation.SpecialInteractSirenFan ...

function game.SpecialInteractThreatenChronos(a, b) end
---@alias game-Scripts-InteractPresentation.SpecialInteractThreatenChronos ...

function game.SpellPotionRefillPresentation(a, b, c, d) end
---@alias game-Scripts-InteractPresentation.SpellPotionRefillPresentation ...

return game