---@meta game-Scripts-KeepsakeLogic
local game = {}

function game.AdvanceKeepsake(a) end
---@alias game-Scripts-KeepsakeLogic.AdvanceKeepsake ...

function game.BlockDeathCanceled(a) end
---@alias game-Scripts-KeepsakeLogic.BlockDeathCanceled ...

function game.CanFreeSwapKeepsakes() end
---@alias game-Scripts-KeepsakeLogic.CanFreeSwapKeepsakes ...

function game.CheckOverTimeManaRefund(a, b) end
---@alias game-Scripts-KeepsakeLogic.CheckOverTimeManaRefund ...

function game.ClearSaveFirstIcon(a, b) end
---@alias game-Scripts-KeepsakeLogic.ClearSaveFirstIcon ...

function game.CreateKeepsakeIcon(a, b, c) end
---@alias game-Scripts-KeepsakeLogic.CreateKeepsakeIcon ...

function game.DamageAfterInterval(a, b) end
---@alias game-Scripts-KeepsakeLogic.DamageAfterInterval ...

function game.EquipKeepsake(a, b, c) end
---@alias game-Scripts-KeepsakeLogic.EquipKeepsake ...

function game.EquipLastAwardTrait(a, b) end
---@alias game-Scripts-KeepsakeLogic.EquipLastAwardTrait ...

function game.GetBlockDeathCurrentEncounter(a, b) end
---@alias game-Scripts-KeepsakeLogic.GetBlockDeathCurrentEncounter ...

function game.GetKeepsakeChambersToNextLevel(a) end
---@alias game-Scripts-KeepsakeLogic.GetKeepsakeChambersToNextLevel ...

function game.GetKeepsakeData(a) end
---@alias game-Scripts-KeepsakeLogic.GetKeepsakeData ...

function game.GetKeepsakeLevel(a, b) end
---@alias game-Scripts-KeepsakeLogic.GetKeepsakeLevel ...

function game.GetKeepsakeProgress(a) end
---@alias game-Scripts-KeepsakeLogic.GetKeepsakeProgress ...

function game.GiftRackEquipRandomKeepsake(a, b) end
---@alias game-Scripts-KeepsakeLogic.GiftRackEquipRandomKeepsake ...

function game.HandleUpgradeToggle(a, b, c) end
---@alias game-Scripts-KeepsakeLogic.HandleUpgradeToggle ...

function game.HasNewTraits() end
---@alias game-Scripts-KeepsakeLogic.HasNewTraits ...

function game.IsFateValid() end
---@alias game-Scripts-KeepsakeLogic.IsFateValid ...

function game.IsKeepsakeMaxed(a) end
---@alias game-Scripts-KeepsakeLogic.IsKeepsakeMaxed ...

function game.KeepsakeAcquireSpellDrop(a, b) end
---@alias game-Scripts-KeepsakeLogic.KeepsakeAcquireSpellDrop ...

function game.KeepsakeAddMaxMana(a) end
---@alias game-Scripts-KeepsakeLogic.KeepsakeAddMaxMana ...

function game.KeepsakeHasHeroicRarity(a) end
---@alias game-Scripts-KeepsakeLogic.KeepsakeHasHeroicRarity ...

function game.KeepsakeScreenClose(a, b) end
---@alias game-Scripts-KeepsakeLogic.KeepsakeScreenClose ...

function game.KeepsakeScreenSaveFirst(a, b) end
---@alias game-Scripts-KeepsakeLogic.KeepsakeScreenSaveFirst ...

function game.KeepsakeScreenShowInfo(a, b) end
---@alias game-Scripts-KeepsakeLogic.KeepsakeScreenShowInfo ...

function game.KeepsakeScreenUpdateActionBar(a, b) end
---@alias game-Scripts-KeepsakeLogic.KeepsakeScreenUpdateActionBar ...

function game.ManaOverTimeRefund(a, b, c, d) end
---@alias game-Scripts-KeepsakeLogic.ManaOverTimeRefund ...

function game.MouseOffKeepsake(a) end
---@alias game-Scripts-KeepsakeLogic.MouseOffKeepsake ...

function game.MouseOverKeepsake(a) end
---@alias game-Scripts-KeepsakeLogic.MouseOverKeepsake ...

function game.OpenKeepsakeRackScreen(a) end
---@alias game-Scripts-KeepsakeLogic.OpenKeepsakeRackScreen ...

function game.PreRunIsFateValid() end
---@alias game-Scripts-KeepsakeLogic.PreRunIsFateValid ...

function game.SetSaveFirstIcon(a, b) end
---@alias game-Scripts-KeepsakeLogic.SetSaveFirstIcon ...

function game.SetSelectedFrame(a, b, c) end
---@alias game-Scripts-KeepsakeLogic.SetSelectedFrame ...

function game.SetupBlockDeathThread() end
---@alias game-Scripts-KeepsakeLogic.SetupBlockDeathThread ...

function game.UnequipKeepsake(a, b, c) end
---@alias game-Scripts-KeepsakeLogic.UnequipKeepsake ...

function game.UpdateFateStatus() end
---@alias game-Scripts-KeepsakeLogic.UpdateFateStatus ...

function game.UpdateGiftRackShineStatus(a) end
---@alias game-Scripts-KeepsakeLogic.UpdateGiftRackShineStatus ...

function game.UseKeepsakeRack(a, b) end
---@alias game-Scripts-KeepsakeLogic.UseKeepsakeRack ...

return game