---@meta game-Scripts-MailboxLogic
local game = {}

function game.CloseMailboxScreen(a, b) end
---@alias game-Scripts-MailboxLogic.CloseMailboxScreen ...

function game.GenerateMailboxItems(a) end
---@alias game-Scripts-MailboxLogic.GenerateMailboxItems ...

function game.HandleCharonPurchase(a, b) end
---@alias game-Scripts-MailboxLogic.HandleCharonPurchase ...

function game.HandleMailboxPurchase(a, b) end
---@alias game-Scripts-MailboxLogic.HandleMailboxPurchase ...

function game.IsMailboxItemInStock(a, b) end
---@alias game-Scripts-MailboxLogic.IsMailboxItemInStock ...

function game.MailboxScreenDisplayCategory(a, b) end
---@alias game-Scripts-MailboxLogic.MailboxScreenDisplayCategory ...

function game.MailboxScreenUpdateResourceStatus(a, b) end
---@alias game-Scripts-MailboxLogic.MailboxScreenUpdateResourceStatus ...

function game.MailboxTimeTick(a) end
---@alias game-Scripts-MailboxLogic.MailboxTimeTick ...

function game.OpenMailboxScreen(a, b) end
---@alias game-Scripts-MailboxLogic.OpenMailboxScreen ...

function game.SetupCharonPoints(a) end
---@alias game-Scripts-MailboxLogic.SetupCharonPoints ...

function game.SetupMailboxStatus(a, b) end
---@alias game-Scripts-MailboxLogic.SetupMailboxStatus ...

function game.ShouldShowMailboxWantsToTalkIndicator(a, b) end
---@alias game-Scripts-MailboxLogic.ShouldShowMailboxWantsToTalkIndicator ...

function game.UpdateMailboxScreenInteractionText(a, b) end
---@alias game-Scripts-MailboxLogic.UpdateMailboxScreenInteractionText ...

function game.UseMailboxDeliveryReady(a, b) end
---@alias game-Scripts-MailboxLogic.UseMailboxDeliveryReady ...

function game.UseMailboxObject(a, b) end
---@alias game-Scripts-MailboxLogic.UseMailboxObject ...

return game