---@meta game-Scripts-Main
local game = {}

game._elapsedTimeMultiplier = 1
---@alias game-Scripts-Main._elapsedTimeMultiplier ...

game._worldTime = 0
---@alias game-Scripts-Main._worldTime ...

game._worldTimeUnmodified = 0
---@alias game-Scripts-Main._worldTimeUnmodified ...

---@class game-Scripts-Main*_coroutinePool

---@type game-Scripts-Main*_coroutinePool
game._coroutinePool = ...
---@alias game-Scripts-Main._coroutinePool ...

---@class game-Scripts-Main*_eventListeners

---@type game-Scripts-Main*_eventListeners
game._eventListeners = ...
---@alias game-Scripts-Main._eventListeners ...

---@class game-Scripts-Main*_events

---@type game-Scripts-Main*_events
game._events = ...
---@alias game-Scripts-Main._events ...

---@class game-Scripts-Main*_eventTimeoutRecord

---@type game-Scripts-Main*_eventTimeoutRecord
game._eventTimeoutRecord = ...
---@alias game-Scripts-Main._eventTimeoutRecord ...

---@class game-Scripts-Main*_tagsToKill

---@type game-Scripts-Main*_tagsToKill
game._tagsToKill = ...
---@alias game-Scripts-Main._tagsToKill ...

---@class game-Scripts-Main*_threads

---@type game-Scripts-Main*_threads
game._threads = ...
---@alias game-Scripts-Main._threads ...

---@class game-Scripts-Main*_workingThreads

---@type game-Scripts-Main*_workingThreads
game._workingThreads = ...
---@alias game-Scripts-Main._workingThreads ...

---@class game-Scripts-Main*NotifyResultsTable

---@type game-Scripts-Main*NotifyResultsTable
game.NotifyResultsTable = ...
---@alias game-Scripts-Main.NotifyResultsTable ...

function game.dispatch(a, b) end
---@alias game-Scripts-Main.dispatch ...

function game.draw(a, b) end
---@alias game-Scripts-Main.draw ...

function game.eat_true(a, ...) end
---@alias game-Scripts-Main.eat_true ...

function game.GetRecursiveTableString(a) end
---@alias game-Scripts-Main.GetRecursiveTableString ...

function game.GetTableString(a, b) end
---@alias game-Scripts-Main.GetTableString ...

function game.HasThread(a) end
---@alias game-Scripts-Main.HasThread ...

function game.HasWaitUntil(a) end
---@alias game-Scripts-Main.HasWaitUntil ...

function game.hurryUpWaitingThreads(a) end
---@alias game-Scripts-Main.hurryUpWaitingThreads ...

function game.KeysToList(a) end
---@alias game-Scripts-Main.KeysToList ...

function game.KillNonPersistentThreads() end
---@alias game-Scripts-Main.KillNonPersistentThreads ...

function game.killTaggedThreads(a) end
---@alias game-Scripts-Main.killTaggedThreads ...

function game.killWaitUntilThreads(a) end
---@alias game-Scripts-Main.killWaitUntilThreads ...

function game.LoadMap(a) end
---@alias game-Scripts-Main.LoadMap ...

function game.ManageThreads(a, b) end
---@alias game-Scripts-Main.ManageThreads ...

function game.NewStack(a) end
---@alias game-Scripts-Main.NewStack ...

function game.notify(a, b) end
---@alias game-Scripts-Main.notify ...

function game.notifyExistingWaiters(a, b) end
---@alias game-Scripts-Main.notifyExistingWaiters ...

function game.OrderedKeysToList(a) end
---@alias game-Scripts-Main.OrderedKeysToList ...

function game.resume(a, b, c, d, e, f, g, h) end
---@alias game-Scripts-Main.resume ...

function game.SetElapsedTimeMultiplier(a, b, c) end
---@alias game-Scripts-Main.SetElapsedTimeMultiplier ...

function game.SetThreadWait(a, b) end
---@alias game-Scripts-Main.SetThreadWait ...

function game.thread(a, b, c, d, e, f, g) end
---@alias game-Scripts-Main.thread ...

function game.ToLookup(a) end
---@alias game-Scripts-Main.ToLookup ...

function game.unpackTableArgs(a) end
---@alias game-Scripts-Main.unpackTableArgs ...

function game.unpackTableArgsInternal(a, b, c, d) end
---@alias game-Scripts-Main.unpackTableArgsInternal ...

function game.update(a, b) end
---@alias game-Scripts-Main.update ...

function game.wait(a, b, c) end
---@alias game-Scripts-Main.wait ...

function game.waitUnmodified(a, b, c) end
---@alias game-Scripts-Main.waitUnmodified ...

function game.waitUntil(a, b, c) end
---@alias game-Scripts-Main.waitUntil ...

return game