---@meta game-Scripts-MarketLogic
local game = {}

function game.CloseMarketScreen(a, b) end
---@alias game-Scripts-MarketLogic.CloseMarketScreen ...

function game.GenerateMarketItems(a, b) end
---@alias game-Scripts-MarketLogic.GenerateMarketItems ...

function game.HandleMarketPurchase(a, b) end
---@alias game-Scripts-MarketLogic.HandleMarketPurchase ...

function game.HasAllWorldUpgradesRequiringResource(a, b) end
---@alias game-Scripts-MarketLogic.HasAllWorldUpgradesRequiringResource ...

function game.HasUnviewedMarketItem(a, b) end
---@alias game-Scripts-MarketLogic.HasUnviewedMarketItem ...

function game.IsMarketItemInStock(a, b) end
---@alias game-Scripts-MarketLogic.IsMarketItemInStock ...

function game.MarketScreenDisplayCategory(a, b, c) end
---@alias game-Scripts-MarketLogic.MarketScreenDisplayCategory ...

function game.MarketScreenNextCategory(a, b) end
---@alias game-Scripts-MarketLogic.MarketScreenNextCategory ...

function game.MarketScreenPrevCategory(a, b) end
---@alias game-Scripts-MarketLogic.MarketScreenPrevCategory ...

function game.MarketScreenSelectCategory(a, b) end
---@alias game-Scripts-MarketLogic.MarketScreenSelectCategory ...

function game.MarketScreenSellAll(a, b) end
---@alias game-Scripts-MarketLogic.MarketScreenSellAll ...

function game.MarketScreenShowSellAllPrompt(a) end
---@alias game-Scripts-MarketLogic.MarketScreenShowSellAllPrompt ...

function game.MarketScreenUpdateResourceStatus(a) end
---@alias game-Scripts-MarketLogic.MarketScreenUpdateResourceStatus ...

function game.OpenMarketScreen(a) end
---@alias game-Scripts-MarketLogic.OpenMarketScreen ...

function game.UpdateMarketScreenInteractionText(a, b) end
---@alias game-Scripts-MarketLogic.UpdateMarketScreenInteractionText ...

function game.UseMarketObject(a, b) end
---@alias game-Scripts-MarketLogic.UseMarketObject ...

return game