---@meta game-Scripts-MetaUpgradeCardScreenPresentation
local game = {}

function game.CannotAffordMetaUpgradeLimitPresentation(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.CannotAffordMetaUpgradeLimitPresentation ...

function game.CannotUpgradeMaxLevelMetaUpgradePresentation(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.CannotUpgradeMaxLevelMetaUpgradePresentation ...

function game.CloseMetaUpgradeCardScreenPresentation(a) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.CloseMetaUpgradeCardScreenPresentation ...

function game.DoMetaUpgradeCardReveal(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.DoMetaUpgradeCardReveal ...

function game.DoScreenZoomOut(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.DoScreenZoomOut ...

function game.EquipMetaUpgradeBonusCardPresentation(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.EquipMetaUpgradeBonusCardPresentation ...

function game.EquipMetaUpgradeCardPresentation(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.EquipMetaUpgradeCardPresentation ...

function game.InvalidMetaUpgradeCardAction(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.InvalidMetaUpgradeCardAction ...

function game.MetaUpgradeCardMaxLevelPresentation(a) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.MetaUpgradeCardMaxLevelPresentation ...

function game.MetaUpgradeCardOverLimitPresentation(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.MetaUpgradeCardOverLimitPresentation ...

function game.MetaUpgradeCardRevealComplete(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.MetaUpgradeCardRevealComplete ...

function game.MetaUpgradeCardScreenLayoutChangeIn(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.MetaUpgradeCardScreenLayoutChangeIn ...

function game.MetaUpgradeCardScreenLayoutChangeOut(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.MetaUpgradeCardScreenLayoutChangeOut ...

function game.MetaUpgradeCardScreenMouseOffLayout(a) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.MetaUpgradeCardScreenMouseOffLayout ...

function game.MetaUpgradeCardScreenMouseOverLayout(a) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.MetaUpgradeCardScreenMouseOverLayout ...

function game.MetaUpgradeCardScreenOpenPresentation(a) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.MetaUpgradeCardScreenOpenPresentation ...

function game.MetaUpgradeCardScreenUpdateLayoutSets(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.MetaUpgradeCardScreenUpdateLayoutSets ...

function game.MetaUpgradeCardZoomPresentation(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.MetaUpgradeCardZoomPresentation ...

function game.MouseOverMetaUpgradeLimitPresentation(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.MouseOverMetaUpgradeLimitPresentation ...

function game.NewBonePresentation(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.NewBonePresentation ...

function game.PulseMetaUpgradeMemCostDisplay(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.PulseMetaUpgradeMemCostDisplay ...

function game.RevealMetaUpgradeCardPresentation(a, b, c) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.RevealMetaUpgradeCardPresentation ...

function game.StopMetaUpgradeMemCostPulse(a) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.StopMetaUpgradeMemCostPulse ...

function game.UnequipMetaUpgradeBonusCardPresentation(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.UnequipMetaUpgradeBonusCardPresentation ...

function game.UnequipMetaUpgradeCardPresentation(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.UnequipMetaUpgradeCardPresentation ...

function game.UnlockMetaUpgradeCardPresentation(a, b, c) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.UnlockMetaUpgradeCardPresentation ...

function game.UpgradeMetaUpgradeCardPresentation(a) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.UpgradeMetaUpgradeCardPresentation ...

function game.UpgradeMetaUpgradeLimitPresentation(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.UpgradeMetaUpgradeLimitPresentation ...

function game.UpgradeModeAvailablePresentation(a) end
---@alias game-Scripts-MetaUpgradeCardScreenPresentation.UpgradeModeAvailablePresentation ...

return game