---@meta game-Scripts-MetaUpgradeData
local game = {}

---@class game-Scripts-MetaUpgradeData*FatedDisableKeepsakes

---@type game-Scripts-MetaUpgradeData*FatedDisableKeepsakes
game.FatedDisableKeepsakes = ...
---@alias game-Scripts-MetaUpgradeData.FatedDisableKeepsakes ...

---@class game-Scripts-MetaUpgradeData*FatedDisableMetaUpgrades

---@type game-Scripts-MetaUpgradeData*FatedDisableMetaUpgrades
game.FatedDisableMetaUpgrades = ...
---@alias game-Scripts-MetaUpgradeData.FatedDisableMetaUpgrades ...

---@class game-Scripts-MetaUpgradeData*FatedEnableKeepsakes

---@type game-Scripts-MetaUpgradeData*FatedEnableKeepsakes
game.FatedEnableKeepsakes = ...
---@alias game-Scripts-MetaUpgradeData.FatedEnableKeepsakes ...

---@class game-Scripts-MetaUpgradeData*MetaUpgradeCardData

---@type game-Scripts-MetaUpgradeData*MetaUpgradeCardData
game.MetaUpgradeCardData = ...
---@alias game-Scripts-MetaUpgradeData.MetaUpgradeCardData ...

---@class game-Scripts-MetaUpgradeData*MetaUpgradeCardRarityIcons

---@type game-Scripts-MetaUpgradeData*MetaUpgradeCardRarityIcons
game.MetaUpgradeCardRarityIcons = ...
---@alias game-Scripts-MetaUpgradeData.MetaUpgradeCardRarityIcons ...

---@class game-Scripts-MetaUpgradeData*MetaUpgradeCostData

---@type game-Scripts-MetaUpgradeData*MetaUpgradeCostData
game.MetaUpgradeCostData = ...
---@alias game-Scripts-MetaUpgradeData.MetaUpgradeCostData ...

---@class game-Scripts-MetaUpgradeData*MetaUpgradeData

---@type game-Scripts-MetaUpgradeData*MetaUpgradeData
game.MetaUpgradeData = ...
---@alias game-Scripts-MetaUpgradeData.MetaUpgradeData ...

---@class game-Scripts-MetaUpgradeData*MetaUpgradeDefaultCardLayout

---@type game-Scripts-MetaUpgradeData*MetaUpgradeDefaultCardLayout
game.MetaUpgradeDefaultCardLayout = ...
---@alias game-Scripts-MetaUpgradeData.MetaUpgradeDefaultCardLayout ...

---@class game-Scripts-MetaUpgradeData*MetaUpgradeLockOrder

---@type game-Scripts-MetaUpgradeData*MetaUpgradeLockOrder
game.MetaUpgradeLockOrder = ...
---@alias game-Scripts-MetaUpgradeData.MetaUpgradeLockOrder ...

---@class game-Scripts-MetaUpgradeData*MetaUpgradeSaveLayoutData

---@type game-Scripts-MetaUpgradeData*MetaUpgradeSaveLayoutData
game.MetaUpgradeSaveLayoutData = ...
---@alias game-Scripts-MetaUpgradeData.MetaUpgradeSaveLayoutData ...

---@class game-Scripts-MetaUpgradeData*MetaUpgradeSwapGameStateRequirement

---@type game-Scripts-MetaUpgradeData*MetaUpgradeSwapGameStateRequirement
game.MetaUpgradeSwapGameStateRequirement = ...
---@alias game-Scripts-MetaUpgradeData.MetaUpgradeSwapGameStateRequirement ...

---@class game-Scripts-MetaUpgradeData*RerollCosts

---@type game-Scripts-MetaUpgradeData*RerollCosts
game.RerollCosts = ...
---@alias game-Scripts-MetaUpgradeData.RerollCosts ...

return game