---@meta game-Scripts-MetaUpgradeCardScreenLogic
local game = {}

function game.CanIncreaseMetaUpgradeCardLimit() end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.CanIncreaseMetaUpgradeCardLimit ...

function game.CanUpgradeCards() end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.CanUpgradeCards ...

function game.CheckAutoEquipCards(a) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.CheckAutoEquipCards ...

function game.CloseMetaUpgradeCardScreen(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.CloseMetaUpgradeCardScreen ...

function game.CreateBones(a) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.CreateBones ...

function game.CreateMetaUpgradeCard(a, b, c, d, e) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.CreateMetaUpgradeCard ...

function game.CreateMetaUpgradeCards(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.CreateMetaUpgradeCards ...

function game.DoCardSwap(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.DoCardSwap ...

function game.DoMetaUpgradePatches() end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.DoMetaUpgradePatches ...

function game.EnterUpgradeMode(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.EnterUpgradeMode ...

function game.EquipMetaUpgradeButton(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.EquipMetaUpgradeButton ...

function game.GetCoordsInColumn(a) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.GetCoordsInColumn ...

function game.GetCoordsInRow(a) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.GetCoordsInRow ...

function game.GetCurrentMetaUpgradeCost() end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.GetCurrentMetaUpgradeCost ...

function game.GetCurrentMetaUpgradeLimitLevel() end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.GetCurrentMetaUpgradeLimitLevel ...

function game.GetMaximumUnlockedMetaUpgradeCost() end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.GetMaximumUnlockedMetaUpgradeCost ...

function game.GetMaxMetaUpgradeCost() end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.GetMaxMetaUpgradeCost ...

function game.GetMetaUpgradeCardButton(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.GetMetaUpgradeCardButton ...

function game.GetMetaUpgradeKey(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.GetMetaUpgradeKey ...

function game.GetNeighboringCoords(a, b, c) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.GetNeighboringCoords ...

function game.GetZoomLevel() end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.GetZoomLevel ...

function game.HandleCardSwapInput(a) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.HandleCardSwapInput ...

function game.HasNeighboringUnlockedCards(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.HasNeighboringUnlockedCards ...

function game.IncreaseMetaUpgradeCardLimit(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.IncreaseMetaUpgradeCardLimit ...

function game.InitializeMetaUpgradePins(a) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.InitializeMetaUpgradePins ...

function game.LoadCurrentMetaUpgradeSet(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.LoadCurrentMetaUpgradeSet ...

function game.MetaUpgradeCardAction(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.MetaUpgradeCardAction ...

function game.MetaUpgradeCardEquipped(a) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.MetaUpgradeCardEquipped ...

function game.MetaUpgradeCardScreenCanSwapLayoutArt(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.MetaUpgradeCardScreenCanSwapLayoutArt ...

function game.MetaUpgradeCardScreenLayoutSetSwapClose(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.MetaUpgradeCardScreenLayoutSetSwapClose ...

function game.MetaUpgradeCardScreenLayoutSetSwapOpen(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.MetaUpgradeCardScreenLayoutSetSwapOpen ...

function game.MetaUpgradeCardScreenNextLayout(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.MetaUpgradeCardScreenNextLayout ...

function game.MetaUpgradeCardScreenPinItem(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.MetaUpgradeCardScreenPinItem ...

function game.MetaUpgradeCardScreenPrevLayout(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.MetaUpgradeCardScreenPrevLayout ...

function game.MetaUpgradeCardScreenResetCursor(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.MetaUpgradeCardScreenResetCursor ...

function game.MetaUpgradeCardScreenSelectLayout(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.MetaUpgradeCardScreenSelectLayout ...

function game.MetaupgradeUpdateCardZoom(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.MetaupgradeUpdateCardZoom ...

function game.MouseOffLayoutSetArt(a) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.MouseOffLayoutSetArt ...

function game.MouseOffMetaUpgrade(a) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.MouseOffMetaUpgrade ...

function game.MouseOffMetaUpgradeCardLimit(a) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.MouseOffMetaUpgradeCardLimit ...

function game.MouseOverLayoutSetArt(a) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.MouseOverLayoutSetArt ...

function game.MouseOverMetaUpgrade(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.MouseOverMetaUpgrade ...

function game.MouseOverMetaUpgradeCardLimit(a) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.MouseOverMetaUpgradeCardLimit ...

function game.NoMetaUpgradeCardsUnlocked() end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.NoMetaUpgradeCardsUnlocked ...

function game.OpenMetaUpgradeCardScreen(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.OpenMetaUpgradeCardScreen ...

function game.RecordMetaUpgradeChanges(a) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.RecordMetaUpgradeChanges ...

function game.RecordStartingMetaUpgrades(a) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.RecordStartingMetaUpgrades ...

function game.RecreateMetaUpgradeCostText(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.RecreateMetaUpgradeCostText ...

function game.SaveCurrentMetaUpgradeSet() end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.SaveCurrentMetaUpgradeSet ...

function game.SelectLayoutSetArt(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.SelectLayoutSetArt ...

function game.SelectMetaUpgradeButton(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.SelectMetaUpgradeButton ...

function game.SetCardOnDelay(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.SetCardOnDelay ...

function game.ShouldShowMetaUpgradeCapacityHint(a) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.ShouldShowMetaUpgradeCapacityHint ...

function game.UpdateMetaUpgradeCard(a, b, c, d) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.UpdateMetaUpgradeCard ...

function game.UpdateMetaUpgradeCardAnimation(a) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.UpdateMetaUpgradeCardAnimation ...

function game.UpdateMetaUpgradeCardInteractionText(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.UpdateMetaUpgradeCardInteractionText ...

function game.UpdateMetaUpgradeCardState(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.UpdateMetaUpgradeCardState ...

function game.UpdateMetaUpgradeCostDisplay(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.UpdateMetaUpgradeCostDisplay ...

function game.UpdateMetaUpgradeCostText(a, b) end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.UpdateMetaUpgradeCostText ...

function game.UpdateMetaUpgradeUnlockedCountCache() end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.UpdateMetaUpgradeUnlockedCountCache ...

function game.ValidateMetaUpgradeLayout() end
---@alias game-Scripts-MetaUpgradeCardScreenLogic.ValidateMetaUpgradeLayout ...

return game