---@meta game-Scripts-PowersLogic
local game = {}

function game.AddRandomChaosBlessing(a) end
---@alias game-Scripts-PowersLogic.AddRandomChaosBlessing ...

function game.AddRandomHammer(a) end
---@alias game-Scripts-PowersLogic.AddRandomHammer ...

function game.AddTalentPoints(a, b) end
---@alias game-Scripts-PowersLogic.AddTalentPoints ...

function game.AddTraitResources(a, b) end
---@alias game-Scripts-PowersLogic.AddTraitResources ...

function game.ApolloBlindStrike(a, b) end
---@alias game-Scripts-PowersLogic.ApolloBlindStrike ...

function game.ApolloDelayedBlast(a, b, c) end
---@alias game-Scripts-PowersLogic.ApolloDelayedBlast ...

function game.ApolloEarlyCastBlast(a, b, c) end
---@alias game-Scripts-PowersLogic.ApolloEarlyCastBlast ...

function game.ApolloRetaliate(a, b) end
---@alias game-Scripts-PowersLogic.ApolloRetaliate ...

function game.ApolloRetaliateThread(a) end
---@alias game-Scripts-PowersLogic.ApolloRetaliateThread ...

function game.ApplyAphroditeVulnerability(a, b, c) end
---@alias game-Scripts-PowersLogic.ApplyAphroditeVulnerability ...

function game.ApplyBurn(a, b, c) end
---@alias game-Scripts-PowersLogic.ApplyBurn ...

function game.ApplyDamageShare(a, b, c) end
---@alias game-Scripts-PowersLogic.ApplyDamageShare ...

function game.ApplyOmegaBuff(a) end
---@alias game-Scripts-PowersLogic.ApplyOmegaBuff ...

function game.ApplyRoot(a, b, c) end
---@alias game-Scripts-PowersLogic.ApplyRoot ...

function game.AthenaDeflect(a, b, c) end
---@alias game-Scripts-PowersLogic.AthenaDeflect ...

function game.AthenaInvulnerabilitySetup(a, b) end
---@alias game-Scripts-PowersLogic.AthenaInvulnerabilitySetup ...

function game.AthenaRefillLastStands(a) end
---@alias game-Scripts-PowersLogic.AthenaRefillLastStands ...

function game.AthenaRetaliate(a, b, c) end
---@alias game-Scripts-PowersLogic.AthenaRetaliate ...

function game.AttachCastAtLocation(a) end
---@alias game-Scripts-PowersLogic.AttachCastAtLocation ...

function game.AttemptAdvanceKeepsake(a, b) end
---@alias game-Scripts-PowersLogic.AttemptAdvanceKeepsake ...

function game.AutofireLogProjectilesForFireEvent(a, b, c) end
---@alias game-Scripts-PowersLogic.AutofireLogProjectilesForFireEvent ...

function game.BankGold(a, b) end
---@alias game-Scripts-PowersLogic.BankGold ...

function game.BloodDropExpire(a, b) end
---@alias game-Scripts-PowersLogic.BloodDropExpire ...

function game.BloodDropUse(a, b) end
---@alias game-Scripts-PowersLogic.BloodDropUse ...

function game.CacheCurrentLifestealUses(a, b) end
---@alias game-Scripts-PowersLogic.CacheCurrentLifestealUses ...

function game.CanGoldifyReward(a) end
---@alias game-Scripts-PowersLogic.CanGoldifyReward ...

function game.CarryOverBloodDropBonus(a, b) end
---@alias game-Scripts-PowersLogic.CarryOverBloodDropBonus ...

function game.ChaosBlessingBonus(a, b, c) end
---@alias game-Scripts-PowersLogic.ChaosBlessingBonus ...

function game.ChaosCurseDamage(a, b, c) end
---@alias game-Scripts-PowersLogic.ChaosCurseDamage ...

function game.ChaosManaDrain(a, b, c) end
---@alias game-Scripts-PowersLogic.ChaosManaDrain ...

function game.ChaosStunSelf(a, b, c) end
---@alias game-Scripts-PowersLogic.ChaosStunSelf ...

function game.ChargeSkullImpulse(a, b, c) end
---@alias game-Scripts-PowersLogic.ChargeSkullImpulse ...

function game.CharmCrowd(a, b) end
---@alias game-Scripts-PowersLogic.CharmCrowd ...

function game.CheckApolloManaRestore(a, b) end
---@alias game-Scripts-PowersLogic.CheckApolloManaRestore ...

function game.CheckApplyDamageShare(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckApplyDamageShare ...

function game.CheckAresBloodDrop(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckAresBloodDrop ...

function game.CheckAresCurseApply(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckAresCurseApply ...

function game.CheckAresExCurseApply(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckAresExCurseApply ...

function game.CheckAresManaBloodDrop(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckAresManaBloodDrop ...

function game.CheckArmedApolloCast(a, b) end
---@alias game-Scripts-PowersLogic.CheckArmedApolloCast ...

function game.CheckArmedPoseidonCast(a, b) end
---@alias game-Scripts-PowersLogic.CheckArmedPoseidonCast ...

function game.CheckArmImput(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckArmImput ...

function game.CheckAthenaProjectile(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckAthenaProjectile ...

function game.CheckAutoRevenge(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckAutoRevenge ...

function game.CheckAxeCastArm(a, b) end
---@alias game-Scripts-PowersLogic.CheckAxeCastArm ...

function game.CheckAxeNova(a, b) end
---@alias game-Scripts-PowersLogic.CheckAxeNova ...

function game.CheckBlindApply(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckBlindApply ...

function game.CheckBloodDropDisplay() end
---@alias game-Scripts-PowersLogic.CheckBloodDropDisplay ...

function game.CheckBurnConsumption(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckBurnConsumption ...

function game.CheckBurnConsumptionDelay(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckBurnConsumptionDelay ...

function game.CheckBurnDeathExplosion(a, b) end
---@alias game-Scripts-PowersLogic.CheckBurnDeathExplosion ...

function game.CheckCastAphroditeVulnerabilityApply(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckCastAphroditeVulnerabilityApply ...

function game.CheckCastBurnApply(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckCastBurnApply ...

function game.CheckCastDetach(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckCastDetach ...

function game.CheckCastSummonDamage(a, b) end
---@alias game-Scripts-PowersLogic.CheckCastSummonDamage ...

function game.CheckCastVolley(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckCastVolley ...

function game.CheckClearCastManaRefund(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckClearCastManaRefund ...

function game.CheckClearCastStart(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckClearCastStart ...

function game.CheckDaggerBlock(a, b) end
---@alias game-Scripts-PowersLogic.CheckDaggerBlock ...

function game.CheckDaggerBlockRecharge(a, b) end
---@alias game-Scripts-PowersLogic.CheckDaggerBlockRecharge ...

function game.CheckDaggerCritCharges(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckDaggerCritCharges ...

function game.CheckDaggerPenetration(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckDaggerPenetration ...

function game.CheckDamageOnFire(a) end
---@alias game-Scripts-PowersLogic.CheckDamageOnFire ...

function game.CheckDashVolley(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckDashVolley ...

function game.CheckDemeterStormSpawn(a, b) end
---@alias game-Scripts-PowersLogic.CheckDemeterStormSpawn ...

function game.CheckDifferentOmegaCrit(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckDifferentOmegaCrit ...

function game.CheckDionysusDebuff(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckDionysusDebuff ...

function game.CheckDrinkCritCharges(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckDrinkCritCharges ...

function game.CheckDrinkSpawn(a, b) end
---@alias game-Scripts-PowersLogic.CheckDrinkSpawn ...

function game.CheckExProjectileSpawn(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckExProjectileSpawn ...

function game.CheckFamiliarLink(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckFamiliarLink ...

function game.CheckFireballSpawn(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckFireballSpawn ...

function game.CheckFrenzyCount(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckFrenzyCount ...

function game.CheckGenerateAresSword(a) end
---@alias game-Scripts-PowersLogic.CheckGenerateAresSword ...

function game.CheckHeraManaRestore(a, b) end
---@alias game-Scripts-PowersLogic.CheckHeraManaRestore ...

function game.CheckIcarusExplosion(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckIcarusExplosion ...

function game.CheckIndirectCastAthenaDeflect(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckIndirectCastAthenaDeflect ...

function game.CheckLavaPresentation(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckLavaPresentation ...

function game.CheckLavaSplashPresentation(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckLavaSplashPresentation ...

function game.CheckLeapCritCharges(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckLeapCritCharges ...

function game.CheckLinkDeathDamage(a, b) end
---@alias game-Scripts-PowersLogic.CheckLinkDeathDamage ...

function game.CheckLobDetonate(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckLobDetonate ...

function game.CheckManaBurst(a, b) end
---@alias game-Scripts-PowersLogic.CheckManaBurst ...

function game.CheckManaSpear(a, b) end
---@alias game-Scripts-PowersLogic.CheckManaSpear ...

function game.CheckManaUrn(a, b) end
---@alias game-Scripts-PowersLogic.CheckManaUrn ...

function game.CheckMassiveAttack(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckMassiveAttack ...

function game.CheckNewStatusDamage(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckNewStatusDamage ...

function game.CheckOnDamagedPowers(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckOnDamagedPowers ...

function game.CheckOnDeathAutoRevenge(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckOnDeathAutoRevenge ...

function game.CheckPerfectAxeCrit(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckPerfectAxeCrit ...

function game.CheckPerfectChargeRefund(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckPerfectChargeRefund ...

function game.CheckPlayerOnFirePowers(a) end
---@alias game-Scripts-PowersLogic.CheckPlayerOnFirePowers ...

function game.CheckPoseidonCastSplash(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckPoseidonCastSplash ...

function game.CheckPoseidonExProjectileOnSpawn(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckPoseidonExProjectileOnSpawn ...

function game.CheckPoseidonSplash(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckPoseidonSplash ...

function game.CheckPotionClearCast(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckPotionClearCast ...

function game.CheckProjectilePull(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckProjectilePull ...

function game.CheckProjectileSpawn(a, b) end
---@alias game-Scripts-PowersLogic.CheckProjectileSpawn ...

function game.CheckRandomStatusCurse(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckRandomStatusCurse ...

function game.CheckRootStrike(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckRootStrike ...

function game.CheckSkullImpulseStart() end
---@alias game-Scripts-PowersLogic.CheckSkullImpulseStart ...

function game.CheckSlipApply(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckSlipApply ...

function game.CheckSpawnArmorDamage(a, b) end
---@alias game-Scripts-PowersLogic.CheckSpawnArmorDamage ...

function game.CheckSpawnCurseDamage(a, b) end
---@alias game-Scripts-PowersLogic.CheckSpawnCurseDamage ...

function game.CheckSpawnZeusDamage(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckSpawnZeusDamage ...

function game.CheckSplitValidity(a, b) end
---@alias game-Scripts-PowersLogic.CheckSplitValidity ...

function game.CheckSprintCollision(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckSprintCollision ...

function game.CheckSprintPhasingCollision(a) end
---@alias game-Scripts-PowersLogic.CheckSprintPhasingCollision ...

function game.CheckStaffProjectilePull(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckStaffProjectilePull ...

function game.CheckSteam(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckSteam ...

function game.CheckSupportingFire(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckSupportingFire ...

function game.CheckTimedKillBuff(a, b) end
---@alias game-Scripts-PowersLogic.CheckTimedKillBuff ...

function game.CheckTorchDetonation(a, b) end
---@alias game-Scripts-PowersLogic.CheckTorchDetonation ...

function game.CheckUrnDetonation(a, b) end
---@alias game-Scripts-PowersLogic.CheckUrnDetonation ...

function game.CheckWeaponAmmoFire(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckWeaponAmmoFire ...

function game.CheckZeusManaBolt(a) end
---@alias game-Scripts-PowersLogic.CheckZeusManaBolt ...

function game.CheckZeusManaSpawn(a, b) end
---@alias game-Scripts-PowersLogic.CheckZeusManaSpawn ...

function game.CheckZeusProjectile(a, b, c) end
---@alias game-Scripts-PowersLogic.CheckZeusProjectile ...

function game.CleanupRaiseDeadEncounter(a) end
---@alias game-Scripts-PowersLogic.CleanupRaiseDeadEncounter ...

function game.CleanupShadeMerc(a) end
---@alias game-Scripts-PowersLogic.CleanupShadeMerc ...

function game.ClearAllOriginMarkers() end
---@alias game-Scripts-PowersLogic.ClearAllOriginMarkers ...

function game.ClearBlindEffect(a, b, c) end
---@alias game-Scripts-PowersLogic.ClearBlindEffect ...

function game.ClearCastRestoreEligible(a) end
---@alias game-Scripts-PowersLogic.ClearCastRestoreEligible ...

function game.ClearOriginMarker(a, b) end
---@alias game-Scripts-PowersLogic.ClearOriginMarker ...

function game.ClearReserveManaInvulnerability() end
---@alias game-Scripts-PowersLogic.ClearReserveManaInvulnerability ...

function game.ClearRoot(a, b, c) end
---@alias game-Scripts-PowersLogic.ClearRoot ...

function game.ContinuousDemeterCast(a, b, c) end
---@alias game-Scripts-PowersLogic.ContinuousDemeterCast ...

function game.CreateAlliedEnemy(a, b) end
---@alias game-Scripts-PowersLogic.CreateAlliedEnemy ...

function game.CreateBloodDrop(a, b) end
---@alias game-Scripts-PowersLogic.CreateBloodDrop ...

function game.CreateManaBurst(a, b) end
---@alias game-Scripts-PowersLogic.CreateManaBurst ...

function game.CreateManaUrn(a, b) end
---@alias game-Scripts-PowersLogic.CreateManaUrn ...

function game.CreateSecondAnubisWall(a, b, c) end
---@alias game-Scripts-PowersLogic.CreateSecondAnubisWall ...

function game.CreateShadeMerc(a, b) end
---@alias game-Scripts-PowersLogic.CreateShadeMerc ...

function game.CreateZeusBolt(a) end
---@alias game-Scripts-PowersLogic.CreateZeusBolt ...

function game.CreditMissingGold(a, b) end
---@alias game-Scripts-PowersLogic.CreditMissingGold ...

function game.CurseRetaliate(a, b) end
---@alias game-Scripts-PowersLogic.CurseRetaliate ...

function game.DaggerBlockSetup(a, b) end
---@alias game-Scripts-PowersLogic.DaggerBlockSetup ...

function game.DaggerFinalHitIncrease(a, b, c) end
---@alias game-Scripts-PowersLogic.DaggerFinalHitIncrease ...

function game.DelayEndShadeDissipate(a) end
---@alias game-Scripts-PowersLogic.DelayEndShadeDissipate ...

function game.DelayFireSprintLinkProjectile(a, b) end
---@alias game-Scripts-PowersLogic.DelayFireSprintLinkProjectile ...

function game.DemeterCastBlast(a, b, c) end
---@alias game-Scripts-PowersLogic.DemeterCastBlast ...

function game.DemeterSprintBlast(a, b, c) end
---@alias game-Scripts-PowersLogic.DemeterSprintBlast ...

function game.DemeterSprintStormDetach(a) end
---@alias game-Scripts-PowersLogic.DemeterSprintStormDetach ...

function game.DestroyMeldedBlessing(a, b) end
---@alias game-Scripts-PowersLogic.DestroyMeldedBlessing ...

function game.DiminishingDodge(a, b) end
---@alias game-Scripts-PowersLogic.DiminishingDodge ...

function game.DiminishingDodgeSetup(a, b) end
---@alias game-Scripts-PowersLogic.DiminishingDodgeSetup ...

function game.DionysusSkipTrait(a, b) end
---@alias game-Scripts-PowersLogic.DionysusSkipTrait ...

function game.DoCurseDamage(a, b, c, d) end
---@alias game-Scripts-PowersLogic.DoCurseDamage ...

function game.DodgeHeal(a, b) end
---@alias game-Scripts-PowersLogic.DodgeHeal ...

function game.DoLinkDeath(a, b) end
---@alias game-Scripts-PowersLogic.DoLinkDeath ...

function game.DoZeusSpawnDamage(a, b, c) end
---@alias game-Scripts-PowersLogic.DoZeusSpawnDamage ...

function game.DrinkPickup(a, b, c) end
---@alias game-Scripts-PowersLogic.DrinkPickup ...

function game.DropOriginMarker(a, b, c) end
---@alias game-Scripts-PowersLogic.DropOriginMarker ...

function game.EncounterStartTempArmor(a, b) end
---@alias game-Scripts-PowersLogic.EncounterStartTempArmor ...

function game.EncounterStartTempArmorThread(a, b) end
---@alias game-Scripts-PowersLogic.EncounterStartTempArmorThread ...

function game.EndAnubisAnimationSwaps() end
---@alias game-Scripts-PowersLogic.EndAnubisAnimationSwaps ...

function game.EndAutofire() end
---@alias game-Scripts-PowersLogic.EndAutofire ...

function game.EndAxeSturdy() end
---@alias game-Scripts-PowersLogic.EndAxeSturdy ...

function game.EndEncounterHeal(a, b) end
---@alias game-Scripts-PowersLogic.EndEncounterHeal ...

function game.EndEncounterShadeDissipate(a, b) end
---@alias game-Scripts-PowersLogic.EndEncounterShadeDissipate ...

function game.EndEosProjectile() end
---@alias game-Scripts-PowersLogic.EndEosProjectile ...

function game.EndLobSturdy() end
---@alias game-Scripts-PowersLogic.EndLobSturdy ...

function game.EndMedeaAnimationSwaps() end
---@alias game-Scripts-PowersLogic.EndMedeaAnimationSwaps ...

function game.EndSprintPhasing(a, b) end
---@alias game-Scripts-PowersLogic.EndSprintPhasing ...

function game.EndTimedBuff(a) end
---@alias game-Scripts-PowersLogic.EndTimedBuff ...

function game.EnlargeApply(a) end
---@alias game-Scripts-PowersLogic.EnlargeApply ...

function game.EnlargeClear(a) end
---@alias game-Scripts-PowersLogic.EnlargeClear ...

function game.ExpireDaggersOnBlink(a, b, c) end
---@alias game-Scripts-PowersLogic.ExpireDaggersOnBlink ...

function game.FireAphroditeSprintProjectile(a, b) end
---@alias game-Scripts-PowersLogic.FireAphroditeSprintProjectile ...

function game.FireAphroditeSprintProjectileAtEnd(a, b) end
---@alias game-Scripts-PowersLogic.FireAphroditeSprintProjectileAtEnd ...

function game.FireAphroditeSprintProjectileAtStart(a, b) end
---@alias game-Scripts-PowersLogic.FireAphroditeSprintProjectileAtStart ...

function game.FireDaggerSpecial(a, b, c) end
---@alias game-Scripts-PowersLogic.FireDaggerSpecial ...

function game.FireDemeterCastStrike(a, b, c) end
---@alias game-Scripts-PowersLogic.FireDemeterCastStrike ...

function game.FireHadesSprintProjectile(a, b, c) end
---@alias game-Scripts-PowersLogic.FireHadesSprintProjectile ...

function game.FireHephaestusSprintProjectile(a, b) end
---@alias game-Scripts-PowersLogic.FireHephaestusSprintProjectile ...

function game.FireHephCastStrike(a, b, c) end
---@alias game-Scripts-PowersLogic.FireHephCastStrike ...

function game.FireRallyHeal(a, b, c) end
---@alias game-Scripts-PowersLogic.FireRallyHeal ...

function game.FireRallyThread(a, b) end
---@alias game-Scripts-PowersLogic.FireRallyThread ...

function game.FireWeaponWithinRange(a) end
---@alias game-Scripts-PowersLogic.FireWeaponWithinRange ...

function game.FizzleOldAnubisProjectiles(a, b) end
---@alias game-Scripts-PowersLogic.FizzleOldAnubisProjectiles ...

function game.FreezeFrameApply(a) end
---@alias game-Scripts-PowersLogic.FreezeFrameApply ...

function game.FreezeFrameClear(a) end
---@alias game-Scripts-PowersLogic.FreezeFrameClear ...

function game.FreezeStunApply(a) end
---@alias game-Scripts-PowersLogic.FreezeStunApply ...

function game.GetRequiredForceToEnemy(a, b, c, d) end
---@alias game-Scripts-PowersLogic.GetRequiredForceToEnemy ...

function game.GetRewardGoldifyValue(a) end
---@alias game-Scripts-PowersLogic.GetRewardGoldifyValue ...

function game.GetTorchSplitProjectileCap() end
---@alias game-Scripts-PowersLogic.GetTorchSplitProjectileCap ...

function game.GiveDurationHammer(a, b) end
---@alias game-Scripts-PowersLogic.GiveDurationHammer ...

function game.GiveRandomHadesBoonAndBoostBoons(a, b) end
---@alias game-Scripts-PowersLogic.GiveRandomHadesBoonAndBoostBoons ...

function game.GrantRandomMaxHealth(a) end
---@alias game-Scripts-PowersLogic.GrantRandomMaxHealth ...

function game.HadesInvisibility() end
---@alias game-Scripts-PowersLogic.HadesInvisibility ...

function game.HadesInvisibilitySetup(a, b) end
---@alias game-Scripts-PowersLogic.HadesInvisibilitySetup ...

function game.HadesInvisibleClear() end
---@alias game-Scripts-PowersLogic.HadesInvisibleClear ...

function game.HadesRetaliate(a, b, c) end
---@alias game-Scripts-PowersLogic.HadesRetaliate ...

function game.HandleAttachRecord(a, b, c) end
---@alias game-Scripts-PowersLogic.HandleAttachRecord ...

function game.HandleGunBehavior(a, b, c) end
---@alias game-Scripts-PowersLogic.HandleGunBehavior ...

function game.HephaestusArmor(a, b) end
---@alias game-Scripts-PowersLogic.HephaestusArmor ...

function game.HeraCastCountBlast(a, b, c) end
---@alias game-Scripts-PowersLogic.HeraCastCountBlast ...

function game.HeraManaRestoreEligible(a) end
---@alias game-Scripts-PowersLogic.HeraManaRestoreEligible ...

function game.HeraRetaliate(a, b, c) end
---@alias game-Scripts-PowersLogic.HeraRetaliate ...

function game.HeraSprintLink(a) end
---@alias game-Scripts-PowersLogic.HeraSprintLink ...

function game.HeraSprintMana(a, b) end
---@alias game-Scripts-PowersLogic.HeraSprintMana ...

function game.HeraSprintSuction(a) end
---@alias game-Scripts-PowersLogic.HeraSprintSuction ...

function game.HestiaBlockSpend(a, b, c) end
---@alias game-Scripts-PowersLogic.HestiaBlockSpend ...

function game.HestiaCastDefense(a, b, c) end
---@alias game-Scripts-PowersLogic.HestiaCastDefense ...

function game.HestiaSprintFlames(a, b) end
---@alias game-Scripts-PowersLogic.HestiaSprintFlames ...

function game.HestiaSprintSplash(a) end
---@alias game-Scripts-PowersLogic.HestiaSprintSplash ...

function game.HideGunUI() end
---@alias game-Scripts-PowersLogic.HideGunUI ...

function game.IcarusArmorExplosion(a) end
---@alias game-Scripts-PowersLogic.IcarusArmorExplosion ...

function game.IcarusArmorInvulnerability(a) end
---@alias game-Scripts-PowersLogic.IcarusArmorInvulnerability ...

function game.IcarusHazardCast(a, b, c) end
---@alias game-Scripts-PowersLogic.IcarusHazardCast ...

function game.IcarusSelfDamage(a, b, c) end
---@alias game-Scripts-PowersLogic.IcarusSelfDamage ...

function game.IcarusUpgradeBoon(a, b) end
---@alias game-Scripts-PowersLogic.IcarusUpgradeBoon ...

function game.ImpactSlowApply(a) end
---@alias game-Scripts-PowersLogic.ImpactSlowApply ...

function game.InsideCastBuffApply(a) end
---@alias game-Scripts-PowersLogic.InsideCastBuffApply ...

function game.InsideCastBuffClear(a) end
---@alias game-Scripts-PowersLogic.InsideCastBuffClear ...

function game.IntermittentHephCastStrike(a, b, c) end
---@alias game-Scripts-PowersLogic.IntermittentHephCastStrike ...

function game.LastMomentManaRestoreEligible(a) end
---@alias game-Scripts-PowersLogic.LastMomentManaRestoreEligible ...

function game.LavaVignetteApply(a) end
---@alias game-Scripts-PowersLogic.LavaVignetteApply ...

function game.LavaVignetteClear(a) end
---@alias game-Scripts-PowersLogic.LavaVignetteClear ...

function game.LogTorchAutofireProjectile(a, b) end
---@alias game-Scripts-PowersLogic.LogTorchAutofireProjectile ...

function game.ManageProjectilePull(a, b, c) end
---@alias game-Scripts-PowersLogic.ManageProjectilePull ...

function game.ManageZeusCloud(a, b, c) end
---@alias game-Scripts-PowersLogic.ManageZeusCloud ...

function game.ManaRestoreDamage(a, b) end
---@alias game-Scripts-PowersLogic.ManaRestoreDamage ...

function game.MarkRandomNearby(a, b) end
---@alias game-Scripts-PowersLogic.MarkRandomNearby ...

function game.MassiveAttackSetup(a, b, c) end
---@alias game-Scripts-PowersLogic.MassiveAttackSetup ...

function game.MedeaPoisonAllyBoostApply(a) end
---@alias game-Scripts-PowersLogic.MedeaPoisonAllyBoostApply ...

function game.MedeaPoisonAllyBoostClear(a) end
---@alias game-Scripts-PowersLogic.MedeaPoisonAllyBoostClear ...

function game.MedeaPoisonApply(a) end
---@alias game-Scripts-PowersLogic.MedeaPoisonApply ...

function game.MedeaPoisonClear(a) end
---@alias game-Scripts-PowersLogic.MedeaPoisonClear ...

function game.MeldBlessing(a, b) end
---@alias game-Scripts-PowersLogic.MeldBlessing ...

function game.MultipliedSpeedDodgeSetup(a, b, c) end
---@alias game-Scripts-PowersLogic.MultipliedSpeedDodgeSetup ...

function game.MultiplySameRoomRewards(a, b) end
---@alias game-Scripts-PowersLogic.MultiplySameRoomRewards ...

function game.NyxHitBuffApply(a) end
---@alias game-Scripts-PowersLogic.NyxHitBuffApply ...

function game.NyxHitBuffClear() end
---@alias game-Scripts-PowersLogic.NyxHitBuffClear ...

function game.OnAresCastArmed(a, b) end
---@alias game-Scripts-PowersLogic.OnAresCastArmed ...

function game.OnDemeterCastArmed(a, b) end
---@alias game-Scripts-PowersLogic.OnDemeterCastArmed ...

function game.OnGunOverheatCreated(a) end
---@alias game-Scripts-PowersLogic.OnGunOverheatCreated ...

function game.OnGunRiftCreated(a) end
---@alias game-Scripts-PowersLogic.OnGunRiftCreated ...

function game.OnGunRiftDamage(a, b, c) end
---@alias game-Scripts-PowersLogic.OnGunRiftDamage ...

function game.OnGunRiftDeath(a) end
---@alias game-Scripts-PowersLogic.OnGunRiftDeath ...

function game.OnHitStunApply(a) end
---@alias game-Scripts-PowersLogic.OnHitStunApply ...

function game.OnHitStunClear(a) end
---@alias game-Scripts-PowersLogic.OnHitStunClear ...

function game.OnZeusCast(a, b, c) end
---@alias game-Scripts-PowersLogic.OnZeusCast ...

function game.PeriodicMark(a, b) end
---@alias game-Scripts-PowersLogic.PeriodicMark ...

function game.PermanentSwitchWeapon(a, b) end
---@alias game-Scripts-PowersLogic.PermanentSwitchWeapon ...

function game.PlaySupaySpecialLoop(a, b) end
---@alias game-Scripts-PowersLogic.PlaySupaySpecialLoop ...

function game.PolymorphEnlargeClear(a) end
---@alias game-Scripts-PowersLogic.PolymorphEnlargeClear ...

function game.PoseidonAttackPunish(a, b) end
---@alias game-Scripts-PowersLogic.PoseidonAttackPunish ...

function game.PoseidonIntermittentClearCast(a, b, c) end
---@alias game-Scripts-PowersLogic.PoseidonIntermittentClearCast ...

function game.PoseidonSprintBall(a, b, c) end
---@alias game-Scripts-PowersLogic.PoseidonSprintBall ...

function game.PoseidonSprintBlastDetach() end
---@alias game-Scripts-PowersLogic.PoseidonSprintBlastDetach ...

function game.PoseidonSprintBlastRefresh(a) end
---@alias game-Scripts-PowersLogic.PoseidonSprintBlastRefresh ...

function game.PoseidonSprintFollow(a) end
---@alias game-Scripts-PowersLogic.PoseidonSprintFollow ...

function game.PoseidonSprintSpend(a, b, c) end
---@alias game-Scripts-PowersLogic.PoseidonSprintSpend ...

function game.PoseidonSprintSplash(a, b, c) end
---@alias game-Scripts-PowersLogic.PoseidonSprintSplash ...

function game.PreDamageBoss(a, b, c) end
---@alias game-Scripts-PowersLogic.PreDamageBoss ...

function game.ProjectileExCastPreview(a, b) end
---@alias game-Scripts-PowersLogic.ProjectileExCastPreview ...

function game.QueueManaBurst(a, b) end
---@alias game-Scripts-PowersLogic.QueueManaBurst ...

function game.RaiseKilledEnemy(a, b) end
---@alias game-Scripts-PowersLogic.RaiseKilledEnemy ...

function game.RallyAnubisShades(a, b, c) end
---@alias game-Scripts-PowersLogic.RallyAnubisShades ...

function game.RandomFogSpawn(a, b) end
---@alias game-Scripts-PowersLogic.RandomFogSpawn ...

function game.RecordDamageSnapshot() end
---@alias game-Scripts-PowersLogic.RecordDamageSnapshot ...

function game.RecordSecondStageApolloCast(a, b, c) end
---@alias game-Scripts-PowersLogic.RecordSecondStageApolloCast ...

function game.ReduceKillBuff(a) end
---@alias game-Scripts-PowersLogic.ReduceKillBuff ...

function game.RemoveArcana(a, b) end
---@alias game-Scripts-PowersLogic.RemoveArcana ...

function game.RemoveAresSwordRecord(a, b) end
---@alias game-Scripts-PowersLogic.RemoveAresSwordRecord ...

function game.RemoveArtemisDaggerTick(a) end
---@alias game-Scripts-PowersLogic.RemoveArtemisDaggerTick ...

function game.RemoveAttachedExProjectiles(a) end
---@alias game-Scripts-PowersLogic.RemoveAttachedExProjectiles ...

function game.RemoveCastDefense() end
---@alias game-Scripts-PowersLogic.RemoveCastDefense ...

function game.RemoveCastVolleyProjectile(a) end
---@alias game-Scripts-PowersLogic.RemoveCastVolleyProjectile ...

function game.RemoveCritVolley(a) end
---@alias game-Scripts-PowersLogic.RemoveCritVolley ...

function game.RemoveDashVolley(a) end
---@alias game-Scripts-PowersLogic.RemoveDashVolley ...

function game.RemoveDrinkCritVolley(a) end
---@alias game-Scripts-PowersLogic.RemoveDrinkCritVolley ...

function game.RemoveLeapCritVolley(a) end
---@alias game-Scripts-PowersLogic.RemoveLeapCritVolley ...

function game.RemoveOmegaCritVolley(a) end
---@alias game-Scripts-PowersLogic.RemoveOmegaCritVolley ...

function game.RemoveRootActiveEffectBlock(a, b, c) end
---@alias game-Scripts-PowersLogic.RemoveRootActiveEffectBlock ...

function game.RemoveWeaponAmmoFire(a) end
---@alias game-Scripts-PowersLogic.RemoveWeaponAmmoFire ...

function game.ResetBulletCount(a) end
---@alias game-Scripts-PowersLogic.ResetBulletCount ...

function game.ResetHestiaSprint(a, b) end
---@alias game-Scripts-PowersLogic.ResetHestiaSprint ...

function game.ResetLobSpecialCooldown(a, b) end
---@alias game-Scripts-PowersLogic.ResetLobSpecialCooldown ...

function game.ResetPerfectAxeCrit(a, b, c) end
---@alias game-Scripts-PowersLogic.ResetPerfectAxeCrit ...

function game.ResetPerfectDamageBonusBoon(a, b, c) end
---@alias game-Scripts-PowersLogic.ResetPerfectDamageBonusBoon ...

function game.ResetPoseidonSprint(a, b) end
---@alias game-Scripts-PowersLogic.ResetPoseidonSprint ...

function game.RestoreHephaestusArmor(a, b) end
---@alias game-Scripts-PowersLogic.RestoreHephaestusArmor ...

function game.RestoreLastRoomKillBuff(a) end
---@alias game-Scripts-PowersLogic.RestoreLastRoomKillBuff ...

function game.RestoreRenewableHephaestusArmor(a, b) end
---@alias game-Scripts-PowersLogic.RestoreRenewableHephaestusArmor ...

function game.RoomStartResetPerfectDamageBonus() end
---@alias game-Scripts-PowersLogic.RoomStartResetPerfectDamageBonus ...

function game.RootStrikeThread(a, b) end
---@alias game-Scripts-PowersLogic.RootStrikeThread ...

function game.SetBaseChargeTimes(a, b) end
---@alias game-Scripts-PowersLogic.SetBaseChargeTimes ...

function game.SetupAnubisAnimationSwaps() end
---@alias game-Scripts-PowersLogic.SetupAnubisAnimationSwaps ...

function game.SetupAnywhereCast(a, b) end
---@alias game-Scripts-PowersLogic.SetupAnywhereCast ...

function game.SetupArtemisDaggerTicks(a) end
---@alias game-Scripts-PowersLogic.SetupArtemisDaggerTicks ...

function game.SetupBloodDropDisplay() end
---@alias game-Scripts-PowersLogic.SetupBloodDropDisplay ...

function game.SetupCastCast(a, b) end
---@alias game-Scripts-PowersLogic.SetupCastCast ...

function game.SetupFrenzyUI() end
---@alias game-Scripts-PowersLogic.SetupFrenzyUI ...

function game.SetupHadesCast(a, b) end
---@alias game-Scripts-PowersLogic.SetupHadesCast ...

function game.SetupLobCast(a, b) end
---@alias game-Scripts-PowersLogic.SetupLobCast ...

function game.SetupMedeaAnimationSwaps() end
---@alias game-Scripts-PowersLogic.SetupMedeaAnimationSwaps ...

function game.SetupMercBaseDamageBonus(a, b) end
---@alias game-Scripts-PowersLogic.SetupMercBaseDamageBonus ...

function game.SetupMercDamageBonus(a, b) end
---@alias game-Scripts-PowersLogic.SetupMercDamageBonus ...

function game.SetupPerfectCritUI() end
---@alias game-Scripts-PowersLogic.SetupPerfectCritUI ...

function game.SetupSkullImpulseUI() end
---@alias game-Scripts-PowersLogic.SetupSkullImpulseUI ...

function game.SetupSuitUI() end
---@alias game-Scripts-PowersLogic.SetupSuitUI ...

function game.SetupTorchAutofire(a, b) end
---@alias game-Scripts-PowersLogic.SetupTorchAutofire ...

function game.SkullImpulseTransform(a, b, c) end
---@alias game-Scripts-PowersLogic.SkullImpulseTransform ...

function game.SpawnSelfBloodDrop(a, b, c) end
---@alias game-Scripts-PowersLogic.SpawnSelfBloodDrop ...

function game.SplitSelfBuff(a, b, c) end
---@alias game-Scripts-PowersLogic.SplitSelfBuff ...

function game.SprintShieldEndPresentation() end
---@alias game-Scripts-PowersLogic.SprintShieldEndPresentation ...

function game.SprintShieldPresentation() end
---@alias game-Scripts-PowersLogic.SprintShieldPresentation ...

function game.SprintShieldSetup(a, b, c) end
---@alias game-Scripts-PowersLogic.SprintShieldSetup ...

function game.StaffEXHitHeal(a, b, c) end
---@alias game-Scripts-PowersLogic.StaffEXHitHeal ...

function game.StartAresSprintProjectile(a, b, c) end
---@alias game-Scripts-PowersLogic.StartAresSprintProjectile ...

function game.StartAxeSturdy(a, b) end
---@alias game-Scripts-PowersLogic.StartAxeSturdy ...

function game.StartCastRepeatThread(a, b) end
---@alias game-Scripts-PowersLogic.StartCastRepeatThread ...

function game.StartChaosTimer(a, b) end
---@alias game-Scripts-PowersLogic.StartChaosTimer ...

function game.StartHermesKeepsakeTimer(a, b) end
---@alias game-Scripts-PowersLogic.StartHermesKeepsakeTimer ...

function game.StartLobSturdy(a, b, c) end
---@alias game-Scripts-PowersLogic.StartLobSturdy ...

function game.StartPrimaryRepeatThread(a, b) end
---@alias game-Scripts-PowersLogic.StartPrimaryRepeatThread ...

function game.StartSpecialRepeatThread(a, b, c, d, e) end
---@alias game-Scripts-PowersLogic.StartSpecialRepeatThread ...

function game.StartSprintPhasing(a, b) end
---@alias game-Scripts-PowersLogic.StartSprintPhasing ...

function game.StartTorchRepeatDetonationThread(a, b, c) end
---@alias game-Scripts-PowersLogic.StartTorchRepeatDetonationThread ...

function game.StasisStunApply(a) end
---@alias game-Scripts-PowersLogic.StasisStunApply ...

function game.StasisStunClear(a) end
---@alias game-Scripts-PowersLogic.StasisStunClear ...

function game.TemporaryMuteStunImmunity(a, b) end
---@alias game-Scripts-PowersLogic.TemporaryMuteStunImmunity ...

function game.ThreadedPerfectDamageReset(a) end
---@alias game-Scripts-PowersLogic.ThreadedPerfectDamageReset ...

function game.TimedBuffSetup(a, b) end
---@alias game-Scripts-PowersLogic.TimedBuffSetup ...

function game.TimeElementalHealApply(a) end
---@alias game-Scripts-PowersLogic.TimeElementalHealApply ...

function game.TimeSlowApply(a) end
---@alias game-Scripts-PowersLogic.TimeSlowApply ...

function game.TimeSlowClear(a) end
---@alias game-Scripts-PowersLogic.TimeSlowClear ...

function game.TimeSlowUpdate(a) end
---@alias game-Scripts-PowersLogic.TimeSlowUpdate ...

function game.TorchPrimaryAutofire(a) end
---@alias game-Scripts-PowersLogic.TorchPrimaryAutofire ...

function game.TorchSpecialAutofire(a) end
---@alias game-Scripts-PowersLogic.TorchSpecialAutofire ...

function game.TorchSprintRecall(a, b, c) end
---@alias game-Scripts-PowersLogic.TorchSprintRecall ...

function game.TraitReserveMana(a, b) end
---@alias game-Scripts-PowersLogic.TraitReserveMana ...

function game.TraitUnreserveMana(a) end
---@alias game-Scripts-PowersLogic.TraitUnreserveMana ...

function game.UpdateBloodDropSpeed(a, b) end
---@alias game-Scripts-PowersLogic.UpdateBloodDropSpeed ...

function game.UpdateLastMomentManaRestoreEligibility() end
---@alias game-Scripts-PowersLogic.UpdateLastMomentManaRestoreEligibility ...

function game.UpdateProjectileLedger(a, b) end
---@alias game-Scripts-PowersLogic.UpdateProjectileLedger ...

function game.UpgradeHammers(a) end
---@alias game-Scripts-PowersLogic.UpgradeHammers ...

function game.WeakCrowdMana(a, b) end
---@alias game-Scripts-PowersLogic.WeakCrowdMana ...

function game.ZeusManaPickup(a, b, c) end
---@alias game-Scripts-PowersLogic.ZeusManaPickup ...

function game.ZeusRetaliate(a, b) end
---@alias game-Scripts-PowersLogic.ZeusRetaliate ...

function game.ZeusSprintSpend(a) end
---@alias game-Scripts-PowersLogic.ZeusSprintSpend ...

function game.ZeusSprintZap(a, b, c) end
---@alias game-Scripts-PowersLogic.ZeusSprintZap ...

return game