---@meta game-Scripts-PresentationBiomeH
local game = {}

function game.CerberusStageEnter(a, b, c) end
---@alias game-Scripts-PresentationBiomeH.CerberusStageEnter ...

function game.CerberusStageExit(a, b, c) end
---@alias game-Scripts-PresentationBiomeH.CerberusStageExit ...

function game.EchoPostChoicePresentation(a, b) end
---@alias game-Scripts-PresentationBiomeH.EchoPostChoicePresentation ...

function game.FieldsBridgeCharonMusic() end
---@alias game-Scripts-PresentationBiomeH.FieldsBridgeCharonMusic ...

function game.FieldsBridgeEchoMusic() end
---@alias game-Scripts-PresentationBiomeH.FieldsBridgeEchoMusic ...

function game.FieldsEncounterActivatedPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeH.FieldsEncounterActivatedPresentation ...

function game.FieldsEncounterEndPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeH.FieldsEncounterEndPresentation ...

function game.FieldsEncounterStartPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeH.FieldsEncounterStartPresentation ...

function game.FieldsExitsReadyPresentation(a) end
---@alias game-Scripts-PresentationBiomeH.FieldsExitsReadyPresentation ...

function game.FieldsLeaveRoomPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeH.FieldsLeaveRoomPresentation ...

function game.FieldsRoomEntrancePresentation(a, b) end
---@alias game-Scripts-PresentationBiomeH.FieldsRoomEntrancePresentation ...

function game.GhostWallCollidePresentation(a, b) end
---@alias game-Scripts-PresentationBiomeH.GhostWallCollidePresentation ...

function game.H_ReloadHideGhostWalls(a, b) end
---@alias game-Scripts-PresentationBiomeH.H_ReloadHideGhostWalls ...

function game.InfestedCerberusHorribleRaceConditionForTempPresentation(a) end
---@alias game-Scripts-PresentationBiomeH.InfestedCerberusHorribleRaceConditionForTempPresentation ...

function game.InfestedCerberusKillPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeH.InfestedCerberusKillPresentation ...

function game.InfestedCerberusSetupPresentation(a) end
---@alias game-Scripts-PresentationBiomeH.InfestedCerberusSetupPresentation ...

function game.InfestedCerberusSpawnPostEndingPresentation(a) end
---@alias game-Scripts-PresentationBiomeH.InfestedCerberusSpawnPostEndingPresentation ...

function game.InfestedCerberusSpawnPresentation(a) end
---@alias game-Scripts-PresentationBiomeH.InfestedCerberusSpawnPresentation ...

function game.LeaveRoomHBossPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeH.LeaveRoomHBossPresentation ...

function game.LeaveRoomHPostBossPresentation(a, b, c) end
---@alias game-Scripts-PresentationBiomeH.LeaveRoomHPostBossPresentation ...

function game.OnMixerHBossAdded(a, b, c, d) end
---@alias game-Scripts-PresentationBiomeH.OnMixerHBossAdded ...

function game.RoomEntranceBossFields(a, b, c) end
---@alias game-Scripts-PresentationBiomeH.RoomEntranceBossFields ...

function game.RoomEntrancePortalFields(a, b) end
---@alias game-Scripts-PresentationBiomeH.RoomEntrancePortalFields ...

function game.UseFieldsRewardFinderPresentation(a) end
---@alias game-Scripts-PresentationBiomeH.UseFieldsRewardFinderPresentation ...

function game.WheatHit(a, b) end
---@alias game-Scripts-PresentationBiomeH.WheatHit ...

return game