---@meta game-Scripts-PresentationBiomeP
local game = {}

function game.BiomeBackToRoomOlympus(a, b) end
---@alias game-Scripts-PresentationBiomeP.BiomeBackToRoomOlympus ...

function game.BiomeOverlookOlympus(a, b) end
---@alias game-Scripts-PresentationBiomeP.BiomeOverlookOlympus ...

function game.DionysusBathHouseEndPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeP.DionysusBathHouseEndPresentation ...

function game.DionysusBathHouseStartPresentation(a, b, c) end
---@alias game-Scripts-PresentationBiomeP.DionysusBathHouseStartPresentation ...

function game.DionysusChoiceScreenPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeP.DionysusChoiceScreenPresentation ...

function game.DionysusMusicManager(a, b) end
---@alias game-Scripts-PresentationBiomeP.DionysusMusicManager ...

function game.DionysusRandomizeLeopards(a, b) end
---@alias game-Scripts-PresentationBiomeP.DionysusRandomizeLeopards ...

function game.EagleBattleStart(a, b) end
---@alias game-Scripts-PresentationBiomeP.EagleBattleStart ...

function game.HeraclesIntroPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeP.HeraclesIntroPresentation ...

function game.HeraclesKillPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeP.HeraclesKillPresentation ...

function game.HeraclesMemoryBreak(a, b) end
---@alias game-Scripts-PresentationBiomeP.HeraclesMemoryBreak ...

function game.OlympusChronosPortalExitPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeP.OlympusChronosPortalExitPresentation ...

function game.OlympusEagleFirstSpawnPresentation(a) end
---@alias game-Scripts-PresentationBiomeP.OlympusEagleFirstSpawnPresentation ...

function game.OlympusEaglePreSpawnPresentation() end
---@alias game-Scripts-PresentationBiomeP.OlympusEaglePreSpawnPresentation ...

function game.OlympusEagleSpawnPresentation(a) end
---@alias game-Scripts-PresentationBiomeP.OlympusEagleSpawnPresentation ...

function game.OlympusOverlookFadeInObjects() end
---@alias game-Scripts-PresentationBiomeP.OlympusOverlookFadeInObjects ...

function game.OlympusOverlookFadeOutObjects() end
---@alias game-Scripts-PresentationBiomeP.OlympusOverlookFadeOutObjects ...

function game.OlympusSkyExitPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeP.OlympusSkyExitPresentation ...

function game.OlympusTremorPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeP.OlympusTremorPresentation ...

function game.PlayPrometheusTauntAnim(a, b) end
---@alias game-Scripts-PresentationBiomeP.PlayPrometheusTauntAnim ...

function game.PrometheusBattleStart(a, b) end
---@alias game-Scripts-PresentationBiomeP.PrometheusBattleStart ...

function game.PrometheusBossDreamRunIntro(a, b) end
---@alias game-Scripts-PresentationBiomeP.PrometheusBossDreamRunIntro ...

function game.PrometheusEagleEntrance(a, b, c) end
---@alias game-Scripts-PresentationBiomeP.PrometheusEagleEntrance ...

function game.PrometheusForesightPresentation(a, b, c) end
---@alias game-Scripts-PresentationBiomeP.PrometheusForesightPresentation ...

function game.PrometheusKillPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeP.PrometheusKillPresentation ...

function game.PrometheusMemoryIntroPresentation(a, b, c, d) end
---@alias game-Scripts-PresentationBiomeP.PrometheusMemoryIntroPresentation ...

function game.PrometheusMemoryOnHit(a, b, c) end
---@alias game-Scripts-PresentationBiomeP.PrometheusMemoryOnHit ...

function game.PrometheusMemoryOutroPresentation(a, b, c, d) end
---@alias game-Scripts-PresentationBiomeP.PrometheusMemoryOutroPresentation ...

function game.PrometheusSummonPresentation(a, b, c, d) end
---@alias game-Scripts-PresentationBiomeP.PrometheusSummonPresentation ...

function game.RoomEntranceBossPrometheus(a, b, c) end
---@alias game-Scripts-PresentationBiomeP.RoomEntranceBossPrometheus ...

function game.SatyrGuestHitPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeP.SatyrGuestHitPresentation ...

function game.SetupHeraclesForBathHouse(a, b) end
---@alias game-Scripts-PresentationBiomeP.SetupHeraclesForBathHouse ...

function game.SpawnOlympusCorpses(a, b) end
---@alias game-Scripts-PresentationBiomeP.SpawnOlympusCorpses ...

function game.UseGodStatueTrapPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeP.UseGodStatueTrapPresentation ...

return game