---@meta game-Scripts-PresentationBiomeG
local game = {}

function game.CharybdisGrowl(a, b) end
---@alias game-Scripts-PresentationBiomeG.CharybdisGrowl ...

function game.CharybdisRevealPresentation(a) end
---@alias game-Scripts-PresentationBiomeG.CharybdisRevealPresentation ...

function game.CharybdisScyllaFightStartPresentation(a) end
---@alias game-Scripts-PresentationBiomeG.CharybdisScyllaFightStartPresentation ...

function game.CharybdisTentacleHidePresentation(a) end
---@alias game-Scripts-PresentationBiomeG.CharybdisTentacleHidePresentation ...

function game.CharybdisTentacleSurfacePresentation(a, b, c) end
---@alias game-Scripts-PresentationBiomeG.CharybdisTentacleSurfacePresentation ...

function game.CrawlerMiniBossKillPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeG.CrawlerMiniBossKillPresentation ...

function game.EnterBiomeGRoomPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeG.EnterBiomeGRoomPresentation ...

function game.ExitBiomeGRoomPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeG.ExitBiomeGRoomPresentation ...

function game.FlashRoomFire(a, b) end
---@alias game-Scripts-PresentationBiomeG.FlashRoomFire ...

function game.FlashRoomLights(a, b) end
---@alias game-Scripts-PresentationBiomeG.FlashRoomLights ...

function game.FloodEncounterStartEndAudio() end
---@alias game-Scripts-PresentationBiomeG.FloodEncounterStartEndAudio ...

function game.FloodEncounterStartPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeG.FloodEncounterStartPresentation ...

function game.FloodTrapFireEndPresentation() end
---@alias game-Scripts-PresentationBiomeG.FloodTrapFireEndPresentation ...

function game.FloodTrapFireStartPresentation(a) end
---@alias game-Scripts-PresentationBiomeG.FloodTrapFireStartPresentation ...

function game.NarcissusAdmirerHeartPresentation(a) end
---@alias game-Scripts-PresentationBiomeG.NarcissusAdmirerHeartPresentation ...

function game.NarcissusAdmirersPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeG.NarcissusAdmirersPresentation ...

function game.NarcissusPostChoicePresentation(a, b) end
---@alias game-Scripts-PresentationBiomeG.NarcissusPostChoicePresentation ...

function game.PlayScyllaTauntAnim(a, b) end
---@alias game-Scripts-PresentationBiomeG.PlayScyllaTauntAnim ...

function game.ResetScyllaMusicStem(a, b) end
---@alias game-Scripts-PresentationBiomeG.ResetScyllaMusicStem ...

function game.RestoreSirenMusic(a) end
---@alias game-Scripts-PresentationBiomeG.RestoreSirenMusic ...

function game.RoomEntranceBoss02BiomeG(a, b, c) end
---@alias game-Scripts-PresentationBiomeG.RoomEntranceBoss02BiomeG ...

function game.RoomEntranceBoss02TentaclePresentation(a, b, c) end
---@alias game-Scripts-PresentationBiomeG.RoomEntranceBoss02TentaclePresentation ...

function game.RoomEntranceBossBiomeG(a, b, c) end
---@alias game-Scripts-PresentationBiomeG.RoomEntranceBossBiomeG ...

function game.RoomEntranceCrawlerMiniBoss(a, b) end
---@alias game-Scripts-PresentationBiomeG.RoomEntranceCrawlerMiniBoss ...

function game.ScyllaActivatePresentation(a) end
---@alias game-Scripts-PresentationBiomeG.ScyllaActivatePresentation ...

function game.ScyllaBossDreamRunIntro(a) end
---@alias game-Scripts-PresentationBiomeG.ScyllaBossDreamRunIntro ...

function game.ScyllaFinalStandPresentation() end
---@alias game-Scripts-PresentationBiomeG.ScyllaFinalStandPresentation ...

function game.ScyllaKillPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeG.ScyllaKillPresentation ...

function game.ScyllaNewSongPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeG.ScyllaNewSongPresentation ...

function game.ScyllaQuestPearlPresentation(a, b, c) end
---@alias game-Scripts-PresentationBiomeG.ScyllaQuestPearlPresentation ...

function game.ScyllaSpotlightPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeG.ScyllaSpotlightPresentation ...

function game.SetupScyllaFan(a) end
---@alias game-Scripts-PresentationBiomeG.SetupScyllaFan ...

function game.SetupStageLights(a) end
---@alias game-Scripts-PresentationBiomeG.SetupStageLights ...

function game.SirenKillPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeG.SirenKillPresentation ...

function game.SirenKillScreenEffects(a, b) end
---@alias game-Scripts-PresentationBiomeG.SirenKillScreenEffects ...

function game.SoloSirenDrummer(a) end
---@alias game-Scripts-PresentationBiomeG.SoloSirenDrummer ...

function game.SoloSirenKeytarist(a) end
---@alias game-Scripts-PresentationBiomeG.SoloSirenKeytarist ...

function game.SoloSirenVocalist(a) end
---@alias game-Scripts-PresentationBiomeG.SoloSirenVocalist ...

function game.SummonOdysseus(a, b) end
---@alias game-Scripts-PresentationBiomeG.SummonOdysseus ...

function game.UnSummonOdysseus(a, b) end
---@alias game-Scripts-PresentationBiomeG.UnSummonOdysseus ...

function game.UseScyllaPearl(a, b, c) end
---@alias game-Scripts-PresentationBiomeG.UseScyllaPearl ...

return game