---@meta game-Scripts-PresentationBiomeQ
local game = {}

function game.ActivateApollo() end
---@alias game-Scripts-PresentationBiomeQ.ActivateApollo ...

function game.ActivatePalaceExitPoint(a, b) end
---@alias game-Scripts-PresentationBiomeQ.ActivatePalaceExitPoint ...

function game.AttackTyphonHint(a, b) end
---@alias game-Scripts-PresentationBiomeQ.AttackTyphonHint ...

function game.BiomeBackToRoomQPostBoss(a, b) end
---@alias game-Scripts-PresentationBiomeQ.BiomeBackToRoomQPostBoss ...

function game.BiomeBackToRoomTyphon(a, b) end
---@alias game-Scripts-PresentationBiomeQ.BiomeBackToRoomTyphon ...

function game.BiomeOverlookQPostBoss(a, b) end
---@alias game-Scripts-PresentationBiomeQ.BiomeOverlookQPostBoss ...

function game.BiomeOverlookTyphon(a, b) end
---@alias game-Scripts-PresentationBiomeQ.BiomeOverlookTyphon ...

function game.BiomeOverlookTyphonCreature(a, b) end
---@alias game-Scripts-PresentationBiomeQ.BiomeOverlookTyphonCreature ...

function game.BiomeOverlookTyphonThread(a, b) end
---@alias game-Scripts-PresentationBiomeQ.BiomeOverlookTyphonThread ...

function game.BiomeQBossExitPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeQ.BiomeQBossExitPresentation ...

function game.BiomeQLeaveRoomPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeQ.BiomeQLeaveRoomPresentation ...

function game.BlockDemeterInteraction(a, b) end
---@alias game-Scripts-PresentationBiomeQ.BlockDemeterInteraction ...

function game.CheckTyphonReward(a, b) end
---@alias game-Scripts-PresentationBiomeQ.CheckTyphonReward ...

function game.DisablePalaceForcefield(a, b) end
---@alias game-Scripts-PresentationBiomeQ.DisablePalaceForcefield ...

function game.EndChronosScreenBlock(a, b) end
---@alias game-Scripts-PresentationBiomeQ.EndChronosScreenBlock ...

function game.FakeDeathTyphonEntrance(a, b, c) end
---@alias game-Scripts-PresentationBiomeQ.FakeDeathTyphonEntrance ...

function game.FlockOfBirds() end
---@alias game-Scripts-PresentationBiomeQ.FlockOfBirds ...

function game.FortressMainDoorOpenPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeQ.FortressMainDoorOpenPresentation ...

function game.OlympianSaluteResponse() end
---@alias game-Scripts-PresentationBiomeQ.OlympianSaluteResponse ...

function game.PauseApolloSinging(a, b) end
---@alias game-Scripts-PresentationBiomeQ.PauseApolloSinging ...

function game.RestoreDemeterInteraction() end
---@alias game-Scripts-PresentationBiomeQ.RestoreDemeterInteraction ...

function game.RestoreMelRun(a, b) end
---@alias game-Scripts-PresentationBiomeQ.RestoreMelRun ...

function game.ResumeApolloSinging(a, b) end
---@alias game-Scripts-PresentationBiomeQ.ResumeApolloSinging ...

function game.RoomEntranceBossTwins(a, b, c) end
---@alias game-Scripts-PresentationBiomeQ.RoomEntranceBossTwins ...

function game.RoomEntranceTyphonHead(a, b, c) end
---@alias game-Scripts-PresentationBiomeQ.RoomEntranceTyphonHead ...

function game.RoomEntranceTyphonHeadEM(a, b, c) end
---@alias game-Scripts-PresentationBiomeQ.RoomEntranceTyphonHeadEM ...

function game.SetupApolloMusic(a, b) end
---@alias game-Scripts-PresentationBiomeQ.SetupApolloMusic ...

function game.SetupMelWalk(a, b) end
---@alias game-Scripts-PresentationBiomeQ.SetupMelWalk ...

function game.SetupPalaceExitPoint(a, b) end
---@alias game-Scripts-PresentationBiomeQ.SetupPalaceExitPoint ...

function game.SetupPalaceForcefield(a, b) end
---@alias game-Scripts-PresentationBiomeQ.SetupPalaceForcefield ...

function game.SetupZeusHeraFinalInteraction(a, b) end
---@alias game-Scripts-PresentationBiomeQ.SetupZeusHeraFinalInteraction ...

function game.TyphonCameraRaindropsPresentation(a) end
---@alias game-Scripts-PresentationBiomeQ.TyphonCameraRaindropsPresentation ...

function game.TyphonChronosStageTransition(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonChronosStageTransition ...

function game.TyphonFakeDeathKillPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonFakeDeathKillPresentation ...

function game.TyphonFakeDeathTransition(a, b, c) end
---@alias game-Scripts-PresentationBiomeQ.TyphonFakeDeathTransition ...

function game.TyphonHeadArmWeapon(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonHeadArmWeapon ...

function game.TyphonHeadCannonPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonHeadCannonPresentation ...

function game.TyphonHeadGustPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonHeadGustPresentation ...

function game.TyphonHeadHealthBarPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonHeadHealthBarPresentation ...

function game.TyphonHeadKillPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonHeadKillPresentation ...

function game.TyphonHeadRoarPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonHeadRoarPresentation ...

function game.TyphonHeadStageTransition(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonHeadStageTransition ...

function game.TyphonHeadStageTransitionEM(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonHeadStageTransitionEM ...

function game.TyphonHeadStageTransitionOlympianEffects(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonHeadStageTransitionOlympianEffects ...

function game.TyphonHeadSummonPresentation(a, b, c, d) end
---@alias game-Scripts-PresentationBiomeQ.TyphonHeadSummonPresentation ...

function game.TyphonHeadSummonPresentationEarlyEnd(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonHeadSummonPresentationEarlyEnd ...

function game.TyphonHeadTailWeapon(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonHeadTailWeapon ...

function game.TyphonHeadVolleyPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonHeadVolleyPresentation ...

function game.TyphonIncursionArmFlick(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonIncursionArmFlick ...

function game.TyphonIncursionArmSlam(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonIncursionArmSlam ...

function game.TyphonIncursionTailImpale(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonIncursionTailImpale ...

function game.TyphonSpeakingEndPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonSpeakingEndPresentation ...

function game.TyphonSpeakingPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonSpeakingPresentation ...

function game.TyphonSpecialKillPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonSpecialKillPresentation ...

function game.TyphonTailAmbushSetup(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonTailAmbushSetup ...

function game.TyphonTremorPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeQ.TyphonTremorPresentation ...

function game.UseDummyLoot(a, b, c) end
---@alias game-Scripts-PresentationBiomeQ.UseDummyLoot ...

return game