---@meta game-Scripts-PresentationBiomeO
local game = {}

function game.BiomeBackToRoomShips(a, b) end
---@alias game-Scripts-PresentationBiomeO.BiomeBackToRoomShips ...

function game.BiomeOverlookShips(a, b) end
---@alias game-Scripts-PresentationBiomeO.BiomeOverlookShips ...

function game.BiomeOverlookShipsFadeIdsIn() end
---@alias game-Scripts-PresentationBiomeO.BiomeOverlookShipsFadeIdsIn ...

function game.BiomeOverlookShipsFadeIdsOut() end
---@alias game-Scripts-PresentationBiomeO.BiomeOverlookShipsFadeIdsOut ...

function game.CirceBlessingPostChoicePresentation(a, b) end
---@alias game-Scripts-PresentationBiomeO.CirceBlessingPostChoicePresentation ...

function game.CirceBlessingPreChoicePresentation(a, b) end
---@alias game-Scripts-PresentationBiomeO.CirceBlessingPreChoicePresentation ...

function game.DestroyShipWheelPresentation(a) end
---@alias game-Scripts-PresentationBiomeO.DestroyShipWheelPresentation ...

function game.DouseFire(a) end
---@alias game-Scripts-PresentationBiomeO.DouseFire ...

function game.ErisBossDreamRunIntro(a, b) end
---@alias game-Scripts-PresentationBiomeO.ErisBossDreamRunIntro ...

function game.ErisFlyByPresentation(a, b, c, d) end
---@alias game-Scripts-PresentationBiomeO.ErisFlyByPresentation ...

function game.ErisKillPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeO.ErisKillPresentation ...

function game.ErisSelfBuffApply(a) end
---@alias game-Scripts-PresentationBiomeO.ErisSelfBuffApply ...

function game.ErisSelfBuffClear(a) end
---@alias game-Scripts-PresentationBiomeO.ErisSelfBuffClear ...

function game.GustWindBoss(a) end
---@alias game-Scripts-PresentationBiomeO.GustWindBoss ...

function game.GustWinds(a) end
---@alias game-Scripts-PresentationBiomeO.GustWinds ...

function game.MuteSpeaker(a) end
---@alias game-Scripts-PresentationBiomeO.MuteSpeaker ...

function game.MuteSpeakerPermanent(a) end
---@alias game-Scripts-PresentationBiomeO.MuteSpeakerPermanent ...

function game.PlayErisTauntAnim(a, b) end
---@alias game-Scripts-PresentationBiomeO.PlayErisTauntAnim ...

function game.RoomEntranceBossShips(a, b, c) end
---@alias game-Scripts-PresentationBiomeO.RoomEntranceBossShips ...

function game.RoomEntranceCharybdis(a, b) end
---@alias game-Scripts-PresentationBiomeO.RoomEntranceCharybdis ...

function game.ShipsEndOilFires() end
---@alias game-Scripts-PresentationBiomeO.ShipsEndOilFires ...

function game.ShipsExitsUnlockedPresentation() end
---@alias game-Scripts-PresentationBiomeO.ShipsExitsUnlockedPresentation ...

function game.ShipsLeaveRoomPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeO.ShipsLeaveRoomPresentation ...

function game.ShipsRoomEntrancePresentation(a, b, c) end
---@alias game-Scripts-PresentationBiomeO.ShipsRoomEntrancePresentation ...

function game.ShipsSteeringWheelChoicePresentation(a) end
---@alias game-Scripts-PresentationBiomeO.ShipsSteeringWheelChoicePresentation ...

function game.ShipsSteeringWheelSelectionPresentation(a) end
---@alias game-Scripts-PresentationBiomeO.ShipsSteeringWheelSelectionPresentation ...

function game.ShipWheelEnd(a) end
---@alias game-Scripts-PresentationBiomeO.ShipWheelEnd ...

function game.ShipWheelUsedPresentation(a) end
---@alias game-Scripts-PresentationBiomeO.ShipWheelUsedPresentation ...

function game.UnmuteSpeakerPermanent(a) end
---@alias game-Scripts-PresentationBiomeO.UnmuteSpeakerPermanent ...

function game.UseShipWheelForward(a) end
---@alias game-Scripts-PresentationBiomeO.UseShipWheelForward ...

function game.UseShipWheelLeft(a) end
---@alias game-Scripts-PresentationBiomeO.UseShipWheelLeft ...

function game.UseShipWheelRight(a) end
---@alias game-Scripts-PresentationBiomeO.UseShipWheelRight ...

return game