---@meta game-Scripts-PresentationBiomeI
local game = {}

function game.AttemptPetCerberusThread(a) end
---@alias game-Scripts-PresentationBiomeI.AttemptPetCerberusThread ...

function game.BedroomToChronosSanctumPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.BedroomToChronosSanctumPresentation ...

function game.BlockAchillesInteraction(a, b) end
---@alias game-Scripts-PresentationBiomeI.BlockAchillesInteraction ...

function game.ChariotDeparturePresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.ChariotDeparturePresentation ...

function game.ChronosBattleStart(a, b) end
---@alias game-Scripts-PresentationBiomeI.ChronosBattleStart ...

function game.ChronosGigarosKillPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.ChronosGigarosKillPresentation ...

function game.ChronosKillPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.ChronosKillPresentation ...

function game.ChronosMinorStageTransition(a, b, c) end
---@alias game-Scripts-PresentationBiomeI.ChronosMinorStageTransition ...

function game.ChronosPhaseTransition(a, b, c) end
---@alias game-Scripts-PresentationBiomeI.ChronosPhaseTransition ...

function game.ChronosPostCombatReload(a, b) end
---@alias game-Scripts-PresentationBiomeI.ChronosPostCombatReload ...

function game.ChronosRemainsEnterTriggerPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.ChronosRemainsEnterTriggerPresentation ...

function game.ChronosRemainsLeaveTriggerPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.ChronosRemainsLeaveTriggerPresentation ...

function game.ChronosRemainsPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.ChronosRemainsPresentation ...

function game.ChronosSanctumExitPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.ChronosSanctumExitPresentation ...

function game.ChronosSpecialKillPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.ChronosSpecialKillPresentation ...

function game.ChronosThronePresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.ChronosThronePresentation ...

function game.CreditsSecretMusicOff() end
---@alias game-Scripts-PresentationBiomeI.CreditsSecretMusicOff ...

function game.DeathAreaRestorationIllustrationPresentation() end
---@alias game-Scripts-PresentationBiomeI.DeathAreaRestorationIllustrationPresentation ...

function game.DeathAreaRestorationPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.DeathAreaRestorationPresentation ...

function game.DeathAreaRestoredEntrance(a, b) end
---@alias game-Scripts-PresentationBiomeI.DeathAreaRestoredEntrance ...

function game.DeathAreaRestoredEntranceLetterboxFade() end
---@alias game-Scripts-PresentationBiomeI.DeathAreaRestoredEntranceLetterboxFade ...

function game.DeathAreaRestoredToCreditsPresentation() end
---@alias game-Scripts-PresentationBiomeI.DeathAreaRestoredToCreditsPresentation ...

function game.DeathAreaRestoredUpdateHallwayBlocks(a, b) end
---@alias game-Scripts-PresentationBiomeI.DeathAreaRestoredUpdateHallwayBlocks ...

function game.DreamBedPresentation(a, b, c) end
---@alias game-Scripts-PresentationBiomeI.DreamBedPresentation ...

function game.DreamSpeechPresentation() end
---@alias game-Scripts-PresentationBiomeI.DreamSpeechPresentation ...

function game.EndCreditConstellationBloom() end
---@alias game-Scripts-PresentationBiomeI.EndCreditConstellationBloom ...

function game.EndCreditsDebugTimer() end
---@alias game-Scripts-PresentationBiomeI.EndCreditsDebugTimer ...

function game.EndCreditsExitTimer() end
---@alias game-Scripts-PresentationBiomeI.EndCreditsExitTimer ...

function game.EndCreditsSetupBirds() end
---@alias game-Scripts-PresentationBiomeI.EndCreditsSetupBirds ...

function game.EndingCreditsPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.EndingCreditsPresentation ...

function game.EnsembleFamilyEnterPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.EnsembleFamilyEnterPresentation ...

function game.EnsembleRidersEnterPresentation(a) end
---@alias game-Scripts-PresentationBiomeI.EnsembleRidersEnterPresentation ...

function game.FailToPetCerberus(a) end
---@alias game-Scripts-PresentationBiomeI.FailToPetCerberus ...

function game.FamilyRescuePresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.FamilyRescuePresentation ...

function game.GigarosSpellPresentation(a, b, c) end
---@alias game-Scripts-PresentationBiomeI.GigarosSpellPresentation ...

function game.HadesOfficialDecree() end
---@alias game-Scripts-PresentationBiomeI.HadesOfficialDecree ...

function game.HandleEndingCreditsWrapping(a, b) end
---@alias game-Scripts-PresentationBiomeI.HandleEndingCreditsWrapping ...

function game.HouseFrontDoorUsedPresentation(a, b, c) end
---@alias game-Scripts-PresentationBiomeI.HouseFrontDoorUsedPresentation ...

function game.LeaveRoomIPreBoss01Presentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.LeaveRoomIPreBoss01Presentation ...

function game.LeaveRoomIPreBoss02Presentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.LeaveRoomIPreBoss02Presentation ...

function game.MelBackToBedroomPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.MelBackToBedroomPresentation ...

function game.MirrorOffPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.MirrorOffPresentation ...

function game.MirrorOnPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.MirrorOnPresentation ...

function game.NyxFarewellPresentation(a) end
---@alias game-Scripts-PresentationBiomeI.NyxFarewellPresentation ...

function game.PetCerberus(a) end
---@alias game-Scripts-PresentationBiomeI.PetCerberus ...

function game.PingHadesSpear(a, b) end
---@alias game-Scripts-PresentationBiomeI.PingHadesSpear ...

function game.PlayZagreusTauntAnim(a, b) end
---@alias game-Scripts-PresentationBiomeI.PlayZagreusTauntAnim ...

function game.RestoreAchillesInteraction() end
---@alias game-Scripts-PresentationBiomeI.RestoreAchillesInteraction ...

function game.RoomEntranceChronos(a, b, c) end
---@alias game-Scripts-PresentationBiomeI.RoomEntranceChronos ...

function game.RoomEntranceEndCredits(a, b, c) end
---@alias game-Scripts-PresentationBiomeI.RoomEntranceEndCredits ...

function game.RoomEntranceIChronosFlashback(a, b) end
---@alias game-Scripts-PresentationBiomeI.RoomEntranceIChronosFlashback ...

function game.RoomEntranceIPostBoss(a, b) end
---@alias game-Scripts-PresentationBiomeI.RoomEntranceIPostBoss ...

function game.SatyrBattleSounds() end
---@alias game-Scripts-PresentationBiomeI.SatyrBattleSounds ...

function game.SetupEndingCredits() end
---@alias game-Scripts-PresentationBiomeI.SetupEndingCredits ...

function game.SetupEndSceneZoom(a) end
---@alias game-Scripts-PresentationBiomeI.SetupEndSceneZoom ...

function game.SetupFamilyRescueCamera(a, b) end
---@alias game-Scripts-PresentationBiomeI.SetupFamilyRescueCamera ...

function game.ShowEndCreditsConstellation(a) end
---@alias game-Scripts-PresentationBiomeI.ShowEndCreditsConstellation ...

function game.SpawnCredit(a, b, c) end
---@alias game-Scripts-PresentationBiomeI.SpawnCredit ...

function game.StartFinalBossChronos(a, b) end
---@alias game-Scripts-PresentationBiomeI.StartFinalBossChronos ...

function game.StartFinalBossChronosIntroMusic() end
---@alias game-Scripts-PresentationBiomeI.StartFinalBossChronosIntroMusic ...

function game.StartFinalBossChronosMusic() end
---@alias game-Scripts-PresentationBiomeI.StartFinalBossChronosMusic ...

function game.StartTrueEndingMusic() end
---@alias game-Scripts-PresentationBiomeI.StartTrueEndingMusic ...

function game.StartZagreusBossFight() end
---@alias game-Scripts-PresentationBiomeI.StartZagreusBossFight ...

function game.SummonFamilyMembers(a, b) end
---@alias game-Scripts-PresentationBiomeI.SummonFamilyMembers ...

function game.SummonNeoChronos(a, b) end
---@alias game-Scripts-PresentationBiomeI.SummonNeoChronos ...

function game.TartarusChamberMoverPresentation(a, b, c) end
---@alias game-Scripts-PresentationBiomeI.TartarusChamberMoverPresentation ...

function game.TimeMirrorPresentation(a, b, c) end
---@alias game-Scripts-PresentationBiomeI.TimeMirrorPresentation ...

function game.TwinsEntrancePresentation(a) end
---@alias game-Scripts-PresentationBiomeI.TwinsEntrancePresentation ...

function game.TwinsSingingStart(a, b) end
---@alias game-Scripts-PresentationBiomeI.TwinsSingingStart ...

function game.UnSummonNeoChronos(a, b) end
---@alias game-Scripts-PresentationBiomeI.UnSummonNeoChronos ...

function game.UseHadesSpearPresentation(a, b, c) end
---@alias game-Scripts-PresentationBiomeI.UseHadesSpearPresentation ...

function game.ZagreusSpearEquipPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeI.ZagreusSpearEquipPresentation ...

return game