---@meta game-Scripts-PresentationBiomeN
local game = {}

function game.ChooseMedeaIntroPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeN.ChooseMedeaIntroPresentation ...

function game.DestroyEphyraBarrier(a, b) end
---@alias game-Scripts-PresentationBiomeN.DestroyEphyraBarrier ...

function game.EphyraZoomOut(a) end
---@alias game-Scripts-PresentationBiomeN.EphyraZoomOut ...

function game.EphyraZoomOutDoorSort(a, b) end
---@alias game-Scripts-PresentationBiomeN.EphyraZoomOutDoorSort ...

function game.FirstPylonHubReturnPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeN.FirstPylonHubReturnPresentation ...

function game.FirstPylonHubReturnPresentationEnd(a, b) end
---@alias game-Scripts-PresentationBiomeN.FirstPylonHubReturnPresentationEnd ...

function game.HandleNHubWingDimmers(a, b) end
---@alias game-Scripts-PresentationBiomeN.HandleNHubWingDimmers ...

function game.HubCombatRoomEntrance(a, b) end
---@alias game-Scripts-PresentationBiomeN.HubCombatRoomEntrance ...

function game.MedeaCursePostChoicePresentation(a, b) end
---@alias game-Scripts-PresentationBiomeN.MedeaCursePostChoicePresentation ...

function game.MedeaIntroPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeN.MedeaIntroPresentation ...

function game.MedeaIntroPresentation_AlreadyPresent(a, b) end
---@alias game-Scripts-PresentationBiomeN.MedeaIntroPresentation_AlreadyPresent ...

function game.PlayPolyphemusTauntAnim(a, b) end
---@alias game-Scripts-PresentationBiomeN.PlayPolyphemusTauntAnim ...

function game.PolyphemusBossDreamRunIntro(a, b) end
---@alias game-Scripts-PresentationBiomeN.PolyphemusBossDreamRunIntro ...

function game.PolyphemusBoulderIncomingPresentation() end
---@alias game-Scripts-PresentationBiomeN.PolyphemusBoulderIncomingPresentation ...

function game.PolyphemusGrabOngoingPresentation() end
---@alias game-Scripts-PresentationBiomeN.PolyphemusGrabOngoingPresentation ...

function game.PolyphemusInterruptWeaponPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeN.PolyphemusInterruptWeaponPresentation ...

function game.PolyphemusPlayerGrabApplyPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeN.PolyphemusPlayerGrabApplyPresentation ...

function game.PolyphemusPlayerGrabClearPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeN.PolyphemusPlayerGrabClearPresentation ...

function game.StartSurfacePenaltyPresentation() end
---@alias game-Scripts-PresentationBiomeN.StartSurfacePenaltyPresentation ...

function game.SurfacePenaltyPresentation() end
---@alias game-Scripts-PresentationBiomeN.SurfacePenaltyPresentation ...

function game.WitchPostSpellPresentation(a, b) end
---@alias game-Scripts-PresentationBiomeN.WitchPostSpellPresentation ...

return game