---@meta game-Scripts-QuestLogLogic
local game = {}

function game.CashOutQuest(a, b) end
---@alias game-Scripts-QuestLogLogic.CashOutQuest ...

function game.CheckQuestStatus(a) end
---@alias game-Scripts-QuestLogLogic.CheckQuestStatus ...

function game.CloseQuestLogScreen(a, b) end
---@alias game-Scripts-QuestLogLogic.CloseQuestLogScreen ...

function game.HasActiveQuestForName(a) end
---@alias game-Scripts-QuestLogLogic.HasActiveQuestForName ...

function game.HasAnyQuestWithStatus(a) end
---@alias game-Scripts-QuestLogLogic.HasAnyQuestWithStatus ...

function game.OpenQuestLogScreen(a) end
---@alias game-Scripts-QuestLogLogic.OpenQuestLogScreen ...

function game.QuestLogHideScrollButtons(a, b) end
---@alias game-Scripts-QuestLogLogic.QuestLogHideScrollButtons ...

function game.QuestLogScrollDown(a, b) end
---@alias game-Scripts-QuestLogLogic.QuestLogScrollDown ...

function game.QuestLogScrollUp(a, b) end
---@alias game-Scripts-QuestLogLogic.QuestLogScrollUp ...

function game.QuestLogUpdateVisibility(a, b) end
---@alias game-Scripts-QuestLogLogic.QuestLogUpdateVisibility ...

function game.QueueQuestProgressUpdate(a, b) end
---@alias game-Scripts-QuestLogLogic.QueueQuestProgressUpdate ...

function game.ShowQuestProgress(a, b, c) end
---@alias game-Scripts-QuestLogLogic.ShowQuestProgress ...

function game.UseQuestLog(a, b) end
---@alias game-Scripts-QuestLogLogic.UseQuestLog ...

function game.ValidateQuestData() end
---@alias game-Scripts-QuestLogLogic.ValidateQuestData ...

return game