---@meta game-Scripts-QuestPresentation
local game = {}

function game.FlashQuestLog() end
---@alias game-Scripts-QuestPresentation.FlashQuestLog ...

function game.MajorQuestCompletedPresentation(a, b) end
---@alias game-Scripts-QuestPresentation.MajorQuestCompletedPresentation ...

function game.MouseOffQuest(a) end
---@alias game-Scripts-QuestPresentation.MouseOffQuest ...

function game.MouseOverQuest(a) end
---@alias game-Scripts-QuestPresentation.MouseOverQuest ...

function game.QuestAddedPresentation(a) end
---@alias game-Scripts-QuestPresentation.QuestAddedPresentation ...

function game.QuestCashedOutPresentation(a, b) end
---@alias game-Scripts-QuestPresentation.QuestCashedOutPresentation ...

function game.QuestCompletedPresentation(a) end
---@alias game-Scripts-QuestPresentation.QuestCompletedPresentation ...

function game.QuestLogMouseOverPlayIcon(a) end
---@alias game-Scripts-QuestPresentation.QuestLogMouseOverPlayIcon ...

function game.QuestLogNextProgressPage(a, b) end
---@alias game-Scripts-QuestPresentation.QuestLogNextProgressPage ...

function game.QuestLogOpenFinishPresentation(a) end
---@alias game-Scripts-QuestPresentation.QuestLogOpenFinishPresentation ...

function game.QuestLogPlayInterstitial(a, b, c) end
---@alias game-Scripts-QuestPresentation.QuestLogPlayInterstitial ...

function game.QuestLogPressedPlayIcon(a, b) end
---@alias game-Scripts-QuestPresentation.QuestLogPressedPlayIcon ...

function game.QuestLogPrevProgressPage(a, b) end
---@alias game-Scripts-QuestPresentation.QuestLogPrevProgressPage ...

function game.QuestLogScreenClosePresentation(a, b) end
---@alias game-Scripts-QuestPresentation.QuestLogScreenClosePresentation ...

function game.QuestLogScreenUpdateWithCompletedDecal(a, b) end
---@alias game-Scripts-QuestPresentation.QuestLogScreenUpdateWithCompletedDecal ...

function game.QuestScreenRemoveDescription(a) end
---@alias game-Scripts-QuestPresentation.QuestScreenRemoveDescription ...

function game.QuestScreenShowDescription(a) end
---@alias game-Scripts-QuestPresentation.QuestScreenShowDescription ...

function game.QuestUpdatedPresentation(a) end
---@alias game-Scripts-QuestPresentation.QuestUpdatedPresentation ...

return game