---@meta game-Scripts-RequirementsLogic
local game = {}

function game.DebugTestAllRequirements(a, b, c) end
---@alias game-Scripts-RequirementsLogic.DebugTestAllRequirements ...

function game.DoComparison(a, b, c) end
---@alias game-Scripts-RequirementsLogic.DoComparison ...

function game.IsGameStateEligible(a, b, c) end
---@alias game-Scripts-RequirementsLogic.IsGameStateEligible ...

function game.RequireAffordableItemInScreen(a, b) end
---@alias game-Scripts-RequirementsLogic.RequireAffordableItemInScreen ...

function game.RequireAffordableMetaUpgrade(a, b) end
---@alias game-Scripts-RequirementsLogic.RequireAffordableMetaUpgrade ...

function game.RequireAllMetaUpgradesAtMaxLevel(a, b) end
---@alias game-Scripts-RequirementsLogic.RequireAllMetaUpgradesAtMaxLevel ...

function game.RequiredAlive(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredAlive ...

function game.RequiredBossPhase(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredBossPhase ...

function game.RequiredConfigOptions(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredConfigOptions ...

function game.RequiredConsecutiveClearsOfRoom(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredConsecutiveClearsOfRoom ...

function game.RequiredConsecutiveDeathsInRoom(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredConsecutiveDeathsInRoom ...

function game.RequiredDistanceFromHero(a, b, c) end
---@alias game-Scripts-RequirementsLogic.RequiredDistanceFromHero ...

function game.RequiredHealthFraction(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredHealthFraction ...

function game.RequiredMinExits(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredMinExits ...

function game.RequiredMinRoomsSinceEvent(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredMinRoomsSinceEvent ...

function game.RequiredMissingLastStands(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredMissingLastStands ...

function game.RequiredMusicSectionRoomDuration(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredMusicSectionRoomDuration ...

function game.RequiredNoneAlive(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredNoneAlive ...

function game.RequiredNotInStore(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredNotInStore ...

function game.RequiredOfferedDoorWitRoomSetName(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredOfferedDoorWitRoomSetName ...

function game.RequiredQueuedTextLine(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredQueuedTextLine ...

function game.RequiredRarityInRoom(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredRarityInRoom ...

function game.RequiredRewardCountInRoom(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredRewardCountInRoom ...

function game.RequiredRewardTypeInRoom(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredRewardTypeInRoom ...

function game.RequiredSellableGodTraits(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredSellableGodTraits ...

function game.RequiredTraitCount(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredTraitCount ...

function game.RequiredTraitNameInRoom(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredTraitNameInRoom ...

function game.RequiredUpgradeableGodTraits(a, b) end
---@alias game-Scripts-RequirementsLogic.RequiredUpgradeableGodTraits ...

function game.RequireQuestCount(a, b) end
---@alias game-Scripts-RequirementsLogic.RequireQuestCount ...

function game.RequireQuestWithStatus(a, b) end
---@alias game-Scripts-RequirementsLogic.RequireQuestWithStatus ...

function game.RequireRunsSinceTextLines(a, b) end
---@alias game-Scripts-RequirementsLogic.RequireRunsSinceTextLines ...

function game.RequireSpellCharged(a, b) end
---@alias game-Scripts-RequirementsLogic.RequireSpellCharged ...

function game.RequireUnrestrictedBoonChoices(a, b) end
---@alias game-Scripts-RequirementsLogic.RequireUnrestrictedBoonChoices ...

return game