---@meta game-Scripts-RoomPresentation
local game = {}

function game.AnomalyEndPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.AnomalyEndPresentation ...

function game.AnomalyEntrancePresentation(a, b, c) end
---@alias game-Scripts-RoomPresentation.AnomalyEntrancePresentation ...

function game.AnomalyExitPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.AnomalyExitPresentation ...

function game.AnomalyStartPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.AnomalyStartPresentation ...

function game.AttemptUseDoorNemesisTookPresentation(a) end
---@alias game-Scripts-RoomPresentation.AttemptUseDoorNemesisTookPresentation ...

function game.BiomeBackToRoom(a, b) end
---@alias game-Scripts-RoomPresentation.BiomeBackToRoom ...

function game.BiomeOverlook(a, b) end
---@alias game-Scripts-RoomPresentation.BiomeOverlook ...

function game.BiomeTimeCheckpointPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.BiomeTimeCheckpointPresentation ...

function game.BoonInteractPresentation(a, b, c) end
---@alias game-Scripts-RoomPresentation.BoonInteractPresentation ...

function game.BouldyHitPresentation(a) end
---@alias game-Scripts-RoomPresentation.BouldyHitPresentation ...

function game.CannotRerollPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.CannotRerollPresentation ...

function game.ChaosInteractPresentation(a, b, c) end
---@alias game-Scripts-RoomPresentation.ChaosInteractPresentation ...

function game.ChronosEndTimeSlowPresentation() end
---@alias game-Scripts-RoomPresentation.ChronosEndTimeSlowPresentation ...

function game.ChronosExit(a, b) end
---@alias game-Scripts-RoomPresentation.ChronosExit ...

function game.ChronosInvincibubblePresentation(a) end
---@alias game-Scripts-RoomPresentation.ChronosInvincibubblePresentation ...

function game.ChronosTimeSlowPresentation(a) end
---@alias game-Scripts-RoomPresentation.ChronosTimeSlowPresentation ...

function game.CleanupCustomRoomSounds() end
---@alias game-Scripts-RoomPresentation.CleanupCustomRoomSounds ...

function game.CloseSpellScreenPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.CloseSpellScreenPresentation ...

function game.ConsumableUsedPresentation(a, b, c) end
---@alias game-Scripts-RoomPresentation.ConsumableUsedPresentation ...

function game.ContractExitPresentation(a, b, c) end
---@alias game-Scripts-RoomPresentation.ContractExitPresentation ...

function game.CutsceneAddLetterbox(a) end
---@alias game-Scripts-RoomPresentation.CutsceneAddLetterbox ...

function game.DeathEscapeVFX(a, b) end
---@alias game-Scripts-RoomPresentation.DeathEscapeVFX ...

function game.DeathPresentation(a, b, c) end
---@alias game-Scripts-RoomPresentation.DeathPresentation ...

function game.DelayedRemoveInputBlock(a, b) end
---@alias game-Scripts-RoomPresentation.DelayedRemoveInputBlock ...

function game.DestroyDoorRewardPresenation(a) end
---@alias game-Scripts-RoomPresentation.DestroyDoorRewardPresenation ...

function game.DieHardShadeRevealPresentation(a) end
---@alias game-Scripts-RoomPresentation.DieHardShadeRevealPresentation ...

function game.DoChronosOnHitConversation(a) end
---@alias game-Scripts-RoomPresentation.DoChronosOnHitConversation ...

function game.DoomAppearancePresentation(a) end
---@alias game-Scripts-RoomPresentation.DoomAppearancePresentation ...

function game.DoomContextArtPresentation() end
---@alias game-Scripts-RoomPresentation.DoomContextArtPresentation ...

function game.DoorEntranceAnimation(a) end
---@alias game-Scripts-RoomPresentation.DoorEntranceAnimation ...

function game.EasyModeDisabledPresentation() end
---@alias game-Scripts-RoomPresentation.EasyModeDisabledPresentation ...

function game.EasyModeEnabledPresentation() end
---@alias game-Scripts-RoomPresentation.EasyModeEnabledPresentation ...

function game.EasyModeLevelUpPresentation() end
---@alias game-Scripts-RoomPresentation.EasyModeLevelUpPresentation ...

function game.ElementalIconsUnlockedPresentation(a) end
---@alias game-Scripts-RoomPresentation.ElementalIconsUnlockedPresentation ...

function game.EncounterCostDoorUsedPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.EncounterCostDoorUsedPresentation ...

function game.EndEarlyAccessPresentation() end
---@alias game-Scripts-RoomPresentation.EndEarlyAccessPresentation ...

function game.EndTinyVerminRadialBlur(a) end
---@alias game-Scripts-RoomPresentation.EndTinyVerminRadialBlur ...

function game.EntranceFromAnomalyPresentation(a, b, c) end
---@alias game-Scripts-RoomPresentation.EntranceFromAnomalyPresentation ...

function game.ExitDoorUnlockedPresentation(a) end
---@alias game-Scripts-RoomPresentation.ExitDoorUnlockedPresentation ...

function game.ExitToAnomalyPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.ExitToAnomalyPresentation ...

function game.FastEnterPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.FastEnterPresentation ...

function game.FastExitPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.FastExitPresentation ...

function game.FatesEntranceSFX() end
---@alias game-Scripts-RoomPresentation.FatesEntranceSFX ...

function game.FirstUnityBoonPresentation(a) end
---@alias game-Scripts-RoomPresentation.FirstUnityBoonPresentation ...

function game.FountainDamagePresentation() end
---@alias game-Scripts-RoomPresentation.FountainDamagePresentation ...

function game.FullScreenFadeInAnimation(a, b, c) end
---@alias game-Scripts-RoomPresentation.FullScreenFadeInAnimation ...

function game.FullScreenFadeInAnimationReroll(a) end
---@alias game-Scripts-RoomPresentation.FullScreenFadeInAnimationReroll ...

function game.FullScreenFadeOutAnimation(a, b, c) end
---@alias game-Scripts-RoomPresentation.FullScreenFadeOutAnimation ...

function game.FullScreenFadeOutAnimationReroll(a) end
---@alias game-Scripts-RoomPresentation.FullScreenFadeOutAnimationReroll ...

function game.GameplayTimerDisabledPresentation() end
---@alias game-Scripts-RoomPresentation.GameplayTimerDisabledPresentation ...

function game.GameplayTimerEnabledPresentation() end
---@alias game-Scripts-RoomPresentation.GameplayTimerEnabledPresentation ...

function game.GatherRoomPresentationObjects(a, b) end
---@alias game-Scripts-RoomPresentation.GatherRoomPresentationObjects ...

function game.GetDefaultClampIds() end
---@alias game-Scripts-RoomPresentation.GetDefaultClampIds ...

function game.GetDirectionalWipeAnimation(a) end
---@alias game-Scripts-RoomPresentation.GetDirectionalWipeAnimation ...

function game.HandleWeaponAspectsRevealObjective() end
---@alias game-Scripts-RoomPresentation.HandleWeaponAspectsRevealObjective ...

function game.HarvestPointAvailablePresentation(a, b) end
---@alias game-Scripts-RoomPresentation.HarvestPointAvailablePresentation ...

function game.HeroAlphaDelay(a, b) end
---@alias game-Scripts-RoomPresentation.HeroAlphaDelay ...

function game.HideDoomContextArtPresentation() end
---@alias game-Scripts-RoomPresentation.HideDoomContextArtPresentation ...

function game.HitByMiasmaPresentation(a) end
---@alias game-Scripts-RoomPresentation.HitByMiasmaPresentation ...

function game.KillCritter(a, b) end
---@alias game-Scripts-RoomPresentation.KillCritter ...

function game.LeaveRoomAudio(a, b) end
---@alias game-Scripts-RoomPresentation.LeaveRoomAudio ...

function game.LeaveRoomPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.LeaveRoomPresentation ...

function game.LeaveRoomSecretDoorPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.LeaveRoomSecretDoorPresentation ...

function game.LeaveRoomSecretExitDoorPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.LeaveRoomSecretExitDoorPresentation ...

function game.LeaveRoomStartPresentation(a) end
---@alias game-Scripts-RoomPresentation.LeaveRoomStartPresentation ...

function game.LegendaryAspectPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.LegendaryAspectPresentation ...

function game.LockExtraExitsPresentation(a) end
---@alias game-Scripts-RoomPresentation.LockExtraExitsPresentation ...

function game.ManaFountainUsedPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.ManaFountainUsedPresentation ...

function game.MaxHealthIncreaseText(a) end
---@alias game-Scripts-RoomPresentation.MaxHealthIncreaseText ...

function game.MiasmaClearedPresentation(a) end
---@alias game-Scripts-RoomPresentation.MiasmaClearedPresentation ...

function game.MoneyDropPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.MoneyDropPresentation ...

function game.MoveHeroAlongPath(a, b) end
---@alias game-Scripts-RoomPresentation.MoveHeroAlongPath ...

function game.MoveHeroToRoomPosition(a) end
---@alias game-Scripts-RoomPresentation.MoveHeroToRoomPosition ...

function game.NemesisLeaveRoomPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.NemesisLeaveRoomPresentation ...

function game.OlympusSkyEntrancePresentation(a, b, c) end
---@alias game-Scripts-RoomPresentation.OlympusSkyEntrancePresentation ...

function game.OpenSpellScreenPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.OpenSpellScreenPresentation ...

function game.PostRerollPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.PostRerollPresentation ...

function game.PreRerollPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.PreRerollPresentation ...

function game.QIntroEntrancePresentation(a, b, c) end
---@alias game-Scripts-RoomPresentation.QIntroEntrancePresentation ...

function game.ReattachCameraOnInput() end
---@alias game-Scripts-RoomPresentation.ReattachCameraOnInput ...

function game.RemoveScreenEdgeIndicator(a) end
---@alias game-Scripts-RoomPresentation.RemoveScreenEdgeIndicator ...

function game.RemoveScreenEdgeIndicators() end
---@alias game-Scripts-RoomPresentation.RemoveScreenEdgeIndicators ...

function game.RestoreUnlockRoomExitsPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.RestoreUnlockRoomExitsPresentation ...

function game.RoomEntranceBoss(a, b, c) end
---@alias game-Scripts-RoomPresentation.RoomEntranceBoss ...

function game.RoomEntranceBountyStart(a, b, c) end
---@alias game-Scripts-RoomPresentation.RoomEntranceBountyStart ...

function game.RoomEntranceCBossPresentation(a, b, c) end
---@alias game-Scripts-RoomPresentation.RoomEntranceCBossPresentation ...

function game.RoomEntranceDisplayLocationText(a) end
---@alias game-Scripts-RoomPresentation.RoomEntranceDisplayLocationText ...

function game.RoomEntranceDrop(a, b, c) end
---@alias game-Scripts-RoomPresentation.RoomEntranceDrop ...

function game.RoomEntranceMaterialize(a, b, c) end
---@alias game-Scripts-RoomPresentation.RoomEntranceMaterialize ...

function game.RoomEntrancePortal(a, b, c) end
---@alias game-Scripts-RoomPresentation.RoomEntrancePortal ...

function game.RoomEntranceStandard(a, b) end
---@alias game-Scripts-RoomPresentation.RoomEntranceStandard ...

function game.RoomOpeningUIDelay() end
---@alias game-Scripts-RoomPresentation.RoomOpeningUIDelay ...

function game.ScreenEdgeIndicatorSpawnPresentation(a, b, c, d) end
---@alias game-Scripts-RoomPresentation.ScreenEdgeIndicatorSpawnPresentation ...

function game.SeleneExitPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.SeleneExitPresentation ...

function game.SendCritters(a) end
---@alias game-Scripts-RoomPresentation.SendCritters ...

function game.SetupArachneTheme() end
---@alias game-Scripts-RoomPresentation.SetupArachneTheme ...

function game.SlightDescent() end
---@alias game-Scripts-RoomPresentation.SlightDescent ...

function game.SpawnChronosForTaunt(a, b) end
---@alias game-Scripts-RoomPresentation.SpawnChronosForTaunt ...

function game.SpellDropInteractPresentation(a, b, c) end
---@alias game-Scripts-RoomPresentation.SpellDropInteractPresentation ...

function game.SpellDropInteractPresentationEnd() end
---@alias game-Scripts-RoomPresentation.SpellDropInteractPresentationEnd ...

function game.StackUpgradePickupPresentation(a, b, c) end
---@alias game-Scripts-RoomPresentation.StackUpgradePickupPresentation ...

function game.StartChronosFakeBossMusic(a, b) end
---@alias game-Scripts-RoomPresentation.StartChronosFakeBossMusic ...

function game.StartChronosFakeBossPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.StartChronosFakeBossPresentation ...

function game.StartDevotionTestPresentation(a, b, c) end
---@alias game-Scripts-RoomPresentation.StartDevotionTestPresentation ...

function game.StartRoomMusic(a, b) end
---@alias game-Scripts-RoomPresentation.StartRoomMusic ...

function game.StartRoomPresentation(a, b, c) end
---@alias game-Scripts-RoomPresentation.StartRoomPresentation ...

function game.StopMiniBossMusic(a) end
---@alias game-Scripts-RoomPresentation.StopMiniBossMusic ...

function game.StorePurchasePresentation(a, b, c, d) end
---@alias game-Scripts-RoomPresentation.StorePurchasePresentation ...

function game.TalentScreenCloseFinishedPresentation(a) end
---@alias game-Scripts-RoomPresentation.TalentScreenCloseFinishedPresentation ...

function game.TrueEndingTimeFxVignette() end
---@alias game-Scripts-RoomPresentation.TrueEndingTimeFxVignette ...

function game.UpgradeAcquiredPresentation(a, b) end
---@alias game-Scripts-RoomPresentation.UpgradeAcquiredPresentation ...

return game