---@meta game-Scripts-RunData
local game = {}

game.FinishedDataRead = true
---@alias game-Scripts-RunData.FinishedDataRead ...

---@class game-Scripts-RunData*GlobalTextLines

---@type game-Scripts-RunData*GlobalTextLines
game.GlobalTextLines = ...
---@alias game-Scripts-RunData.GlobalTextLines ...

---@class game-Scripts-RunData*Icons

---@type game-Scripts-RunData*Icons
game.Icons = ...
---@alias game-Scripts-RunData.Icons ...

---@class game-Scripts-RunData*MetaUpgradeCardUpgradeData

---@type game-Scripts-RunData*MetaUpgradeCardUpgradeData
game.MetaUpgradeCardUpgradeData = ...
---@alias game-Scripts-RunData.MetaUpgradeCardUpgradeData ...

---@class game-Scripts-RunData*MetaUpgradeCostDataStore

---@type game-Scripts-RunData*MetaUpgradeCostDataStore
game.MetaUpgradeCostDataStore = ...
---@alias game-Scripts-RunData.MetaUpgradeCostDataStore ...

---@class game-Scripts-RunData*MetaUpgradeUnequipPatchData

---@type game-Scripts-RunData*MetaUpgradeUnequipPatchData
game.MetaUpgradeUnequipPatchData = ...
---@alias game-Scripts-RunData.MetaUpgradeUnequipPatchData ...

---@class game-Scripts-RunData*PropertyOrderingValuesLookup

---@type game-Scripts-RunData*PropertyOrderingValuesLookup
game.PropertyOrderingValuesLookup = ...
---@alias game-Scripts-RunData.PropertyOrderingValuesLookup ...

---@class game-Scripts-RunData*TextLinesCache

---@type game-Scripts-RunData*TextLinesCache
game.TextLinesCache = ...
---@alias game-Scripts-RunData.TextLinesCache ...

---@class game-Scripts-RunData*WeaponSetLookups

---@type game-Scripts-RunData*WeaponSetLookups
game.WeaponSetLookups = ...
---@alias game-Scripts-RunData.WeaponSetLookups ...

function game.AddFormattedPercentageChangeValues(a, b) end
---@alias game-Scripts-RunData.AddFormattedPercentageChangeValues ...

function game.AddLinkedWeapons(a) end
---@alias game-Scripts-RunData.AddLinkedWeapons ...

function game.DeepInheritData(a, b) end
---@alias game-Scripts-RunData.DeepInheritData ...

function game.ProcessDataInheritance(a, b) end
---@alias game-Scripts-RunData.ProcessDataInheritance ...

function game.ProcessDataStore(a) end
---@alias game-Scripts-RunData.ProcessDataStore ...

function game.ProcessSimpleExtractValues(a) end
---@alias game-Scripts-RunData.ProcessSimpleExtractValues ...

function game.ProcessTextLines(a, b, c, d) end
---@alias game-Scripts-RunData.ProcessTextLines ...

function game.ResetKeywords() end
---@alias game-Scripts-RunData.ResetKeywords ...

function game.SetupRunData(a) end
---@alias game-Scripts-RunData.SetupRunData ...

function game.ValidateGlobalFormats() end
---@alias game-Scripts-RunData.ValidateGlobalFormats ...

function game.ValidateLinesFormats(a, b) end
---@alias game-Scripts-RunData.ValidateLinesFormats ...

return game