---@meta game-Scripts-RunHistoryLogic
local game = {}

function game.CloseRunHistoryScreen(a, b) end
---@alias game-Scripts-RunHistoryLogic.CloseRunHistoryScreen ...

function game.GetMetaUpgradeDataFromTraitName(a) end
---@alias game-Scripts-RunHistoryLogic.GetMetaUpgradeDataFromTraitName ...

function game.GetVisitedBiomeIcons(a) end
---@alias game-Scripts-RunHistoryLogic.GetVisitedBiomeIcons ...

function game.OpenRunHistoryScreen(a) end
---@alias game-Scripts-RunHistoryLogic.OpenRunHistoryScreen ...

function game.RunHistoryGetSortedTraits(a) end
---@alias game-Scripts-RunHistoryLogic.RunHistoryGetSortedTraits ...

function game.RunHistoryScreenNextCategory(a, b) end
---@alias game-Scripts-RunHistoryLogic.RunHistoryScreenNextCategory ...

function game.RunHistoryScreenPrevCategory(a, b) end
---@alias game-Scripts-RunHistoryLogic.RunHistoryScreenPrevCategory ...

function game.RunHistoryScreenSelectCategory(a, b) end
---@alias game-Scripts-RunHistoryLogic.RunHistoryScreenSelectCategory ...

function game.RunHistoryScreenSetupTabs(a) end
---@alias game-Scripts-RunHistoryLogic.RunHistoryScreenSetupTabs ...

function game.RunHistoryScreenShowCategory(a, b, c) end
---@alias game-Scripts-RunHistoryLogic.RunHistoryScreenShowCategory ...

function game.RunHistoryScreenShowMetaUpgrades(a, b) end
---@alias game-Scripts-RunHistoryLogic.RunHistoryScreenShowMetaUpgrades ...

function game.RunHistoryScreenShowShrineUpgrades(a, b) end
---@alias game-Scripts-RunHistoryLogic.RunHistoryScreenShowShrineUpgrades ...

function game.RunHistoryScreenShowTraits(a, b, c) end
---@alias game-Scripts-RunHistoryLogic.RunHistoryScreenShowTraits ...

function game.RunHistoryScrollDown(a, b) end
---@alias game-Scripts-RunHistoryLogic.RunHistoryScrollDown ...

function game.RunHistoryScrollUp(a, b) end
---@alias game-Scripts-RunHistoryLogic.RunHistoryScrollUp ...

function game.RunHistorySelectRun(a) end
---@alias game-Scripts-RunHistoryLogic.RunHistorySelectRun ...

function game.RunHistoryTraitSort(a, b) end
---@alias game-Scripts-RunHistoryLogic.RunHistoryTraitSort ...

function game.RunHistoryUpdateVisibility(a) end
---@alias game-Scripts-RunHistoryLogic.RunHistoryUpdateVisibility ...

function game.ShowRunHistory(a, b) end
---@alias game-Scripts-RunHistoryLogic.ShowRunHistory ...

function game.UseRunHistoryScreenObject(a, b) end
---@alias game-Scripts-RunHistoryLogic.UseRunHistoryScreenObject ...

return game