---@meta game-Scripts-RunLogic
local game = {}

function game.AddTimerBlock(a, b, c) end
---@alias game-Scripts-RunLogic.AddTimerBlock ...

function game.AddToSpawnTable(a, b) end
---@alias game-Scripts-RunLogic.AddToSpawnTable ...

function game.CalculateEnemyDifficultyRating(a, b) end
---@alias game-Scripts-RunLogic.CalculateEnemyDifficultyRating ...

function game.CalculateStartingMoney() end
---@alias game-Scripts-RunLogic.CalculateStartingMoney ...

function game.CheckPreviousReward(a, b, c, d) end
---@alias game-Scripts-RunLogic.CheckPreviousReward ...

function game.CheckReloadEncounters(a, b) end
---@alias game-Scripts-RunLogic.CheckReloadEncounters ...

function game.CheckSetupFunction(a, b) end
---@alias game-Scripts-RunLogic.CheckSetupFunction ...

function game.ChooseEncounter(a, b, c) end
---@alias game-Scripts-RunLogic.ChooseEncounter ...

function game.ChooseNextRoomData(a, b, c) end
---@alias game-Scripts-RunLogic.ChooseNextRoomData ...

function game.ChooseStartingRoom(a, b) end
---@alias game-Scripts-RunLogic.ChooseStartingRoom ...

function game.CloseDoorForRun(a, b) end
---@alias game-Scripts-RunLogic.CloseDoorForRun ...

function game.CreateNewHero(a, b) end
---@alias game-Scripts-RunLogic.CreateNewHero ...

function game.CreateRoom(a, b) end
---@alias game-Scripts-RunLogic.CreateRoom ...

function game.EndBiomeRecords(a, b) end
---@alias game-Scripts-RunLogic.EndBiomeRecords ...

function game.EndRun(a) end
---@alias game-Scripts-RunLogic.EndRun ...

function game.FillEnemyCounts(a, b, c) end
---@alias game-Scripts-RunLogic.FillEnemyCounts ...

function game.FillEnemyTypes(a, b, c) end
---@alias game-Scripts-RunLogic.FillEnemyTypes ...

function game.GameStateInit() end
---@alias game-Scripts-RunLogic.GameStateInit ...

function game.GenerateEncounter(a, b, c) end
---@alias game-Scripts-RunLogic.GenerateEncounter ...

function game.GetBiomeDepth(a) end
---@alias game-Scripts-RunLogic.GetBiomeDepth ...

function game.GetCompletedRuns() end
---@alias game-Scripts-RunLogic.GetCompletedRuns ...

function game.GetEligibleInteractedGod(a) end
---@alias game-Scripts-RunLogic.GetEligibleInteractedGod ...

function game.GetEligibleInteractedGods(a) end
---@alias game-Scripts-RunLogic.GetEligibleInteractedGods ...

function game.GetEligibleMeleeWeapons() end
---@alias game-Scripts-RunLogic.GetEligibleMeleeWeapons ...

function game.GetInteractedGods() end
---@alias game-Scripts-RunLogic.GetInteractedGods ...

function game.GetInteractedGodsThisRun(a) end
---@alias game-Scripts-RunLogic.GetInteractedGodsThisRun ...

function game.GetInteractedGodThisRun(a) end
---@alias game-Scripts-RunLogic.GetInteractedGodThisRun ...

function game.GetPreviousRoom(a) end
---@alias game-Scripts-RunLogic.GetPreviousRoom ...

function game.GetRunDepth(a) end
---@alias game-Scripts-RunLogic.GetRunDepth ...

function game.GetRunResult(a) end
---@alias game-Scripts-RunLogic.GetRunResult ...

function game.HandleSubRoomData(a, b) end
---@alias game-Scripts-RunLogic.HandleSubRoomData ...

function game.HandleSubRoomReturnData(a, b) end
---@alias game-Scripts-RunLogic.HandleSubRoomReturnData ...

function game.HasEncounterBeenCompleted(a) end
---@alias game-Scripts-RunLogic.HasEncounterBeenCompleted ...

function game.HasEncounterOccurred(a, b, c) end
---@alias game-Scripts-RunLogic.HasEncounterOccurred ...

function game.HasEventFunctionName(a, b) end
---@alias game-Scripts-RunLogic.HasEventFunctionName ...

function game.HasSeenRoomInNumRuns(a, b) end
---@alias game-Scripts-RunLogic.HasSeenRoomInNumRuns ...

function game.HasTimerBlock(a, b) end
---@alias game-Scripts-RunLogic.HasTimerBlock ...

function game.HasTraitRequirements(a) end
---@alias game-Scripts-RunLogic.HasTraitRequirements ...

function game.InitHeroLastStands(a) end
---@alias game-Scripts-RunLogic.InitHeroLastStands ...

function game.InvalidateCheckpoint() end
---@alias game-Scripts-RunLogic.InvalidateCheckpoint ...

function game.IsDoorClosedForRun(a, b) end
---@alias game-Scripts-RunLogic.IsDoorClosedForRun ...

function game.IsEncounterEligible(a, b, c, d) end
---@alias game-Scripts-RunLogic.IsEncounterEligible ...

function game.IsEncounterForced(a, b, c) end
---@alias game-Scripts-RunLogic.IsEncounterForced ...

function game.IsEnemyEligible(a, b, c) end
---@alias game-Scripts-RunLogic.IsEnemyEligible ...

function game.IsInspectPointEligible(a, b, c) end
---@alias game-Scripts-RunLogic.IsInspectPointEligible ...

function game.IsRoomEligible(a, b, c, d) end
---@alias game-Scripts-RunLogic.IsRoomEligible ...

function game.IsRoomForced(a, b, c, d, e) end
---@alias game-Scripts-RunLogic.IsRoomForced ...

function game.IsTraitEligible(a, b) end
---@alias game-Scripts-RunLogic.IsTraitEligible ...

function game.IsWeaponEligible(a, b) end
---@alias game-Scripts-RunLogic.IsWeaponEligible ...

function game.ProcessObjectValueOptions(a) end
---@alias game-Scripts-RunLogic.ProcessObjectValueOptions ...

function game.RandomizeObject(a, b) end
---@alias game-Scripts-RunLogic.RandomizeObject ...

function game.ReachedMaxGods(a) end
---@alias game-Scripts-RunLogic.ReachedMaxGods ...

function game.RecordRunCleared() end
---@alias game-Scripts-RunLogic.RecordRunCleared ...

function game.RecordRunStats() end
---@alias game-Scripts-RunLogic.RecordRunStats ...

function game.RemoveTimerBlock(a, b) end
---@alias game-Scripts-RunLogic.RemoveTimerBlock ...

function game.RequestSave(a) end
---@alias game-Scripts-RunLogic.RequestSave ...

function game.RoomInit(a) end
---@alias game-Scripts-RunLogic.RoomInit ...

function game.RunStateInit() end
---@alias game-Scripts-RunLogic.RunStateInit ...

function game.SelectBannedEliteAttributes(a) end
---@alias game-Scripts-RunLogic.SelectBannedEliteAttributes ...

function game.SetupEncounter(a, b) end
---@alias game-Scripts-RunLogic.SetupEncounter ...

function game.SetupObstacle(a, b, c) end
---@alias game-Scripts-RunLogic.SetupObstacle ...

function game.StartNewGame(a) end
---@alias game-Scripts-RunLogic.StartNewGame ...

function game.StartNewRun(a, b) end
---@alias game-Scripts-RunLogic.StartNewRun ...

function game.UpdateConfigOptionCache(a) end
---@alias game-Scripts-RunLogic.UpdateConfigOptionCache ...

function game.UpdateLifetimeTraitRecords(a) end
---@alias game-Scripts-RunLogic.UpdateLifetimeTraitRecords ...

function game.UpdateRunHistoryCache(a, b) end
---@alias game-Scripts-RunLogic.UpdateRunHistoryCache ...

function game.UpdateTimers(a) end
---@alias game-Scripts-RunLogic.UpdateTimers ...

function game.UpdateWeaponHistory(a) end
---@alias game-Scripts-RunLogic.UpdateWeaponHistory ...

function game.UpdateZoomFractions(a) end
---@alias game-Scripts-RunLogic.UpdateZoomFractions ...

function game.WasBountyRun(a) end
---@alias game-Scripts-RunLogic.WasBountyRun ...

function game.WasDreamRun(a) end
---@alias game-Scripts-RunLogic.WasDreamRun ...

function game.WasRunSuccess(a) end
---@alias game-Scripts-RunLogic.WasRunSuccess ...

function game.WasSurfaceRun(a) end
---@alias game-Scripts-RunLogic.WasSurfaceRun ...

function game.WasUnderworldRun(a) end
---@alias game-Scripts-RunLogic.WasUnderworldRun ...

return game