---@meta game-Scripts-ShrinePresentation
local game = {}

function game.BanUnpickedBoonPresentation(a, b) end
---@alias game-Scripts-ShrinePresentation.BanUnpickedBoonPresentation ...

function game.BoonManaReserveShrineUpgradePresentation(a, b) end
---@alias game-Scripts-ShrinePresentation.BoonManaReserveShrineUpgradePresentation ...

function game.BoonSkipShrineUpgradePresentation(a, b) end
---@alias game-Scripts-ShrinePresentation.BoonSkipShrineUpgradePresentation ...

function game.BossDifficultyShrineUpgradeRankRevealed(a, b, c) end
---@alias game-Scripts-ShrinePresentation.BossDifficultyShrineUpgradeRankRevealed ...

function game.BountyReadyConfirmPresentation(a, b) end
---@alias game-Scripts-ShrinePresentation.BountyReadyConfirmPresentation ...

function game.CreateShrineScreenDelay() end
---@alias game-Scripts-ShrinePresentation.CreateShrineScreenDelay ...

function game.ErisCurseAppliedPresentation(a, b) end
---@alias game-Scripts-ShrinePresentation.ErisCurseAppliedPresentation ...

function game.ErisTakeOff(a) end
---@alias game-Scripts-ShrinePresentation.ErisTakeOff ...

function game.OpenShrineScreenPostPresentation(a) end
---@alias game-Scripts-ShrinePresentation.OpenShrineScreenPostPresentation ...

function game.OpenShrineScreenPrePresentation(a, b) end
---@alias game-Scripts-ShrinePresentation.OpenShrineScreenPrePresentation ...

function game.RespawnEggCountdownTickPresentation(a, b) end
---@alias game-Scripts-ShrinePresentation.RespawnEggCountdownTickPresentation ...

function game.RespawnEggPickedUpPresentation(a, b, c) end
---@alias game-Scripts-ShrinePresentation.RespawnEggPickedUpPresentation ...

function game.RespawnEggRespawnPresentation(a, b) end
---@alias game-Scripts-ShrinePresentation.RespawnEggRespawnPresentation ...

function game.ShrineEliteAttributeManaDrainTickPresentation(a) end
---@alias game-Scripts-ShrinePresentation.ShrineEliteAttributeManaDrainTickPresentation ...

function game.ShrinePointRefundPresentation(a, b, c) end
---@alias game-Scripts-ShrinePresentation.ShrinePointRefundPresentation ...

function game.ShrinePointSpendPresentation(a, b, c) end
---@alias game-Scripts-ShrinePresentation.ShrinePointSpendPresentation ...

function game.ShrineScreenAlreadyAtMaxPresentation(a, b) end
---@alias game-Scripts-ShrinePresentation.ShrineScreenAlreadyAtMaxPresentation ...

function game.ShrineScreenAlreadyAtMinPresentation(a, b) end
---@alias game-Scripts-ShrinePresentation.ShrineScreenAlreadyAtMinPresentation ...

function game.ShrineScreenMouseOffItem(a) end
---@alias game-Scripts-ShrinePresentation.ShrineScreenMouseOffItem ...

function game.ShrineScreenMouseOverItem(a, b) end
---@alias game-Scripts-ShrinePresentation.ShrineScreenMouseOverItem ...

function game.ShrineScreenOpenFinishedPresentation(a) end
---@alias game-Scripts-ShrinePresentation.ShrineScreenOpenFinishedPresentation ...

function game.ShrineScreenRankDownPresentation(a, b, c) end
---@alias game-Scripts-ShrinePresentation.ShrineScreenRankDownPresentation ...

function game.ShrineScreenRankUpPresentation(a, b) end
---@alias game-Scripts-ShrinePresentation.ShrineScreenRankUpPresentation ...

function game.ShrineScreenResetPresentation(a) end
---@alias game-Scripts-ShrinePresentation.ShrineScreenResetPresentation ...

function game.ShrineScreenUpdateActivePoints(a, b, c) end
---@alias game-Scripts-ShrinePresentation.ShrineScreenUpdateActivePoints ...

function game.ShrineScreenUpdateItems(a, b, c) end
---@alias game-Scripts-ShrinePresentation.ShrineScreenUpdateItems ...

function game.ShrineScreenUpdateNextRankText(a, b) end
---@alias game-Scripts-ShrinePresentation.ShrineScreenUpdateNextRankText ...

function game.ShrineScreenUpdateRankActions(a) end
---@alias game-Scripts-ShrinePresentation.ShrineScreenUpdateRankActions ...

function game.SkellyStatueAdmire(a, b) end
---@alias game-Scripts-ShrinePresentation.SkellyStatueAdmire ...

function game.SkellyStatueUnveil(a, b) end
---@alias game-Scripts-ShrinePresentation.SkellyStatueUnveil ...

function game.StatueHitPresentation(a, b, c) end
---@alias game-Scripts-ShrinePresentation.StatueHitPresentation ...

function game.UpdateShrineAnimation(a) end
---@alias game-Scripts-ShrinePresentation.UpdateShrineAnimation ...

function game.UpdateShrineRunDoorArrow(a, b) end
---@alias game-Scripts-ShrinePresentation.UpdateShrineRunDoorArrow ...

return game