---@meta game-Scripts-SpellPresentation
local game = {}

function game.CheckSpellOutOfManaPresentation(a, b, c) end
---@alias game-Scripts-SpellPresentation.CheckSpellOutOfManaPresentation ...

function game.CleanUpShoutPresentation(a, b, c) end
---@alias game-Scripts-SpellPresentation.CleanUpShoutPresentation ...

function game.CreateSpellHUD(a, b) end
---@alias game-Scripts-SpellPresentation.CreateSpellHUD ...

function game.DelayedHephaestusLeapPresentation(a, b, c, d) end
---@alias game-Scripts-SpellPresentation.DelayedHephaestusLeapPresentation ...

function game.DoFullSuperPresentation(a) end
---@alias game-Scripts-SpellPresentation.DoFullSuperPresentation ...

function game.FirstTimeDuoTalentPresentation(a) end
---@alias game-Scripts-SpellPresentation.FirstTimeDuoTalentPresentation ...

function game.PoseidonPotionWarnPresentation() end
---@alias game-Scripts-SpellPresentation.PoseidonPotionWarnPresentation ...

function game.SelectSpellPresentation(a, b) end
---@alias game-Scripts-SpellPresentation.SelectSpellPresentation ...

function game.ShoutSlow() end
---@alias game-Scripts-SpellPresentation.ShoutSlow ...

function game.SpellActivateTrait(a, b) end
---@alias game-Scripts-SpellPresentation.SpellActivateTrait ...

function game.SpellBloodMoonBeamHitPresentation(a, b, c) end
---@alias game-Scripts-SpellPresentation.SpellBloodMoonBeamHitPresentation ...

function game.SpellChargeEndPresentation(a) end
---@alias game-Scripts-SpellPresentation.SpellChargeEndPresentation ...

function game.SpellChargeNumber(a, b, c) end
---@alias game-Scripts-SpellPresentation.SpellChargeNumber ...

function game.SpellChargePresentation(a, b, c) end
---@alias game-Scripts-SpellPresentation.SpellChargePresentation ...

function game.SpellFailToFirePresentation(a) end
---@alias game-Scripts-SpellPresentation.SpellFailToFirePresentation ...

function game.SpellHasManaPresentation() end
---@alias game-Scripts-SpellPresentation.SpellHasManaPresentation ...

function game.SpellHasNoManaPresentation() end
---@alias game-Scripts-SpellPresentation.SpellHasNoManaPresentation ...

function game.SpellHintPresentation() end
---@alias game-Scripts-SpellPresentation.SpellHintPresentation ...

function game.SpellMeteorPresentation(a, b) end
---@alias game-Scripts-SpellPresentation.SpellMeteorPresentation ...

function game.SpellMeteorPresentationThreaded(a, b) end
---@alias game-Scripts-SpellPresentation.SpellMeteorPresentationThreaded ...

function game.SpellPolymorphResistedPresentation(a, b) end
---@alias game-Scripts-SpellPresentation.SpellPolymorphResistedPresentation ...

function game.SpellPotionUsedPresentation(a, b) end
---@alias game-Scripts-SpellPresentation.SpellPotionUsedPresentation ...

function game.SpellReadyPresentation(a, b) end
---@alias game-Scripts-SpellPresentation.SpellReadyPresentation ...

function game.SpellReloadPresentation(a, b) end
---@alias game-Scripts-SpellPresentation.SpellReloadPresentation ...

function game.SpellTransformEndPresentation(a, b, c, d) end
---@alias game-Scripts-SpellPresentation.SpellTransformEndPresentation ...

function game.SpellTransformStartPresentation(a, b, c, d) end
---@alias game-Scripts-SpellPresentation.SpellTransformStartPresentation ...

function game.SpellTransformWarnPresentation() end
---@alias game-Scripts-SpellPresentation.SpellTransformWarnPresentation ...

function game.SpellUnreadyPresentation(a) end
---@alias game-Scripts-SpellPresentation.SpellUnreadyPresentation ...

function game.TeleportSummonPresentation(a) end
---@alias game-Scripts-SpellPresentation.TeleportSummonPresentation ...

return game