---@meta game-Scripts-SpellLogic
local game = {}

function game.AddTransformAttackSpeed(a) end
---@alias game-Scripts-SpellLogic.AddTransformAttackSpeed ...

function game.ApplyLeapSprint(a, b, c) end
---@alias game-Scripts-SpellLogic.ApplyLeapSprint ...

function game.ApplyMoonBeamExVulnerability(a) end
---@alias game-Scripts-SpellLogic.ApplyMoonBeamExVulnerability ...

function game.ApplySelfBuff(a, b, c) end
---@alias game-Scripts-SpellLogic.ApplySelfBuff ...

function game.BuildValidEffects(a, b) end
---@alias game-Scripts-SpellLogic.BuildValidEffects ...

function game.CanChargeSpell() end
---@alias game-Scripts-SpellLogic.CanChargeSpell ...

function game.ChargeSpell(a, b) end
---@alias game-Scripts-SpellLogic.ChargeSpell ...

function game.CheckAndAddOlympianDuo(a) end
---@alias game-Scripts-SpellLogic.CheckAndAddOlympianDuo ...

function game.CheckAutoMoonBeam(a, b, c) end
---@alias game-Scripts-SpellLogic.CheckAutoMoonBeam ...

function game.CheckBurnAll(a, b, c) end
---@alias game-Scripts-SpellLogic.CheckBurnAll ...

function game.CheckFirstTimeLaserFire(a, b) end
---@alias game-Scripts-SpellLogic.CheckFirstTimeLaserFire ...

function game.CheckMeteorCharge(a, b) end
---@alias game-Scripts-SpellLogic.CheckMeteorCharge ...

function game.CheckMoonBeamConsecutiveDamage(a, b, c) end
---@alias game-Scripts-SpellLogic.CheckMoonBeamConsecutiveDamage ...

function game.CheckPolymorphApply(a) end
---@alias game-Scripts-SpellLogic.CheckPolymorphApply ...

function game.CheckPolymorphCharge(a, b) end
---@alias game-Scripts-SpellLogic.CheckPolymorphCharge ...

function game.CheckPolymorphDeathExplosion(a, b) end
---@alias game-Scripts-SpellLogic.CheckPolymorphDeathExplosion ...

function game.CheckSpawnFreeze(a, b) end
---@alias game-Scripts-SpellLogic.CheckSpawnFreeze ...

function game.CheckSpellForceCharge(a, b, c) end
---@alias game-Scripts-SpellLogic.CheckSpellForceCharge ...

function game.CheckSpellMultiuse(a) end
---@alias game-Scripts-SpellLogic.CheckSpellMultiuse ...

function game.ContinuousHealthRegeneration(a) end
---@alias game-Scripts-SpellLogic.ContinuousHealthRegeneration ...

function game.ContinuousManaRegeneration(a) end
---@alias game-Scripts-SpellLogic.ContinuousManaRegeneration ...

function game.CreatePolymorphHealItem(a) end
---@alias game-Scripts-SpellLogic.CreatePolymorphHealItem ...

function game.CreateTalentTree(a) end
---@alias game-Scripts-SpellLogic.CreateTalentTree ...

function game.DisableCastArm() end
---@alias game-Scripts-SpellLogic.DisableCastArm ...

function game.EnableCastArm() end
---@alias game-Scripts-SpellLogic.EnableCastArm ...

function game.EndBurnAll(a) end
---@alias game-Scripts-SpellLogic.EndBurnAll ...

function game.EndCooldownBuff() end
---@alias game-Scripts-SpellLogic.EndCooldownBuff ...

function game.EndMoonBeam(a, b) end
---@alias game-Scripts-SpellLogic.EndMoonBeam ...

function game.EndSpellSummon(a, b) end
---@alias game-Scripts-SpellLogic.EndSpellSummon ...

function game.EndSpellTransform() end
---@alias game-Scripts-SpellLogic.EndSpellTransform ...

function game.EndTimeSlow(a) end
---@alias game-Scripts-SpellLogic.EndTimeSlow ...

function game.EndTimeSlowCrit() end
---@alias game-Scripts-SpellLogic.EndTimeSlowCrit ...

function game.EndTimeSlowFreeze(a) end
---@alias game-Scripts-SpellLogic.EndTimeSlowFreeze ...

function game.EndTimeSlowSpeed() end
---@alias game-Scripts-SpellLogic.EndTimeSlowSpeed ...

function game.EndTransformBurst() end
---@alias game-Scripts-SpellLogic.EndTransformBurst ...

function game.FindSpawnPointsInCast(a, b, c) end
---@alias game-Scripts-SpellLogic.FindSpawnPointsInCast ...

function game.ForceLaserFacing() end
---@alias game-Scripts-SpellLogic.ForceLaserFacing ...

function game.GetManaSpendCost(a) end
---@alias game-Scripts-SpellLogic.GetManaSpendCost ...

function game.GetTalentRarity(a) end
---@alias game-Scripts-SpellLogic.GetTalentRarity ...

function game.GrantPotionBonusCharges(a) end
---@alias game-Scripts-SpellLogic.GrantPotionBonusCharges ...

function game.HandleZeusStrikeNearProjectile(a, b) end
---@alias game-Scripts-SpellLogic.HandleZeusStrikeNearProjectile ...

function game.LaserHoldClear() end
---@alias game-Scripts-SpellLogic.LaserHoldClear ...

function game.LaserMatchDuration(a) end
---@alias game-Scripts-SpellLogic.LaserMatchDuration ...

function game.LaserSpellFire(a, b, c, d) end
---@alias game-Scripts-SpellLogic.LaserSpellFire ...

function game.LaserSpellForceRelease(a) end
---@alias game-Scripts-SpellLogic.LaserSpellForceRelease ...

function game.LaserSpellReload(a, b, c) end
---@alias game-Scripts-SpellLogic.LaserSpellReload ...

function game.LeapEnableBlink(a, b, c) end
---@alias game-Scripts-SpellLogic.LeapEnableBlink ...

function game.LeapSimSlow(a, b) end
---@alias game-Scripts-SpellLogic.LeapSimSlow ...

function game.MeteorCheckInvulnerability(a, b, c) end
---@alias game-Scripts-SpellLogic.MeteorCheckInvulnerability ...

function game.MeteorExCast(a, b) end
---@alias game-Scripts-SpellLogic.MeteorExCast ...

function game.MeteorFirePreattack(a, b, c) end
---@alias game-Scripts-SpellLogic.MeteorFirePreattack ...

function game.MeteorPreattackThread(a, b, c) end
---@alias game-Scripts-SpellLogic.MeteorPreattackThread ...

function game.MeteorStartVulnerability(a, b, c) end
---@alias game-Scripts-SpellLogic.MeteorStartVulnerability ...

function game.MeteorVulnerabilityThread(a, b, c) end
---@alias game-Scripts-SpellLogic.MeteorVulnerabilityThread ...

function game.MoonBeamSpellFire(a, b, c, d) end
---@alias game-Scripts-SpellLogic.MoonBeamSpellFire ...

function game.OnSpellFired() end
---@alias game-Scripts-SpellLogic.OnSpellFired ...

function game.PolymorphCastTeleport(a, b, c) end
---@alias game-Scripts-SpellLogic.PolymorphCastTeleport ...

function game.PolymorphCopyStatus(a, b, c) end
---@alias game-Scripts-SpellLogic.PolymorphCopyStatus ...

function game.PolymorphStunApply(a) end
---@alias game-Scripts-SpellLogic.PolymorphStunApply ...

function game.PolymorphStunClear(a) end
---@alias game-Scripts-SpellLogic.PolymorphStunClear ...

function game.PotionExCast() end
---@alias game-Scripts-SpellLogic.PotionExCast ...

function game.PotionPoseidonDrops(a, b, c) end
---@alias game-Scripts-SpellLogic.PotionPoseidonDrops ...

function game.PotionRetaliate(a) end
---@alias game-Scripts-SpellLogic.PotionRetaliate ...

function game.PregenerateSpells(a) end
---@alias game-Scripts-SpellLogic.PregenerateSpells ...

function game.RecordDamageInWindow(a, b, c) end
---@alias game-Scripts-SpellLogic.RecordDamageInWindow ...

function game.RecordLastDamaged(a, b, c) end
---@alias game-Scripts-SpellLogic.RecordLastDamaged ...

function game.RecordSpellSummonEnemyDeath(a, b) end
---@alias game-Scripts-SpellLogic.RecordSpellSummonEnemyDeath ...

function game.ReenableLaserCharge(a, b) end
---@alias game-Scripts-SpellLogic.ReenableLaserCharge ...

function game.ReleaseDamageInWindow(a, b) end
---@alias game-Scripts-SpellLogic.ReleaseDamageInWindow ...

function game.RemoveTransformAttackSpeed(a) end
---@alias game-Scripts-SpellLogic.RemoveTransformAttackSpeed ...

function game.ResetFirstHitTalent() end
---@alias game-Scripts-SpellLogic.ResetFirstHitTalent ...

function game.SelfBuffOutputApply(a) end
---@alias game-Scripts-SpellLogic.SelfBuffOutputApply ...

function game.SelfBuffOutputClear(a) end
---@alias game-Scripts-SpellLogic.SelfBuffOutputClear ...

function game.SetupSpellLeap(a, b, c, d) end
---@alias game-Scripts-SpellLogic.SetupSpellLeap ...

function game.ShouldFireFirstTimeOlympian() end
---@alias game-Scripts-SpellLogic.ShouldFireFirstTimeOlympian ...

function game.SorceryChargeSetup(a, b) end
---@alias game-Scripts-SpellLogic.SorceryChargeSetup ...

function game.SpellCheckCharges(a, b, c) end
---@alias game-Scripts-SpellLogic.SpellCheckCharges ...

function game.SpellFire(a, b) end
---@alias game-Scripts-SpellLogic.SpellFire ...

function game.SpellHasMana(a) end
---@alias game-Scripts-SpellLogic.SpellHasMana ...

function game.SpellHasNoMana(a) end
---@alias game-Scripts-SpellLogic.SpellHasNoMana ...

function game.SpellMeteorFire() end
---@alias game-Scripts-SpellLogic.SpellMeteorFire ...

function game.SpellMultiuseExpire(a) end
---@alias game-Scripts-SpellLogic.SpellMultiuseExpire ...

function game.SpellPolymorphFire(a, b, c, d) end
---@alias game-Scripts-SpellLogic.SpellPolymorphFire ...

function game.SpellPotion(a, b, c) end
---@alias game-Scripts-SpellLogic.SpellPotion ...

function game.SpellPotionCheckCharges(a, b, c) end
---@alias game-Scripts-SpellLogic.SpellPotionCheckCharges ...

function game.SpellPrecharge(a, b) end
---@alias game-Scripts-SpellLogic.SpellPrecharge ...

function game.SpellRegen() end
---@alias game-Scripts-SpellLogic.SpellRegen ...

function game.SpellReloadStarted(a, b) end
---@alias game-Scripts-SpellLogic.SpellReloadStarted ...

function game.SpellSummon(a, b) end
---@alias game-Scripts-SpellLogic.SpellSummon ...

function game.SpellSummonCheckCharges(a, b, c) end
---@alias game-Scripts-SpellLogic.SpellSummonCheckCharges ...

function game.SpellTransform(a, b, c, d) end
---@alias game-Scripts-SpellLogic.SpellTransform ...

function game.StartCooldownBuff() end
---@alias game-Scripts-SpellLogic.StartCooldownBuff ...

function game.StartReverseBurn(a, b) end
---@alias game-Scripts-SpellLogic.StartReverseBurn ...

function game.StartSpellCharge(a, b, c) end
---@alias game-Scripts-SpellLogic.StartSpellCharge ...

function game.StartSpellSlow(a, b, c, d) end
---@alias game-Scripts-SpellLogic.StartSpellSlow ...

function game.StartTimeSlowCrit(a) end
---@alias game-Scripts-SpellLogic.StartTimeSlowCrit ...

function game.StartTimeSlowFreeze(a) end
---@alias game-Scripts-SpellLogic.StartTimeSlowFreeze ...

function game.StartTimeSlowSpeed() end
---@alias game-Scripts-SpellLogic.StartTimeSlowSpeed ...

function game.StartTransformBurst() end
---@alias game-Scripts-SpellLogic.StartTransformBurst ...

function game.SummonCastTeleport(a, b, c) end
---@alias game-Scripts-SpellLogic.SummonCastTeleport ...

function game.SummonTakeDamage(a, b, c) end
---@alias game-Scripts-SpellLogic.SummonTakeDamage ...

function game.TeleportSummonsToPlayer(a) end
---@alias game-Scripts-SpellLogic.TeleportSummonsToPlayer ...

function game.TimeSlowDamageBonus(a, b, c) end
---@alias game-Scripts-SpellLogic.TimeSlowDamageBonus ...

function game.TimeSlowDestroyProjectiles() end
---@alias game-Scripts-SpellLogic.TimeSlowDestroyProjectiles ...

function game.TimeSlowResetBuff() end
---@alias game-Scripts-SpellLogic.TimeSlowResetBuff ...

function game.TransformArmCast() end
---@alias game-Scripts-SpellLogic.TransformArmCast ...

function game.TransformCheckApolloBoon(a) end
---@alias game-Scripts-SpellLogic.TransformCheckApolloBoon ...

function game.TransformRespawnBurst(a, b) end
---@alias game-Scripts-SpellLogic.TransformRespawnBurst ...

function game.UpdateSpellActiveStatus(a) end
---@alias game-Scripts-SpellLogic.UpdateSpellActiveStatus ...

function game.UpdateTalentPointInvestedCache(a) end
---@alias game-Scripts-SpellLogic.UpdateTalentPointInvestedCache ...

function game.ZeusStrikeNearProjectile(a, b) end
---@alias game-Scripts-SpellLogic.ZeusStrikeNearProjectile ...

return game