---@meta game-Scripts-StoreLogic
local game = {}

function game.AwardRandomStoreItem(a) end
---@alias game-Scripts-StoreLogic.AwardRandomStoreItem ...

function game.CheckChallengeSwitchItemValidity(a) end
---@alias game-Scripts-StoreLogic.CheckChallengeSwitchItemValidity ...

function game.CheckHeraclesShoppingEvent(a, b) end
---@alias game-Scripts-StoreLogic.CheckHeraclesShoppingEvent ...

function game.CheckNemesisShoppingEvent(a, b) end
---@alias game-Scripts-StoreLogic.CheckNemesisShoppingEvent ...

function game.CheckShoppingEventThread(a, b) end
---@alias game-Scripts-StoreLogic.CheckShoppingEventThread ...

function game.CloseStoreScreen(a, b) end
---@alias game-Scripts-StoreLogic.CloseStoreScreen ...

function game.CreateStoreButtons(a, b) end
---@alias game-Scripts-StoreLogic.CreateStoreButtons ...

function game.DestroyStoreButtons(a) end
---@alias game-Scripts-StoreLogic.DestroyStoreButtons ...

function game.FillInShopOptions(a) end
---@alias game-Scripts-StoreLogic.FillInShopOptions ...

function game.GetShopCostMultiplier() end
---@alias game-Scripts-StoreLogic.GetShopCostMultiplier ...

function game.HandleStorePurchase(a, b) end
---@alias game-Scripts-StoreLogic.HandleStorePurchase ...

function game.MouseOffWellShopButton(a) end
---@alias game-Scripts-StoreLogic.MouseOffWellShopButton ...

function game.MouseOverWellShopButton(a) end
---@alias game-Scripts-StoreLogic.MouseOverWellShopButton ...

function game.RecalculateStoreTraitDurations(a) end
---@alias game-Scripts-StoreLogic.RecalculateStoreTraitDurations ...

function game.RemoveStoreItem(a) end
---@alias game-Scripts-StoreLogic.RemoveStoreItem ...

function game.RerollStore(a, b) end
---@alias game-Scripts-StoreLogic.RerollStore ...

function game.RestockWorldItem(a, b, c) end
---@alias game-Scripts-StoreLogic.RestockWorldItem ...

function game.RunShopGeneration(a) end
---@alias game-Scripts-StoreLogic.RunShopGeneration ...

function game.SetupWorldShop(a, b) end
---@alias game-Scripts-StoreLogic.SetupWorldShop ...

function game.ShowStoreScreen() end
---@alias game-Scripts-StoreLogic.ShowStoreScreen ...

function game.SpawnStoreItemInWorld(a, b) end
---@alias game-Scripts-StoreLogic.SpawnStoreItemInWorld ...

function game.SpawnStoreItemsInWorld(a, b) end
---@alias game-Scripts-StoreLogic.SpawnStoreItemsInWorld ...

function game.StartShopping(a, b) end
---@alias game-Scripts-StoreLogic.StartShopping ...

function game.StartUpStore() end
---@alias game-Scripts-StoreLogic.StartUpStore ...

function game.StoreItemEligible(a, b) end
---@alias game-Scripts-StoreLogic.StoreItemEligible ...

function game.StoreItemNameEligible(a, b) end
---@alias game-Scripts-StoreLogic.StoreItemNameEligible ...

function game.UnwrapRandomLoot(a) end
---@alias game-Scripts-StoreLogic.UnwrapRandomLoot ...

function game.UpdateCostButton(a, b) end
---@alias game-Scripts-StoreLogic.UpdateCostButton ...

function game.UpdateCostText(a, b) end
---@alias game-Scripts-StoreLogic.UpdateCostText ...

function game.UpdateStoreItemCostText() end
---@alias game-Scripts-StoreLogic.UpdateStoreItemCostText ...

function game.UpdateStoreOptionsDictionary() end
---@alias game-Scripts-StoreLogic.UpdateStoreOptionsDictionary ...

function game.UpdateStoreReroll(a, b, c) end
---@alias game-Scripts-StoreLogic.UpdateStoreReroll ...

return game