---@meta game-Scripts-TraitLogic
local game = {}

function game.AddRandomBouldyBlessing(a, b) end
---@alias game-Scripts-TraitLogic.AddRandomBouldyBlessing ...

function game.AddRarityToTraits(a, b) end
---@alias game-Scripts-TraitLogic.AddRarityToTraits ...

function game.AddStackToTraits(a, b) end
---@alias game-Scripts-TraitLogic.AddStackToTraits ...

function game.AddTrait(a, b, c, d) end
---@alias game-Scripts-TraitLogic.AddTrait ...

function game.AddTraitData(a, b, c) end
---@alias game-Scripts-TraitLogic.AddTraitData ...

function game.AddTraitToHero(a) end
---@alias game-Scripts-TraitLogic.AddTraitToHero ...

function game.AddTraitToHeroSource(a, b) end
---@alias game-Scripts-TraitLogic.AddTraitToHeroSource ...

function game.ApplyLinkedTraitPropertyChanges(a, b) end
---@alias game-Scripts-TraitLogic.ApplyLinkedTraitPropertyChanges ...

function game.ApplyTraitSetupFunctions(a, b) end
---@alias game-Scripts-TraitLogic.ApplyTraitSetupFunctions ...

function game.AreTraitsIdentical(a, b) end
---@alias game-Scripts-TraitLogic.AreTraitsIdentical ...

function game.CalcNumLootChoices(a) end
---@alias game-Scripts-TraitLogic.CalcNumLootChoices ...

function game.ChaosHammerUpgrade(a) end
---@alias game-Scripts-TraitLogic.ChaosHammerUpgrade ...

function game.CheckActivatedTraits(a, b) end
---@alias game-Scripts-TraitLogic.CheckActivatedTraits ...

function game.CheckChamberTraits() end
---@alias game-Scripts-TraitLogic.CheckChamberTraits ...

function game.CheckChillKill(a, b, c, d) end
---@alias game-Scripts-TraitLogic.CheckChillKill ...

function game.CreditAccumulatedTime(a, b, c) end
---@alias game-Scripts-TraitLogic.CreditAccumulatedTime ...

function game.CreditMissingStacks(a, b, c) end
---@alias game-Scripts-TraitLogic.CreditMissingStacks ...

function game.CreditMissingStacksThread(a, b, c) end
---@alias game-Scripts-TraitLogic.CreditMissingStacksThread ...

function game.DistributeLevels(a, b) end
---@alias game-Scripts-TraitLogic.DistributeLevels ...

function game.DumbFireWeapon(a, b, c) end
---@alias game-Scripts-TraitLogic.DumbFireWeapon ...

function game.EquipReferencedWeapons(a) end
---@alias game-Scripts-TraitLogic.EquipReferencedWeapons ...

function game.ExtractValue(a, b, c, d) end
---@alias game-Scripts-TraitLogic.ExtractValue ...

function game.ExtractValues(a, b, c, d) end
---@alias game-Scripts-TraitLogic.ExtractValues ...

function game.FormatExtractedValue(a, b) end
---@alias game-Scripts-TraitLogic.FormatExtractedValue ...

function game.GetAllLootSourceNames(a, b) end
---@alias game-Scripts-TraitLogic.GetAllLootSourceNames ...

function game.GetAllUpgradeableGodTraits(a) end
---@alias game-Scripts-TraitLogic.GetAllUpgradeableGodTraits ...

function game.GetEligibleTransformingTrait(a) end
---@alias game-Scripts-TraitLogic.GetEligibleTransformingTrait ...

function game.GetExtractData(a, b) end
---@alias game-Scripts-TraitLogic.GetExtractData ...

function game.GetGodSourceName(a, b) end
---@alias game-Scripts-TraitLogic.GetGodSourceName ...

function game.GetHeroTrait(a) end
---@alias game-Scripts-TraitLogic.GetHeroTrait ...

function game.GetHeroTraitValues(a, b) end
---@alias game-Scripts-TraitLogic.GetHeroTraitValues ...

function game.GetLootSourceName(a, b) end
---@alias game-Scripts-TraitLogic.GetLootSourceName ...

function game.GetProcessedTraitData(a) end
---@alias game-Scripts-TraitLogic.GetProcessedTraitData ...

function game.GetProcessedValue(a, b, c) end
---@alias game-Scripts-TraitLogic.GetProcessedValue ...

function game.GetTotalHeroTraitValue(a, b) end
---@alias game-Scripts-TraitLogic.GetTotalHeroTraitValue ...

function game.GetTotalLootChoices() end
---@alias game-Scripts-TraitLogic.GetTotalLootChoices ...

function game.GetTotalTraitCount(a) end
---@alias game-Scripts-TraitLogic.GetTotalTraitCount ...

function game.GetTraitCount(a, b) end
---@alias game-Scripts-TraitLogic.GetTraitCount ...

function game.GetTraitUniqueId() end
---@alias game-Scripts-TraitLogic.GetTraitUniqueId ...

function game.GrantBoons(a, b) end
---@alias game-Scripts-TraitLogic.GrantBoons ...

function game.HasHeroTraitValue(a) end
---@alias game-Scripts-TraitLogic.HasHeroTraitValue ...

function game.HasRarifiableTraits(a) end
---@alias game-Scripts-TraitLogic.HasRarifiableTraits ...

function game.HasSuperchargeableBoon(a, b) end
---@alias game-Scripts-TraitLogic.HasSuperchargeableBoon ...

function game.HeraSuperchargeBoon(a, b, c) end
---@alias game-Scripts-TraitLogic.HeraSuperchargeBoon ...

function game.HeroHasTrait(a) end
---@alias game-Scripts-TraitLogic.HeroHasTrait ...

function game.HeroSlotFilled(a) end
---@alias game-Scripts-TraitLogic.HeroSlotFilled ...

function game.IncreaseTraitLevel(a, b) end
---@alias game-Scripts-TraitLogic.IncreaseTraitLevel ...

function game.IncrementTraitCooldown(a, b) end
---@alias game-Scripts-TraitLogic.IncrementTraitCooldown ...

function game.IsGodTrait(a, b) end
---@alias game-Scripts-TraitLogic.IsGodTrait ...

function game.IsTraitActive(a) end
---@alias game-Scripts-TraitLogic.IsTraitActive ...

function game.LogTraitUses(a) end
---@alias game-Scripts-TraitLogic.LogTraitUses ...

function game.MergeWeaponDataOverride(a, b) end
---@alias game-Scripts-TraitLogic.MergeWeaponDataOverride ...

function game.PommableSlottedTraitCountAtLeast(a, b) end
---@alias game-Scripts-TraitLogic.PommableSlottedTraitCountAtLeast ...

function game.ProcessTraitData(a) end
---@alias game-Scripts-TraitLogic.ProcessTraitData ...

function game.ProcessValue(a, b) end
---@alias game-Scripts-TraitLogic.ProcessValue ...

function game.PutTraitOnCooldown(a) end
---@alias game-Scripts-TraitLogic.PutTraitOnCooldown ...

function game.ReduceTraitUses(a, b) end
---@alias game-Scripts-TraitLogic.ReduceTraitUses ...

function game.RemoveActivatedRarityBonus(a, b) end
---@alias game-Scripts-TraitLogic.RemoveActivatedRarityBonus ...

function game.RemoveTrait(a, b, c) end
---@alias game-Scripts-TraitLogic.RemoveTrait ...

function game.RemoveTraitAfterDuration(a, b, c) end
---@alias game-Scripts-TraitLogic.RemoveTraitAfterDuration ...

function game.RemoveTraitData(a, b, c) end
---@alias game-Scripts-TraitLogic.RemoveTraitData ...

function game.RemoveWeaponTrait(a, b) end
---@alias game-Scripts-TraitLogic.RemoveWeaponTrait ...

function game.ReplaceDerivedValues(a) end
---@alias game-Scripts-TraitLogic.ReplaceDerivedValues ...

function game.RunTraitThreads(a) end
---@alias game-Scripts-TraitLogic.RunTraitThreads ...

function game.SacrificeAllBoon(a, b) end
---@alias game-Scripts-TraitLogic.SacrificeAllBoon ...

function game.SetTraitsOnLoot(a, b) end
---@alias game-Scripts-TraitLogic.SetTraitsOnLoot ...

function game.SetTraitTextData(a, b) end
---@alias game-Scripts-TraitLogic.SetTraitTextData ...

function game.SetTransformingTraitsOnLoot(a, b) end
---@alias game-Scripts-TraitLogic.SetTransformingTraitsOnLoot ...

function game.UpdateHeroTraitDictionary() end
---@alias game-Scripts-TraitLogic.UpdateHeroTraitDictionary ...

function game.UpdateUpgradableTraitCount(a, b) end
---@alias game-Scripts-TraitLogic.UpdateUpgradableTraitCount ...

function game.UpgradableGodTraitCountAtLeast(a) end
---@alias game-Scripts-TraitLogic.UpgradableGodTraitCountAtLeast ...

function game.UpgradeAllCommon(a, b) end
---@alias game-Scripts-TraitLogic.UpgradeAllCommon ...

function game.UpgradeAspect(a, b) end
---@alias game-Scripts-TraitLogic.UpgradeAspect ...

function game.UseHeroTraitsWithValue(a, b) end
---@alias game-Scripts-TraitLogic.UseHeroTraitsWithValue ...

function game.UseStoreRewardRandomStack(a) end
---@alias game-Scripts-TraitLogic.UseStoreRewardRandomStack ...

function game.UseTrait(a, b) end
---@alias game-Scripts-TraitLogic.UseTrait ...

function game.UseTraitData(a, b) end
---@alias game-Scripts-TraitLogic.UseTraitData ...

function game.ValidateTraitData() end
---@alias game-Scripts-TraitLogic.ValidateTraitData ...

function game.WaitAndReactivate(a) end
---@alias game-Scripts-TraitLogic.WaitAndReactivate ...

return game