---@meta game-Scripts-UIPresentation
local game = {}

function game.ChronosHealthBarTextTransition(a) end
---@alias game-Scripts-UIPresentation.ChronosHealthBarTextTransition ...

function game.DisplayBiomeLocationBanner(a, b) end
---@alias game-Scripts-UIPresentation.DisplayBiomeLocationBanner ...

function game.DisplayInfoBanner(a, b) end
---@alias game-Scripts-UIPresentation.DisplayInfoBanner ...

function game.DisplayInfoToast(a, b) end
---@alias game-Scripts-UIPresentation.DisplayInfoToast ...

function game.GenericInfoPresentation(a, b) end
---@alias game-Scripts-UIPresentation.GenericInfoPresentation ...

function game.GenericMouseOverPresentation(a) end
---@alias game-Scripts-UIPresentation.GenericMouseOverPresentation ...

function game.GenericScreenCloseFinishedPresentation(a) end
---@alias game-Scripts-UIPresentation.GenericScreenCloseFinishedPresentation ...

function game.GenericScreenClosePresentation(a) end
---@alias game-Scripts-UIPresentation.GenericScreenClosePresentation ...

function game.GenericScreenOpenEndPresentation(a) end
---@alias game-Scripts-UIPresentation.GenericScreenOpenEndPresentation ...

function game.GenericScreenOpenStartPresentation(a) end
---@alias game-Scripts-UIPresentation.GenericScreenOpenStartPresentation ...

function game.GenericScrollPresentation(a, b) end
---@alias game-Scripts-UIPresentation.GenericScrollPresentation ...

function game.HUDTraitAddedPresentation(a, b) end
---@alias game-Scripts-UIPresentation.HUDTraitAddedPresentation ...

function game.InterstitialWaitForInput(a) end
---@alias game-Scripts-UIPresentation.InterstitialWaitForInput ...

function game.PulseContextActionPresentation(a, b) end
---@alias game-Scripts-UIPresentation.PulseContextActionPresentation ...

function game.RunClearMessagePresentation(a, b, c) end
---@alias game-Scripts-UIPresentation.RunClearMessagePresentation ...

function game.RunInterstitialPresentation(a, b) end
---@alias game-Scripts-UIPresentation.RunInterstitialPresentation ...

function game.ScreenCantAffordPresentation(a, b, c) end
---@alias game-Scripts-UIPresentation.ScreenCantAffordPresentation ...

function game.TraitTrayHoverOnPresentation(a, b) end
---@alias game-Scripts-UIPresentation.TraitTrayHoverOnPresentation ...

function game.TraitTrayPinOffPresentation(a, b) end
---@alias game-Scripts-UIPresentation.TraitTrayPinOffPresentation ...

function game.TraitTrayPinOnPresentation(a, b) end
---@alias game-Scripts-UIPresentation.TraitTrayPinOnPresentation ...

function game.UpgradeChoiceScreenOpenStartPresentation(a, b) end
---@alias game-Scripts-UIPresentation.UpgradeChoiceScreenOpenStartPresentation ...

return game