---@meta game-Scripts-UpgradeLogic
local game = {}

function game.ApplyAllTraitWeapons(a) end
---@alias game-Scripts-UpgradeLogic.ApplyAllTraitWeapons ...

function game.ApplyEnemyTraits(a, b) end
---@alias game-Scripts-UpgradeLogic.ApplyEnemyTraits ...

function game.ApplyLifePropertyChange(a, b, c) end
---@alias game-Scripts-UpgradeLogic.ApplyLifePropertyChange ...

function game.ApplyProjectilePropertyChanges(a, b) end
---@alias game-Scripts-UpgradeLogic.ApplyProjectilePropertyChanges ...

function game.ApplyTraitUpgrade(a, b) end
---@alias game-Scripts-UpgradeLogic.ApplyTraitUpgrade ...

function game.ApplyUnitPropertyChange(a, b, c, d, e) end
---@alias game-Scripts-UpgradeLogic.ApplyUnitPropertyChange ...

function game.ApplyUnitPropertyChanges(a, b, c, d, e) end
---@alias game-Scripts-UpgradeLogic.ApplyUnitPropertyChanges ...

function game.ApplyWeaponPropertyChange(a, b, c, d, e) end
---@alias game-Scripts-UpgradeLogic.ApplyWeaponPropertyChange ...

function game.ClampSprintSpeed(a) end
---@alias game-Scripts-UpgradeLogic.ClampSprintSpeed ...

function game.DeleteMatchingPropertyChange(a, b) end
---@alias game-Scripts-UpgradeLogic.DeleteMatchingPropertyChange ...

function game.GatherAndEquipWeapons(a) end
---@alias game-Scripts-UpgradeLogic.GatherAndEquipWeapons ...

function game.GetDerivedPropertyChangeValues(a) end
---@alias game-Scripts-UpgradeLogic.GetDerivedPropertyChangeValues ...

function game.GetPropertyOrderingValue(a, b) end
---@alias game-Scripts-UpgradeLogic.GetPropertyOrderingValue ...

function game.GetRandomUnequippedWeapon(a) end
---@alias game-Scripts-UpgradeLogic.GetRandomUnequippedWeapon ...

function game.GetTraitOrderingValue(a) end
---@alias game-Scripts-UpgradeLogic.GetTraitOrderingValue ...

function game.HandleWeaponAnimSwaps() end
---@alias game-Scripts-UpgradeLogic.HandleWeaponAnimSwaps ...

function game.HasMeleeWeapon(a) end
---@alias game-Scripts-UpgradeLogic.HasMeleeWeapon ...

function game.IsBonusUnusedWeapon(a) end
---@alias game-Scripts-UpgradeLogic.IsBonusUnusedWeapon ...

function game.IsWeaponUnlocked(a) end
---@alias game-Scripts-UpgradeLogic.IsWeaponUnlocked ...

function game.IsWeaponUntouched(a) end
---@alias game-Scripts-UpgradeLogic.IsWeaponUntouched ...

function game.OrderAndApplyPropertyChanges(a) end
---@alias game-Scripts-UpgradeLogic.OrderAndApplyPropertyChanges ...

function game.ProcessHeroTraitChanges(a, b) end
---@alias game-Scripts-UpgradeLogic.ProcessHeroTraitChanges ...

function game.RecordTraitPropertyChange(a, b, c) end
---@alias game-Scripts-UpgradeLogic.RecordTraitPropertyChange ...

function game.RemoveTraitPropertyChange(a, b, c) end
---@alias game-Scripts-UpgradeLogic.RemoveTraitPropertyChange ...

function game.ReorderPropertyChanges(a) end
---@alias game-Scripts-UpgradeLogic.ReorderPropertyChanges ...

function game.TraitOrderingSort(a, b) end
---@alias game-Scripts-UpgradeLogic.TraitOrderingSort ...

return game