---@meta game-Scripts-WeaponLogic
local game = {}

---@class game-Scripts-WeaponLogic*BlinkControlReleaseWeapons
---@field [any] any

---@type game-Scripts-WeaponLogic*BlinkControlReleaseWeapons
game.BlinkControlReleaseWeapons = ...
---@alias game-Scripts-WeaponLogic.BlinkControlReleaseWeapons ...

function game.AllowAxeSpin() end
---@alias game-Scripts-WeaponLogic.AllowAxeSpin ...

function game.AllowLobLock() end
---@alias game-Scripts-WeaponLogic.AllowLobLock ...

function game.ApolloExSetup(a, b) end
---@alias game-Scripts-WeaponLogic.ApolloExSetup ...

function game.ApplyDeferredThrowReversions(a) end
---@alias game-Scripts-WeaponLogic.ApplyDeferredThrowReversions ...

function game.ApplySprintSpeedIncrease(a, b) end
---@alias game-Scripts-WeaponLogic.ApplySprintSpeedIncrease ...

function game.ApplyWeaponChanges(a, b, c, d) end
---@alias game-Scripts-WeaponLogic.ApplyWeaponChanges ...

function game.AxeChargeStage(a, b) end
---@alias game-Scripts-WeaponLogic.AxeChargeStage ...

function game.BlockDashDisable(a, b) end
---@alias game-Scripts-WeaponLogic.BlockDashDisable ...

function game.BlockLaunchMissile(a, b, c) end
---@alias game-Scripts-WeaponLogic.BlockLaunchMissile ...

function game.BlockSelfBuff(a, b, c) end
---@alias game-Scripts-WeaponLogic.BlockSelfBuff ...

function game.CastArmedFunction(a, b, c, d) end
---@alias game-Scripts-WeaponLogic.CastArmedFunction ...

function game.CastChargeStage(a, b) end
---@alias game-Scripts-WeaponLogic.CastChargeStage ...

function game.CheckAspectBounces(a, b) end
---@alias game-Scripts-WeaponLogic.CheckAspectBounces ...

function game.CheckAutoSprint() end
---@alias game-Scripts-WeaponLogic.CheckAutoSprint ...

function game.CheckAutoSprintEnd() end
---@alias game-Scripts-WeaponLogic.CheckAutoSprintEnd ...

function game.CheckAxeSpinDisable(a, b, c, d) end
---@alias game-Scripts-WeaponLogic.CheckAxeSpinDisable ...

function game.CheckConsecutiveDamage(a, b, c) end
---@alias game-Scripts-WeaponLogic.CheckConsecutiveDamage ...

function game.CheckDashManeuverEnd() end
---@alias game-Scripts-WeaponLogic.CheckDashManeuverEnd ...

function game.CheckEarlyPowershot() end
---@alias game-Scripts-WeaponLogic.CheckEarlyPowershot ...

function game.CheckExecute(a, b, c) end
---@alias game-Scripts-WeaponLogic.CheckExecute ...

function game.CheckFinisher(a, b, c) end
---@alias game-Scripts-WeaponLogic.CheckFinisher ...

function game.CheckLobPulse(a, b, c) end
---@alias game-Scripts-WeaponLogic.CheckLobPulse ...

function game.CheckMissileOnHit(a, b, c) end
---@alias game-Scripts-WeaponLogic.CheckMissileOnHit ...

function game.CheckSelfBuffBlast(a, b) end
---@alias game-Scripts-WeaponLogic.CheckSelfBuffBlast ...

function game.CheckSpinControl(a, b, c) end
---@alias game-Scripts-WeaponLogic.CheckSpinControl ...

function game.CheckSprintBoons(a) end
---@alias game-Scripts-WeaponLogic.CheckSprintBoons ...

function game.CheckSuitChargedDisable(a, b, c, d) end
---@alias game-Scripts-WeaponLogic.CheckSuitChargedDisable ...

function game.CheckSuitComboAttackBuff(a, b, c) end
---@alias game-Scripts-WeaponLogic.CheckSuitComboAttackBuff ...

function game.CheckSuitEnemiesInRange(a, b) end
---@alias game-Scripts-WeaponLogic.CheckSuitEnemiesInRange ...

function game.CheckTraitExecuteStatus(a, b) end
---@alias game-Scripts-WeaponLogic.CheckTraitExecuteStatus ...

function game.CheckWeaponRoomStartEvents() end
---@alias game-Scripts-WeaponLogic.CheckWeaponRoomStartEvents ...

function game.ClearEnemySeekStatus(a) end
---@alias game-Scripts-WeaponLogic.ClearEnemySeekStatus ...

function game.CreateProjectileFromUnitDelay(a, b) end
---@alias game-Scripts-WeaponLogic.CreateProjectileFromUnitDelay ...

function game.CreateSuitAimlines(a) end
---@alias game-Scripts-WeaponLogic.CreateSuitAimlines ...

function game.DaggerChargeStage(a, b) end
---@alias game-Scripts-WeaponLogic.DaggerChargeStage ...

function game.DashManeuver(a) end
---@alias game-Scripts-WeaponLogic.DashManeuver ...

function game.DoSuitExAttackBlock(a, b) end
---@alias game-Scripts-WeaponLogic.DoSuitExAttackBlock ...

function game.DoThrowEx(a) end
---@alias game-Scripts-WeaponLogic.DoThrowEx ...

function game.DoWeaponCharge(a, b, c) end
---@alias game-Scripts-WeaponLogic.DoWeaponCharge ...

function game.EmptyAxeCharge(a, b, c) end
---@alias game-Scripts-WeaponLogic.EmptyAxeCharge ...

function game.EmptyCastCharge(a, b) end
---@alias game-Scripts-WeaponLogic.EmptyCastCharge ...

function game.EmptyDaggerCharge(a) end
---@alias game-Scripts-WeaponLogic.EmptyDaggerCharge ...

function game.EmptyIndirectCastCharge(a, b) end
---@alias game-Scripts-WeaponLogic.EmptyIndirectCastCharge ...

function game.EmptyLobCharge(a, b, c) end
---@alias game-Scripts-WeaponLogic.EmptyLobCharge ...

function game.EmptySprintCharge(a, b, c) end
---@alias game-Scripts-WeaponLogic.EmptySprintCharge ...

function game.EmptyStaffCharge(a, b) end
---@alias game-Scripts-WeaponLogic.EmptyStaffCharge ...

function game.EmptySuitAttackCharge(a, b, c) end
---@alias game-Scripts-WeaponLogic.EmptySuitAttackCharge ...

function game.EmptySuitCharge(a, b) end
---@alias game-Scripts-WeaponLogic.EmptySuitCharge ...

function game.EmptyThrowAspectCharge(a, b) end
---@alias game-Scripts-WeaponLogic.EmptyThrowAspectCharge ...

function game.EmptyThrowCharge(a, b) end
---@alias game-Scripts-WeaponLogic.EmptyThrowCharge ...

function game.EmptyTorchCharge(a, b) end
---@alias game-Scripts-WeaponLogic.EmptyTorchCharge ...

function game.EmptyTorchSpecialCharge(a, b) end
---@alias game-Scripts-WeaponLogic.EmptyTorchSpecialCharge ...

function game.EmptyWeaponCharge(a, b, c, d) end
---@alias game-Scripts-WeaponLogic.EmptyWeaponCharge ...

function game.EndAutoSprint(a) end
---@alias game-Scripts-WeaponLogic.EndAutoSprint ...

function game.EndAxeSpinDisable() end
---@alias game-Scripts-WeaponLogic.EndAxeSpinDisable ...

function game.EndDashDisableForce() end
---@alias game-Scripts-WeaponLogic.EndDashDisableForce ...

function game.EndNergalBuff() end
---@alias game-Scripts-WeaponLogic.EndNergalBuff ...

function game.EndShivaBuff() end
---@alias game-Scripts-WeaponLogic.EndShivaBuff ...

function game.EndSprintControlDown() end
---@alias game-Scripts-WeaponLogic.EndSprintControlDown ...

function game.FireAmmoCollectionPulse(a, b) end
---@alias game-Scripts-WeaponLogic.FireAmmoCollectionPulse ...

function game.FireAnywhereCastAtLocation(a, b, c, d) end
---@alias game-Scripts-WeaponLogic.FireAnywhereCastAtLocation ...

function game.FireCastAtLocation(a) end
---@alias game-Scripts-WeaponLogic.FireCastAtLocation ...

function game.GetChangeFromBaseValue(a, b) end
---@alias game-Scripts-WeaponLogic.GetChangeFromBaseValue ...

function game.GetLuaWeaponSpeedMultiplier(a) end
---@alias game-Scripts-WeaponLogic.GetLuaWeaponSpeedMultiplier ...

function game.GetWeaponChargeStages(a) end
---@alias game-Scripts-WeaponLogic.GetWeaponChargeStages ...

function game.HandleBonusStrikes(a, b) end
---@alias game-Scripts-WeaponLogic.HandleBonusStrikes ...

function game.HandleChargeAnimation(a, b, c) end
---@alias game-Scripts-WeaponLogic.HandleChargeAnimation ...

function game.HandleEarlyPerfectCharge(a, b, c, d) end
---@alias game-Scripts-WeaponLogic.HandleEarlyPerfectCharge ...

function game.HandleEarlySwap(a, b) end
---@alias game-Scripts-WeaponLogic.HandleEarlySwap ...

function game.HasForceRelease(a, b) end
---@alias game-Scripts-WeaponLogic.HasForceRelease ...

function game.HoldSprintUntilInput() end
---@alias game-Scripts-WeaponLogic.HoldSprintUntilInput ...

function game.IndirectCastChargeStage(a, b) end
---@alias game-Scripts-WeaponLogic.IndirectCastChargeStage ...

function game.IsEnemyExecutable(a, b, c) end
---@alias game-Scripts-WeaponLogic.IsEnemyExecutable ...

function game.IsExWeapon(a, b, c) end
---@alias game-Scripts-WeaponLogic.IsExWeapon ...

function game.LobChargeStage(a, b) end
---@alias game-Scripts-WeaponLogic.LobChargeStage ...

function game.LogProjectileSuitCharged(a, b, c) end
---@alias game-Scripts-WeaponLogic.LogProjectileSuitCharged ...

function game.MarkAdditionalDaggerTarget(a, b, c) end
---@alias game-Scripts-WeaponLogic.MarkAdditionalDaggerTarget ...

function game.MarkDaggerTarget(a, b, c) end
---@alias game-Scripts-WeaponLogic.MarkDaggerTarget ...

function game.MarkTorchTarget(a, b, c) end
---@alias game-Scripts-WeaponLogic.MarkTorchTarget ...

function game.ProjectileHasUnitHit(a, b) end
---@alias game-Scripts-WeaponLogic.ProjectileHasUnitHit ...

function game.ProjectileHasUnitWaveHit(a, b, c, d) end
---@alias game-Scripts-WeaponLogic.ProjectileHasUnitWaveHit ...

function game.ProjectileRecordUnitHit(a, b) end
---@alias game-Scripts-WeaponLogic.ProjectileRecordUnitHit ...

function game.ProjectileRecordUnitWaveHit(a, b, c, d) end
---@alias game-Scripts-WeaponLogic.ProjectileRecordUnitWaveHit ...

function game.RecordWeaponCharge(a, b, c, d) end
---@alias game-Scripts-WeaponLogic.RecordWeaponCharge ...

function game.RemoveMissileMark(a, b, c) end
---@alias game-Scripts-WeaponLogic.RemoveMissileMark ...

function game.RemoveTorchTarget(a) end
---@alias game-Scripts-WeaponLogic.RemoveTorchTarget ...

function game.RepeatTripleStrike(a, b, c, d) end
---@alias game-Scripts-WeaponLogic.RepeatTripleStrike ...

function game.ResetClipRegenTriggerLock(a, b, c) end
---@alias game-Scripts-WeaponLogic.ResetClipRegenTriggerLock ...

function game.ResetConsecutiveHits(a, b) end
---@alias game-Scripts-WeaponLogic.ResetConsecutiveHits ...

function game.ResetFireSequence(a, b) end
---@alias game-Scripts-WeaponLogic.ResetFireSequence ...

function game.RevertSuitChanges(a, b, c) end
---@alias game-Scripts-WeaponLogic.RevertSuitChanges ...

function game.RevertWeaponChanges(a, b) end
---@alias game-Scripts-WeaponLogic.RevertWeaponChanges ...

function game.ShieldBlock(a, b) end
---@alias game-Scripts-WeaponLogic.ShieldBlock ...

function game.SprintChargeStage(a, b) end
---@alias game-Scripts-WeaponLogic.SprintChargeStage ...

function game.StaffBall2FiredFunction(a, b, c, d) end
---@alias game-Scripts-WeaponLogic.StaffBall2FiredFunction ...

function game.StaffChargeStage(a, b) end
---@alias game-Scripts-WeaponLogic.StaffChargeStage ...

function game.StartTorchCharge(a, b) end
---@alias game-Scripts-WeaponLogic.StartTorchCharge ...

function game.SuitAttackChargeStage(a, b) end
---@alias game-Scripts-WeaponLogic.SuitAttackChargeStage ...

function game.SuitBaseMissileAttack(a, b) end
---@alias game-Scripts-WeaponLogic.SuitBaseMissileAttack ...

function game.SuitChargeStage(a, b) end
---@alias game-Scripts-WeaponLogic.SuitChargeStage ...

function game.SuitHaltPlayer() end
---@alias game-Scripts-WeaponLogic.SuitHaltPlayer ...

function game.SuitSeekThread(a, b) end
---@alias game-Scripts-WeaponLogic.SuitSeekThread ...

function game.ThrowAspectChargeStage(a, b) end
---@alias game-Scripts-WeaponLogic.ThrowAspectChargeStage ...

function game.ThrowChargeStage(a, b) end
---@alias game-Scripts-WeaponLogic.ThrowChargeStage ...

function game.TorchChargeStage(a, b) end
---@alias game-Scripts-WeaponLogic.TorchChargeStage ...

function game.TorchExEmpowerSetup(a) end
---@alias game-Scripts-WeaponLogic.TorchExEmpowerSetup ...

function game.TorchHasMana(a) end
---@alias game-Scripts-WeaponLogic.TorchHasMana ...

function game.TorchOutOfMana(a) end
---@alias game-Scripts-WeaponLogic.TorchOutOfMana ...

function game.TorchRepeatedFire(a, b, c, d) end
---@alias game-Scripts-WeaponLogic.TorchRepeatedFire ...

function game.TorchSpecialChargeStage(a, b) end
---@alias game-Scripts-WeaponLogic.TorchSpecialChargeStage ...

function game.TriggerLockForSpecial() end
---@alias game-Scripts-WeaponLogic.TriggerLockForSpecial ...

function game.UnequipSuitWeapon() end
---@alias game-Scripts-WeaponLogic.UnequipSuitWeapon ...

function game.UnlogProjectileSuitCharged(a, b, c) end
---@alias game-Scripts-WeaponLogic.UnlogProjectileSuitCharged ...

function game.UpdateExecuteStatus(a, b) end
---@alias game-Scripts-WeaponLogic.UpdateExecuteStatus ...

function game.UpdateLobWeaponProjectileNum(a, b) end
---@alias game-Scripts-WeaponLogic.UpdateLobWeaponProjectileNum ...

function game.WeaponBlinkFunction(a, b, c) end
---@alias game-Scripts-WeaponLogic.WeaponBlinkFunction ...

function game.WeaponLobAmmoDrop(a, b) end
---@alias game-Scripts-WeaponLogic.WeaponLobAmmoDrop ...

function game.WeaponSuitAmmoTransform(a, b) end
---@alias game-Scripts-WeaponLogic.WeaponSuitAmmoTransform ...

return game