---@meta game-Scripts-WeaponPresentation
local game = {}

function game.ClearBlinkAlpha(a) end
---@alias game-Scripts-WeaponPresentation.ClearBlinkAlpha ...

function game.EndPlayerBlinkAlpha() end
---@alias game-Scripts-WeaponPresentation.EndPlayerBlinkAlpha ...

function game.NoSuitSpecialTargetCombatText(a) end
---@alias game-Scripts-WeaponPresentation.NoSuitSpecialTargetCombatText ...

function game.NoSuitSpecialTargetPresentation(a) end
---@alias game-Scripts-WeaponPresentation.NoSuitSpecialTargetPresentation ...

function game.NyxBuffEndPresentation(a) end
---@alias game-Scripts-WeaponPresentation.NyxBuffEndPresentation ...

function game.NyxBuffReadyEndPresentation() end
---@alias game-Scripts-WeaponPresentation.NyxBuffReadyEndPresentation ...

function game.NyxBuffReadyPresentation() end
---@alias game-Scripts-WeaponPresentation.NyxBuffReadyPresentation ...

function game.NyxBuffStartPresentation(a, b) end
---@alias game-Scripts-WeaponPresentation.NyxBuffStartPresentation ...

function game.StartPlayerBlinkAlpha() end
---@alias game-Scripts-WeaponPresentation.StartPlayerBlinkAlpha ...

function game.SuitMaxMissilesLockedPresentation(a) end
---@alias game-Scripts-WeaponPresentation.SuitMaxMissilesLockedPresentation ...

function game.TorchExEmpowerPresentationEnd() end
---@alias game-Scripts-WeaponPresentation.TorchExEmpowerPresentationEnd ...

function game.TorchExEmpowerPresentationStart() end
---@alias game-Scripts-WeaponPresentation.TorchExEmpowerPresentationStart ...

function game.WeaponChargeStageReachedPresentation(a, b, c, d, e, f) end
---@alias game-Scripts-WeaponPresentation.WeaponChargeStageReachedPresentation ...

function game.WeaponChargeStageStartPresentation(a, b, c, d, e) end
---@alias game-Scripts-WeaponPresentation.WeaponChargeStageStartPresentation ...

function game.WeaponChargeStartPresentation(a, b, c) end
---@alias game-Scripts-WeaponPresentation.WeaponChargeStartPresentation ...

return game