---@meta game-Scripts-WeaponShopPresentation
local game = {}

function game.MouseOffWeaponShopItem(a) end
---@alias game-Scripts-WeaponShopPresentation.MouseOffWeaponShopItem ...

function game.MouseOverWeaponShopItem(a) end
---@alias game-Scripts-WeaponShopPresentation.MouseOverWeaponShopItem ...

function game.ToolExorcismBookUnlockedPresentation() end
---@alias game-Scripts-WeaponShopPresentation.ToolExorcismBookUnlockedPresentation ...

function game.ToolFishingRodUnlockedPresentation() end
---@alias game-Scripts-WeaponShopPresentation.ToolFishingRodUnlockedPresentation ...

function game.ToolPickaxeUnlockedPresentation() end
---@alias game-Scripts-WeaponShopPresentation.ToolPickaxeUnlockedPresentation ...

function game.ToolShovelUnlockedPresentation() end
---@alias game-Scripts-WeaponShopPresentation.ToolShovelUnlockedPresentation ...

function game.UpdateWeaponShopInteractionText(a, b) end
---@alias game-Scripts-WeaponShopPresentation.UpdateWeaponShopInteractionText ...

function game.UsedWeaponShopPresentation(a, b) end
---@alias game-Scripts-WeaponShopPresentation.UsedWeaponShopPresentation ...

function game.WeaponShopCloseCategory(a, b) end
---@alias game-Scripts-WeaponShopPresentation.WeaponShopCloseCategory ...

function game.WeaponShopItemPurchasedPresentation(a, b, c) end
---@alias game-Scripts-WeaponShopPresentation.WeaponShopItemPurchasedPresentation ...

function game.WeaponShopPanToKit(a, b) end
---@alias game-Scripts-WeaponShopPresentation.WeaponShopPanToKit ...

function game.WeaponShopPurchaseNoEquipPresentation(a, b, c, d) end
---@alias game-Scripts-WeaponShopPresentation.WeaponShopPurchaseNoEquipPresentation ...

function game.WeaponShopPurchasePostActivatePresentation(a, b, c) end
---@alias game-Scripts-WeaponShopPresentation.WeaponShopPurchasePostActivatePresentation ...

function game.WeaponShopPurchasePreActivatePresentation(a, b, c, d) end
---@alias game-Scripts-WeaponShopPresentation.WeaponShopPurchasePreActivatePresentation ...

function game.WeaponShopRevealCategoryPresentation(a, b, c) end
---@alias game-Scripts-WeaponShopPresentation.WeaponShopRevealCategoryPresentation ...

function game.WeaponShopScreenCloseFinishedPresentation(a, b) end
---@alias game-Scripts-WeaponShopPresentation.WeaponShopScreenCloseFinishedPresentation ...

function game.WeaponShopScreenCloseStartPresentation(a, b) end
---@alias game-Scripts-WeaponShopPresentation.WeaponShopScreenCloseStartPresentation ...

function game.WeaponShopScreenOpenedPresentation(a, b) end
---@alias game-Scripts-WeaponShopPresentation.WeaponShopScreenOpenedPresentation ...

function game.WeaponShopScreenOpenFinishedPresentation(a) end
---@alias game-Scripts-WeaponShopPresentation.WeaponShopScreenOpenFinishedPresentation ...

function game.WeaponShopScreenSelectCategoryPresentation(a, b) end
---@alias game-Scripts-WeaponShopPresentation.WeaponShopScreenSelectCategoryPresentation ...

return game